### ISSUE TITLE
[v0.3.11-beta06] Glide typing does not work when text field is blank

### ISSUE THREAD

**Issue by MarissaRS** [florisboard/florisboard#847] opened 2021-05-09 21:03 UTC
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Try using glide typing on an empty text field
2. The gesture trail shows as expected
3. No words are typed by the keyboard
4. Note that glide typing in a textfield with text works as expected. 

For reference, see [this video](https://imgur.com/a/LA7KgKW) showing how gesture typing doesn't work unless there's text typed before it. 

#### Environment information
- FlorisBoard Version: v0.3.11-beta06
- Install Source: F-Droid
- Device: Google Pixel 4
- Android: 11, CalyxOS

**Comment by marissarousseau** [comment] 2021-05-09 21:07
I just messed around with it some more, and it seems to be really inconsistent. Some blank text fields work fine (like the GitHub app search bar) but others not so much (Signal app message text box).

**Comment by just-Nob** [comment] 2021-05-09 22:15
Same here.

In my case, after updating from beta04 to beta06, I had the same issue.
I also recognized that it wasn't possible to write any by glide typing when the cursor was at the start of a new line (i.e. after entering [return]) **and** _shift_ or _caps lock_ enabled.

After trying to reproduce that behavior by fiddling around a bit, suddenly I wasn't able to write **_any_** word by glide typing! This behavior was resettable by killing _FlorisBoard Beta_ using Android's system settings.

In order to have a comprehensible starting point, I completely deleted FlorisBoard"s app data in the system settings (which is more or less equal to a fresh installation) and then only activated glide typing in FlorisBoard's settings (after doing the initial setup which is requested when opening FlorisBoard for the first time) - with the result that glide typing did not work at all until I stopped _FlorisBoard Beta_ once again in the system settings.

**Comment by patrickgold** [comment] 2021-05-09 22:34
Thanks for your bug report! This took me some time to experiment but it seems like there's indeed something strange going on and glide typing does not always trigger for whatever reason and also not on every device (works completely fine on my OnePlus 7T) but has some strange bugs as described above on my Samsung phone. I am currently investigating what could be the cause. Maybe I will do a hotfix release on stable on Tuesday should the issue be identified on several devices and fixable by me.

**Comment by just-Nob** [comment] 2021-05-09 22:39
Faulty behavior is still present in v3.11.
(I guess that version was compiled before this issue came up.)

**Comment by patrickgold** [comment] 2021-05-09 22:40
>  (I guess that version was compiled before this issue came up.)

Yup that's why I mentioned doing a hotfix release either tomorrow or on Tuesday. I can't really recall the stable version anymore but if I find the culprit of this bug I can push a new new release.

**Comment by patrickgold** [comment] 2021-05-09 22:49
OK after some investigation I think the problem is that since the layout rework the key's code is not fixed anymore (when shift is active the codes change), and this heavily confuses the glide typing logic. Meaning: the glide typing manager only knows the lowercase keys, not the uppercase keys.

**Comment by just-Nob** [comment] 2021-05-09 23:22
Now it's getting really weird - I try to explain:
- To install the latest v0.3.11, I had to uninstall v0.3.10 due to different signature, because v0.3.10 was taken from F-Droid and I didn't want to  wait until v0.3.11 being available on F-Droid.
- Before  deinstallation, I backuped both apk & data of v0.3.10 using OAndBackupX.
- After deinstallation, I installed v0.3.11 from Github, then tried to restore data from v0.3.10 urging OAndBackupX.
- After that, I recognized that the strange behavior was still present in v0.3.11, and I wanted to go back to v0.3.10 (I have installed both _release_ and _beta_ in parallel).
- I tried to restore both app & data using OAndBackupX, but **without** uninstalling v0.3.11 first, because I was lazy and unsure if OAndBackupX is able to overwrite the app.
- OAndBackup wasn't able to overwrite (release version stayed at v0.3.11), but after that, glide typing works correctly on **both** v0.3.11 **and** v3.11-beta06... - that's really crazy!

**Comment by patrickgold** [comment] 2021-05-09 23:35
OAndBackup wasn't able to overwrite v0.3.11 with v0.3.10 (release version stayed at v0.3.11), but after that, glide typing works correctly on both v0.3.11 and v3.11-beta06... - that's really crazy!

But only as long as you don't activate shift/caps, or does it work even then (if that's the case I question the laws of integer comparison). The problem is that since the layout rework the code of a character key changes when pressing shift and the glide logic only knew the lowercase keys.

If possible could you try out the debug APK of the above linked PR and see if the glide logic behavior has improved (it should now work flawlessly when shift/caps is activated)?

**Comment by tsiflimagas** [comment] 2021-05-10 00:03
@patrickgold seems to be working fine for me. What a quick fix!

**Comment by patrickgold** [comment] 2021-05-10 01:11
Thanks for the feedback! I will wait on the feedback from other users to confirm that glide typing is working properly again in the debug APK, then will make a hotfix release tomorrow (Monday).

**Comment by pokegamer5547** [comment] 2021-05-10 02:15
@patrickgold ah sorry for asking here im a noob but how can we gef debug apk? I would like to help too with this bug

**Comment by patrickgold** [comment] 2021-05-10 07:41
@pokegamer5547 The debug APK can be found [here](https://github.com/florisboard/florisboard/pull/848/checks), then click Artifacts and download the APK. The debug release installs separately from your main installation.

**Comment by patrickgold** [comment] 2021-05-10 07:52
Sry misclick.

Direct link to the APK: https://github.com/florisboard/florisboard/suites/2693643873/artifacts/59354881

Maybe this link works, else I honestly don't know, as normally it does work via Artifacts.

**Comment by pokegamer5547** [comment] 2021-05-10 07:55
> Sry misclick.
> 
> Direct link to the APK: https://github.com/florisboard/florisboard/suites/2693643873/artifacts/59354881
> 
> Maybe this link works, else I honestly don't know, as normally it does work via Artifacts.
Its ok and thanks i got able to download now with youe link. I will test it too right now and report back.

**Comment by Surendrajat** [comment] 2021-05-10 08:52
@patrickgold you might want to check https://nightly.link for linking the latest debug builds. The following link will always give latest artifact, even without logging into GH:
https://nightly.link/florisboard/florisboard/workflows/android/master

**Comment by Glitchy-Tozier** [comment] 2021-05-10 09:13
> gesture typing is working again now for all apps except my launcher.

What launcher do you use?

**Comment by leso-kn** [comment] 2021-05-10 09:19
@patrickgold I can confirm, that the bug does not occur anymore after disabling auto-capitalization option is disabled and giving FlorisBoard a restart. Then glide typing works if the caps key is not toggled. If the auto caps option is enabled, thus, capital letters are displayed while the keyboard opens, glide typing does not work for me, even after turnig off caps manually. My device is Oneplus 5 (cheeseburger)

**Comment by just-Nob** [comment] 2021-05-10 10:24
> If the auto caps option is enabled (thus, capital letters are displayed while the keyboard opens), glide typing does not work for me, even after turnig off caps manually.

Can't confirm that behavior using the debug version.
Auto caps option (e.g. for capital letters at the start of a new line) was enabled on my phone after installation, and I didn't change that.
When opening FlorisBoard Debug by tapping on a text field, Shift is automatically enabled, but nevertheless glide typing works fine here.

**Comment by patrickgold** [comment] 2021-05-10 13:22
Thanks everyone for the feedback, really appreciate it! It seems that in general glide typing is fixed in the latest debug artifact, so I will merge it into master and together with some other minor improvements from X-yl I will release v0.3.12 as a hotfix release later on.

> I guess that the weird behavior of the previous versions (v0.3.11 + v0.3.11-beta06) is somehow dependent of some settings + ...the weather, maybe? ;-)

It can only be the weather I guess :) Everything else just makes no sense at all...

**Closed** 2021-05-10 13:22 UTC
Labels: bug, bug-confirmed, priority-0-urgent
