### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [florisboard/florisboard#2103] opened 2022-11-02 20:33 UTC
#### Environment information
- FlorisBoard [0.4.0-alpha04](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha04) (90)
- Device: Samsung SM-F721U (b4qsqw)
- Android: 12 (cn=S_V2 sdk=32)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-11-02T20:26:12.240307Z
Manufacturer        : samsung
Model               : SM-F721U
Product             : b4qsqw
Android             : 12 (cn=S_V2 sdk=32) [SP2A.220305.013.F721USQU1AVHH]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.67 GiB (65.79% used, 7.10 GiB max)
Font scale          : 1.0
Locales             : en-US

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha04 (90)
Build type          : beta
Build commit hash   : 31a01c8d39ba425e4e1e424e9671ffbb96c24fc0
Java heap memory    : 7.70 MiB (3.01% used, 256.00 MiB max)
Native heap memory  : 25.84 MiB (83.42% used, 30.97 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1667420768427.stacktrace</summary>

```
java.lang.IllegalArgumentException: offset(-1) is out of bounds [0, 0]
	at androidx.compose.ui.text.MultiParagraph.requireIndexInRangeInclusiveEnd(MultiParagraph.kt:9)
	at androidx.compose.ui.text.TextLayoutResult.getWordBoundary--jx7JFs(TextLayoutResult.kt:2)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrevWordOffset(TextPreparedSelection.kt:4)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$5.invoke(TextFieldKeyInput.kt:5)
	at androidx.compose.foundation.text.selection.TextFieldPreparedSelection.deleteIfSelectedOr(TextPreparedSelection.kt:3)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:95)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke(TextFieldKeyInput.kt:28)
	at androidx.compose.ui.input.key.KeyInputModifier.propagateKeyEvent-ZmokQxo(KeyInputModifier.kt:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:24)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:1070)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4251)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(Unknown Source:0)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:4)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:892)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7851)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7674)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7045)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7102)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7068)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7266)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7076)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7323)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7049)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7102)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7068)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7076)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7049)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10584)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10432)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10388)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6657)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6521)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8855)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>

**Comment by KLaurence** [comment] 2022-11-04 02:40
This is likely a duplicate of #2001

**Comment by tsiflimagas** [comment] 2023-05-20 20:43
I think you're right, the stacktraces are identical.

**Closed** 2023-05-20 20:44 UTC
Labels: bug
