### ISSUE TITLE
Settings are forgotten / reset randomly

### ISSUE THREAD

**Issue by axelsimon** [florisboard/florisboard#2198] opened 2023-04-24 10:25 UTC
Hope this isn't a duplicate, couldn't see an obvious pre-existing issue!

#### Short description
After installing and setting up Florisboard, i find the keyboard back to the stock / default settings and need to go back into the settings to configure it.

Since installing about a week ago, i've arleady had to re-configure Florisboard 3 times. On the plus side, i have now exported my settings to easily import them next time :wink: 

#### Steps to reproduce
Can't tell. Settings reset seems random.

I have limited space left on the device (~1%) but that's still over 1 GB.

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: F-Droid (Neo Store)
- Device: Pixel 2
- Android: 11 (last GrapheneOS, RQ3A.210905.001.2021092816)

**Comment by BHydden** [comment] 2023-04-24 10:41
2 years w/o security updates 👀

**Comment by axelsimon** [comment] 2023-04-24 12:07
Tell me something i don't know :) If you want to know what happens to a battery after +4 years of constant use too, just let me know.

**Comment by klaurence** [comment] 2023-04-24 13:02
[A previous changelog entry](https://github.com/florisboard/florisboard/releases/tag/v0.3.16) said:
> - Possibly fix prefs sometimes reset on startup (#1726, #1868)
>   - Note that this bug occurs only on some devices and you probably haven't experienced this bug beforehand, so this fix does not apply to you
>   - Should you be the unlucky user to experience this bug after this release again, please provide more details in #1726, so I can try to find the reason why this bug rarely occurs. Thanks!

Please try downloading the newest version ([0.4.0-alpha04](https://github.com/florisboard/florisboard/releases/tag/v0.4.0-alpha04)) and check if settings still get reset.

**Comment by axelsimon** [comment] 2023-05-11 10:42
Same here, settings still get reset with 0.4.0-alpha04, sadly.

**Comment by tsiflimagas** [comment] 2023-09-28 11:47
Thank you for your report! This is a duplicate of #1726. So, let's keep discussion about this there. Just one question though, do you use English (United Kingdom) layout?

**Comment by axelsimon** [comment] 2023-09-28 13:42
@tsiflimagas yes, i do :)

**Comment by tsiflimagas** [comment] 2023-09-28 13:58
Interesting...there seems to be some relation there. Thanks!
So, now I'm closing this issue, for anything further, please write in #1726.

**Closed by tsiflimagas** 2023-09-28 13:58 UTC
Labels: bug, duplicate, area: settings
