### ISSUE TITLE
Crash Log (Dictionary/Prediction?)

### ISSUE THREAD

**Issue by GL513** [florisboard/florisboard#1298] opened 2021-09-28 15:04 UTC
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-A516V
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1632835064264.stacktrace</summary>

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 16
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:933)
	at java.lang.StringBuilder.substring(StringBuilder.java:77)
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getText(EditorInstance.kt:875)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:456)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1632835076637.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 656952 free bytes and 641KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 143654912 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.ArrayList.grow(ArrayList.java:275)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
	at java.util.ArrayList.add(ArrayList.java:467)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:141)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.prepareDictionaries(DictionaryManager.kt:109)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1$1.invokeSuspend(TextInputManager.kt:420)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment] 2021-09-28 17:31
Thanks for your bug report! This is probably caused because the memory is running out due to the old suggestion implementation. See #1268 for more info. The best workaround (currently) is to disable word suggestions. To keep the list of issues cleaner, I will close this issue as a duplicate of mentioned issue.

**Closed by patrickgold** 2021-09-28 17:31 UTC
Labels: bug

**Comment by GL513** [comment] 2021-09-29 11:44
Got it. I saw that, but couldnt be sure if it was the same bug.
