### ISSUE TITLE
Backspace gets held down randomly

### ISSUE THREAD

**Issue by ElishaAz** [florisboard/florisboard#1145] opened 2021-08-09 19:06 UTC
#### Short description
Every once in a while, letters start getting deleted, as if the backspace key is held down. Tapping the key once or twice stops the deletions. Seems to mostly happen after pressing the back button.

#### Steps to reproduce
I did not manage to purposely reproduce this error.

#### Environment information
- FlorisBoard Version: v0.3.13-beta08
- Install Source: Github
- Device: Redmi Note 8 (ginkgo)
- Android: 11, crDroid 7.9

**Comment by Glitchy-Tozier** [comment] 2021-08-10 19:27
Hi and thank you for taking the time to fill put this bug-report!  :)

This has been reported a couple of times and is a duplicate of #986.
It seems difficult to reproduce though, so if you manage to find a way to consistently get this to bug out, please mention it there!

**Closed** 2021-08-12 10:18 UTC
Labels: bug, duplicate
