### ISSUE TITLE
Either translate all quick actions or make them use the system language

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#2071] opened 2022-09-13 13:26 UTC
#### Short description
The quick actions overflow menu displays titles for the actions, with my setup it's not consistent

<details>

<summary>Show screenshot</summary>

![Screenshot_20220913-152302_FlorisBoard_Beta.png](https://user-images.githubusercontent.com/24937357/189912632-0c88fa7a-cd4f-4948-bc57-aebcbde2c4f1.png)

</details>

In my opinion it should use the system language for all of those labels as those actions are not really related to the current keyboard language. Alternatively it could be coupled together with the "Display language names in" setting.

#### Steps to reproduce
1. Have en-US as system language
2. Add another language to FlorisBoard
3. Open the overflow menu
4. See some actions using the system language and some the one from the keyboard

#### Environment information
- FlorisBoard Version: 0.4.0-alpha04
- Install Source: GitHub
- Device: OnePlus 8T
- Android: 11, Lineage for microG

**Comment by patrickgold** [comment] 2022-09-13 13:31
That's because FlorisBoard is entirely community-translated from the original source strings in English, so if a German translation is missing it will fall back to English. In a major release this issue may be pretty aesthetically unpleasing, however for an alpha release this is to be expected, especially as at the time of pulling the translations the original source strings where only available for a few days on Crowdin for translation. Closing as this is not a bug.

**Closed by patrickgold** 2022-09-13 13:31 UTC
Labels: bug

**Comment by patrickgold** [comment] 2022-09-13 13:45
> I'd still prefer it to use the system language, so could you change it into a feature request?

I think what you want is requested in #1991, if I am no mistaken?

**Comment by D3SOX** [comment] 2022-09-13 13:52
Yup, then this is a duplicate
