### ISSUE TITLE
Improve splash of clipboard-manager-items

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1114] opened 2021-07-28 11:49 UTC
Make the splash actually fit the card/button, no paddings and no sharp edges.

Screenshot of me long-pressing the item on the top-left:

![florisPop](https://user-images.githubusercontent.com/59611881/127317451-bde51366-2a7b-4f39-8966-f6eb952830ab.jpeg)

**Comment by patrickgold** [comment] 2021-08-14 10:00
Thanks for your suggestion!

I see what you mean, although I don't know how easy this is to achieve, as we'd have to calculate the corners to be cut out of the splash animation. Will assign it to the list of clipboard proposals and when I find the time see what I can do!

**Comment by Glitchy-Tozier** [comment] 2021-08-14 11:24
I don't have any Kotlin experience, but in Flutter I'd just move the splash-animation inside the card.

Could something like this be accomplished here?

**Comment by patrickgold** [comment] 2021-08-14 17:22
> I don't have any Kotlin experience, but in Flutter I'd just move the splash-animation inside the card.

Kotlin isn't the problem here but the outdated Android view system. The splash animation for the clipboard item is basically the foreground of the box and is just drawn above the background shape - the problem is that the card is technically still a rectangle, the rounded corners are just an illusion. Also @ X-yl used the default splash animation here it seems, I would have to provide a custom one for the rounded corners. It is definitely doable but currently there are more important fixes tbh.

**Comment by Glitchy-Tozier** [comment] 2021-08-14 17:51
> It is definitely doable but currently there are more important fixes tbh.

Absolutely, let's focus on my other bugs.  ;)

**Comment by patrickgold** [comment] 2021-12-11 19:21
As discussed in the Matrix group chat this has been fixed by the new clipboard UI implementation for beta07. Will assign this issue to the beta07 PR, so GH will auto close this issue once I merge the beta07 branch in.

**Comment by Glitchy-Tozier** [comment] 2021-12-12 16:05
Great to hear! :)

**Closed** 2021-12-12 17:24 UTC
Labels: proposal, proposal-accepted, area: clipboard
