### ISSUE TITLE
Password fill-in from smartbar doesn't work with Firefox

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#1556] opened 2022-02-08 11:02 UTC
#### Short description
Fill-in from smartbar works perfectly from any app or any textbox except when using Firefox. The fill-in option shows up in the smartbar, opens my password manager app (Bitwarden), I can select the password I want to be filled in but the textboxes stay empty. Works fine with the system option that shows up just under the textboxes but less convenient of course.

#### Environment information
- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Device: Poco F1
- Android: 11, ROM : crDroid 7.13

**Comment by patrickgold** [comment] 2022-03-06 15:20
Thanks for your bug report!

Could you please try out the latest beta 0.3.14-beta13 and check if it is still this buggy? (The beta installs separately and won't touch your existing installation at all).

**Comment by patrickgold** [comment] 2024-10-11 11:05
Using the newest release v0.4.1, can you still reproduce this issue or does it work now?

**Comment by tsiflimagas** [comment] 2024-10-11 11:52
It seems that the author has deleted his account, so I guess this will remain unconfirmed.

**Comment by patrickgold** [comment] 2024-10-11 11:55
You are right I missed that, thanks for pointing it out. Then I will just close this issue, other similar issues have confirmed that inline autofill works much more reliable since the PR that reworked it.

**Closed by patrickgold** 2024-10-11 11:55 UTC
Labels: bug, not reproducible, area: inline-autofill
