### ISSUE TITLE
Capitalization doesn't work correctly in raw input (termux)

### ISSUE THREAD

**Issue by FuturisticGoo** [florisboard/florisboard#1010] opened 2021-06-08 08:17 UTC
#### Short description
When using first letter capitalization in termux, instead of  automatically switching back to lowercase after the first letter is typed, its stays in uppercase and the letters are typed in all caps. It also shows the same behavior in another terminal app but not in normal text inputs.

#### Steps to reproduce
1. Go to Termux
2. Press caps lock once
3. Type something
4. Instead of only having the first letter capitalized, all letters are in uppercase
 
#### Environment information
- FlorisBoard Version: v0.3.13-beta03
- Install Source: F-Droid
- Device: Samsung SM-J700F
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = false
clipboard_history = true
```

#### Screen recording
Recording shows the expected behavior in other text input apps and then shows the buggy behavior in termux.

https://user-images.githubusercontent.com/28504180/121148996-e4bd6d80-c85f-11eb-84e7-dfe9bc368ae7.mp4

**Comment by FuturisticGoo** [comment] 2021-06-09 03:54
Updated to version v0.3.13-beta04, still shows same behavior

**Comment by bertin0** [comment] 2021-06-10 13:10
I am also affected by this issue

**Comment by KLaurence** [comment] 2021-08-23 13:02
This bug also occurs for me. It first appeared in PR #966 with its debug artifact and doesn't occur in PR #963's artifact.

**Comment by blackCauldron7** [comment] 2021-11-03 13:54
I can confirm this too

**Comment by BobIsMyManager** [comment] 2021-11-27 22:33
This used to happen to me but it doesnt anymore, i think it was after a miui update

**Comment by patrickgold** [comment] 2021-11-28 10:17
Thanks for your bug report! This is a known issue and already filed in #1010, although currently I do not know the cause of this issue. Closing this issue as a duplicate.

**Comment by patrickgold** [comment] 2021-11-28 10:18
Oops wrong issue meant to close #1405

**Comment by unilock** [comment] 2021-11-29 02:44
Maybe you can close this anyway, since this issue seems to have been resolved with v0.3.14-beta06 :)

**Comment by nvllsvm** [comment] 2021-11-29 02:47
I can also confirm that this is resolved with v0.3.14-beta06

**Comment by FuturisticGoo** [comment] 2021-11-29 03:42
Indeed, this has been resolved. Thank you dev! Closing it.

**Closed** 2021-11-29 03:45 UTC
Labels: bug, bug-confirmed, area: kbd-logic

**Comment by patrickgold** [comment] 2021-11-29 16:58
Ok that was not intended at all, but I am happy to see that it is fixed with the new keyboard logic on beta06. Thanks for the feedback!
