### ISSUE TITLE
Some suggestions here👇

### ISSUE THREAD

**Issue by lookerloo** [florisboard/florisboard#1933] opened 2022-07-04 10:17 UTC
(1).Provide latest AOSP style border theme as a standard option in theme section

![IMG_20220630_203037.jpg](https://user-images.githubusercontent.com/108591373/177134528-b5177ae4-e432-4025-858e-eec5e71be55b.jpg)

(2).

![IMG_20220704_153925.jpg](https://user-images.githubusercontent.com/108591373/177134669-d7aab3f4-87ae-48be-9c59-8e720bd8e177.jpg)

(3).

![IMG_20220630_213950.jpg](https://user-images.githubusercontent.com/108591373/177134848-dd2993cf-8563-46d9-91b8-9cbbb6434525.jpg)

**Comment by tsiflimagas** [comment] 2022-07-04 14:03
1) FlorisBoard's default theme already looks similar to this. I don't see why it has to be exactly the same, it's two different keyboards after all. You can create it yourself in the theme editor and use it, however.

2) Duplicate of #142.

3) You can already do this in theme editor (key code = 10).

**Comment by Glitchy-Tozier** [comment] 2022-07-04 20:32
@lookerloo Thank you for writing up your ideas and providing helpful images!
A small hint that would make future contributions more productive: It's way easier for developers to keep track of your suggestions if you split them up into separate issues. This way, they can be worked on & closed individually.

Regarding your requests:
- As @tsiflimagas pointed out, most of this functionality already exists in the theme-editor. Of course, ideally settings should be designed to indicate where to go for functionality like this; theme-editing isn't easy for new users. As far as I know, one of the future milestones is making theme-editing more accessible.
- For your second point, did you mean swiping across the emoji-board or swiping the space-key to switch between emoji-categories?

**Comment by lookerloo** [comment] 2022-07-05 13:45
> A small hint that would make future contributions more productive: It's way easier for developers to keep track of your suggestions if you split them up into separate issues. This way, they can be worked on & closed individually.


I'm very sorry for the inconvenience.

Next time I will correct all mistake from my side.

Thanks a million for your patience, hard work, and  dedication🎉

**Comment by Mokura** [comment] 2022-07-05 14:44
> (1).Provide latest AOSP style border theme as a standard option in theme section
>

I made a quick and dirty AOSP Dark, but I'm unsure how to import/export just that one theme.  Preview:

![Screenshot_20220705-103312_FlorisBoard_1](https://user-images.githubusercontent.com/5167919/177354785-59bc388a-d577-479e-ae9b-9e80fa49de0f.png)

**Comment by lookerloo** [comment] 2022-07-05 15:13
> > (1).Provide latest AOSP style border theme as a standard option in theme section
> >
> 
> I made a quick and dirty AOSP Dark, but I'm unsure how to import/export just that one theme.  Preview:
> 
> ![Screenshot_20220705-103312_FlorisBoard_1](https://user-images.githubusercontent.com/5167919/177354785-59bc388a-d577-479e-ae9b-9e80fa49de0f.png)
> 

Looks good, I like it👍

**Comment by tsiflimagas** [comment] 2022-07-07 01:04
> I made a quick and dirty AOSP Dark, but I'm unsure how to import/export just that one theme.

For now, you'd have to export themes from the settings export menu, then maybe export it from the zip, if you have more themes (wip or whatever) exported with it.

So, is there anything more to do here?

**Comment by Glitchy-Tozier** [comment] 2022-07-07 20:50
> So, is there anything more to do here?

@tsiflimagas I guess that depends on whether we want to turn this into a "Swipe space to switch emoji-cathegories"-issue.

I'm of the opinion that this wouldn't be great behaviour; ideally, space-swiping would do the same thing on every keyboard.

**Comment by tsiflimagas** [comment] 2022-07-08 20:04
> I'm of the opinion that this wouldn't be great behaviour; ideally, space-swiping would do the same thing on every keyboard.

I agree. I think your issue is just what is needed, but in any case, more discussion can be done there. Thus I guess this one's safe to close.

**Closed by tsiflimagas** 2022-07-08 20:04 UTC
Labels: proposal
