### ISSUE TITLE
FlorisBoard does not load after powering on

### ISSUE THREAD

**Issue by madhavmehta1** [florisboard/florisboard#1046] opened 2021-06-29 08:34 UTC
#### Short description
Describe the bug in a short but concise way.
I let my phone die for the first time after installing FlorisBoard.  Upon restart, I could not and still cannot enter my passphrase because apparently there is no keyboard.

#### Steps to reproduce
1. Install FlorisBoard, 
2. Make it default keyboard
3. Uninstall other keyboards
4. Let phone die or restart phone
5. No keyboard popup to enter passphrase

#### Environment information
- FlorisBoard Version: ~No idea, cannot check either since I cannot enter my phone~ 0.3.12
- Install Source: F-Droid
- Device: Samsung Galaxy S10e
- Android: 11

**Comment by Glitchy-Tozier** [comment] 2021-06-29 11:39
That definitely doesn't sound fun!

Is it the regular lock-screen we're talking about or some kind of bootup-screen?

**Comment by madhavmehta1** [comment] 2021-06-30 20:45
> That definitely doesn't sound fun!
> 
> Is it the regular lock-screen we're talking about or some kind of bootup-screen?

It is the lock screen. I was able to get into my phone using a physical keyboard and found I am using version 0.3.12. After installing Simple Keyboard from F-Droid as a backup keyboard, I attempted to make FlorisBoard my default keyboard again and received this alert
![img](https://user-images.githubusercontent.com/12778610/124028284-6fa20b80-d9b9-11eb-8ddd-593cf8e13d45.jpg)

I'm not too familiar with how apps gain startup permissions, but Simple Keyboard from F-Droid does not require the phone to be unlocked for it to start and be used. Is there a reason FlorisBoard requires the phone to be unlocked to be used?

Thanks in advance.

**Comment by Glitchy-Tozier** [comment] 2021-07-01 06:05
I honestly don't know anything about this popup, so let's wait for someone more qualified to come along.

**Comment by gammerboy** [comment] 2021-07-03 15:27
#1021 might be related to this.

**Comment by Duvio** [comment] 2021-07-09 07:25
It's probably your own fault. It's an OS restriction that no other apps can be started before the lock is unlocked for the forst time after reboot but the system services and the systems own keyboard. NEVER disable Samsung Keyboard or exactly this will happen to you. Try connecting an OTG keyboard to your phone or continue to google your problem. I and many others had the same problem, and you should probably close the issue since this expected behavior has nothing to do with FlorisBoard and cannot be circumvented

**Comment by patrickgold** [comment] 2021-07-10 01:06
Thanks for your bug report! First off, currently FlorisBoard does not support direct boot - the above screenshot is the exact dialog of the system alerting you of this exact thing. When a keyboard does not support direct boot, you won't be able to use it when the device is locked after booting (I don't know why Android has this rule, but it is probably because of some security restrictions). I haven't gotten around to review #1021 yet, but it might add direct boot support (by adding a permission and registering a broadcast receiver listening to the BOOT_COMPLETED event afaik) and with this also that FlorisBoard can start before the phone gets unlocked.

I am glad that you were able to get access using your physical keyboard, because such situations can lead to a device reset in the worst case, and that is definitely no fun (why Android does not offer a recovery keyboard for login in such cases is beyond my understanding, but yeah).

I will finish off some work in the spelling branch today then push it as an experimental tagged feature into master. After this I will then make sure to review the direct boot support PR so I can see if such situations can be avoided in the future.

**Comment by madhavmehta1** [comment] 2021-07-10 19:15
@patrickgold thanks for the detailed explanation!

**Closed** 2021-07-14 18:34 UTC
Labels: bug, bug-confirmed

**Comment by patrickgold** [comment] 2021-07-14 18:36
Above PR adds basic support for direct boot, will show a fallback keyboard when showing on a freshly booted locked phone. Will be available in the bta06 release!

The main restriction currently is that the layout is always QWERTY in this mode, a layout switcher for this mode may be added in the future.
