### ISSUE TITLE
Request to add the letter ç to the layout of the Brazilian version of the keyboard

### ISSUE THREAD

**Issue by Neiyr** [florisboard/florisboard#2188] opened 2023-04-05 18:07 UTC
I'd like to ask about the possibility of adding the letter ç to the Brazilian version of the keyboard, as in to the right of the letter L, instead of having to hold the C character every time.

**Comment by tsiflimagas** [comment] 2023-05-22 16:01
Thanks for your suggestion! This is actually a duplicate of #1939, and as noted there, this layout is already available as Catalan (QWERTY), which just may not be the most obvious name for most users

**Closed by tsiflimagas** 2023-05-22 16:01 UTC
Labels: proposal, area: kbd-layout
