### ISSUE TITLE
Add toggle for popup selection method

### ISSUE THREAD

**Issue by Offerel** [florisboard/florisboard#949] opened 2021-05-27 09:14 UTC
#### Short description
Selecting a key from a popup becomes really difficult sometime, because to select the right key does not react to the right position. For example, long press the a key, to select the @ sign. The popup appears at the expected position (or at least near this). But to select the @ sign, you can't press the @ sign. Instead of this, i must select some "empty" space below the @ sign. This got more worse, when you have more than one row in the popup. 

#### Steps to reproduce
1. open the keyboard
2. long press the a key
3. try to select the @ sign
4. directly hit the key does not work
5. select something 2 rows lower, will select the @ sign

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: GitHub
- Device: Galaxy S20FE
- Android: 11
- Language: German

**Comment by patrickgold** [comment] 2021-05-31 03:44
Thanks for your bug report!

The described behavior of the popups sounds to me that they work exactly as intended. The popup touch hitbox is exactly 1 row off on purpose as you start in the lower row immediately after long-pressing and it would be awkward if you had to move your input pointer up 2 rows every time you want to access some key from the second row. Though I see where you are coming from, AnySoftKeyboard for instance has the behavior you want, while FlorisBoard leans towards Gboard's behavior. I like Gboard's way of the popup logic and this logic will always stay as the default, though I am open to add a toggle to override this and require you to move exactly over the key to select it.

I will place this on my todo list, though it may need some time before it is implemented.

**Comment by Offerel** [comment] 2021-05-31 12:02
Amazing! You are absolutely right! I use Gboard actually also daily, however, I get along with the layout there immediately, where I have typos with your keyboard. I thought it was because of the popup keys, but when I compare it directly with Gboard, the behavior is identical. I am really amazed. Maybe it's the colors or something else, I have no real explanation. I'll try to set the colors identical to Gboard. Maybe that will help.

**Comment by Glitchy-Tozier** [comment] 2021-06-05 09:16
Cleaning up: This soundl like it could be closed, is that correct?

**Comment by Offerel** [comment] 2021-06-06 05:22
From my point of view yes but im not sure if the dev has something to add.

**Comment by patrickgold** [comment] 2021-08-03 19:37
> Cleaning up: This sounds like it could be closed, is that correct?

Depends on @Offerel  if a separate toggle for AnySoftKeyboard's behavior is wanted or not.

**Comment by Offerel** [comment] 2021-08-03 20:21
At least for me, the current behavior is fine.

**Comment by patrickgold** [comment] 2021-08-03 21:28
Ok thanks for clarifying, I will close this issue then!

**Closed by patrickgold** 2021-08-03 21:28 UTC
Labels: area: kbd-ui, proposal, proposal-accepted
