### ISSUE TITLE
I tried slide space bar to delete a word, when the field was empty

### ISSUE THREAD

**Issue by uggrin** [florisboard/florisboard#2027] opened 2022-08-28 23:32 UTC
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

#### Environment information
- FlorisBoard [0.4.0-alpha03](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha03) (89)
- Device: Samsung SM-G980F (x1seea)
- Android: 12 (cn=S sdk=31)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-08-28T23:30:34.230171Z
Manufacturer        : samsung
Model               : SM-G980F
Product             : x1seea
Android             : 12 (cn=S sdk=31) [SP1A.210812.016.G980FXXUEFVDB]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.18 GiB (57.49% used, 7.27 GiB max)
Font scale          : 0.9
Locales             : en-US,en-GB,de-AT

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha03 (89)
Build type          : beta
Build commit hash   : 26650d2a00d509efbbd58bafa8606ba11bc5961f
Java heap memory    : 7.24 MiB (2.83% used, 256.00 MiB max)
Native heap memory  : 33.90 MiB (86.93% used, 38.99 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1661729431071.stacktrace</summary>

```
java.lang.IllegalArgumentException: offset(-1) is out of bounds [0, 0]
	at androidx.compose.ui.text.MultiParagraph.requireIndexInRangeInclusiveEnd(MultiParagraph.kt:9)
	at androidx.compose.ui.text.TextLayoutResult.getWordBoundary--jx7JFs(TextLayoutResult.kt:2)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrevWordOffset(TextPreparedSelection.kt:4)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$5.invoke(TextFieldKeyInput.kt:5)
	at androidx.compose.foundation.text.selection.TextFieldPreparedSelection.deleteIfSelectedOr(TextPreparedSelection.kt:3)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:95)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke(TextFieldKeyInput.kt:28)
	at androidx.compose.ui.input.key.KeyInputModifier.propagateKeyEvent-ZmokQxo(KeyInputModifier.kt:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:24)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:1004)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4225)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(Unknown Source:0)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:4)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7714)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7537)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6914)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6971)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6937)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7135)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7192)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6918)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6971)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6937)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6918)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10367)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10215)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10171)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6531)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6395)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>

**Comment by patrickgold** [comment] 2022-08-29 12:06
Duplicate of #2001. Closing thus.

**Closed by patrickgold** 2022-08-29 12:06 UTC
Labels: bug
