### ISSUE TITLE
[AssetManager.kt] java.lang.NullPointerException: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by hornedfiend** [florisboard/florisboard#1351] opened 2021-10-24 23:00 UTC
#### Environment information
- FlorisBoard Version: 0.3.14-beta04 (60)
- Device: Google Pixel 5
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1635116204290.stacktrace</summary>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter jsonConfig
	at dev.patrickgold.florisboard.res.AssetManager.loadJsonAsset-0E7RQCE(Unknown Source:12)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.indexInternalModule(ExtensionManager.kt:173)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.refresh(ExtensionManager.kt:134)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.access$refresh(ExtensionManager.kt:102)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex$1.invokeSuspend(ExtensionManager.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment] 2021-11-05 00:31
@hornedfiend 
@Donkey-Doug
@absoluteinc

(pinging all of you because you reported this crash)

Above commit is a potential fix for this issue. Could any of you please check the debug build if this crash is fixed? For me this issue is not reproducible but I get quite a few reports, so something must go wrong here and I need feedback if my potential fix actually fixed this crash. (https://github.com/florisboard/florisboard/pull/1370/checks)

**Comment by Donkey-Doug** [comment] 2021-11-05 00:45
I am not able to find the debug build apk. Is it this link: https://github.com/florisboard/florisboard/pull/1370/checks

**Comment by patrickgold** [comment] 2021-11-05 00:48
Yes, then Artifacts > app-debug.apk

**Comment by Donkey-Doug** [comment] 2021-11-05 13:25
I think the debug version solves issue #1374. Not sure about this issue, since the crashes do not happen frequently.

**Comment by patrickgold** [comment] 2021-11-05 15:01
Thanks for testing this out! What we can do is that I assign this issue to PR #1370 and see it as solved, but should you encounter it in further testing or beta06 we can open this issue again.

> Not sure about this issue, since the crashes do not happen frequently.

For me this crash is not reproducible at all, so a complete hit-or-miss. This is the reason why I am solely reliant on feedback from the original reporters of this crash.

**Closed** 2021-11-27 19:56 UTC
Labels: bug, area: other, not reproducible
