### ISSUE TITLE
Wrong way of  writing an Arabic letter

### ISSUE THREAD

**Issue by uabas** [florisboard/florisboard#438] opened 2021-03-05 11:01 UTC
I will give an example of the issue.

Keyboard writing:**سﺅال**

What it shoud look like:**سؤال**

So the problem is with the letter (ﺅ)

**Comment by patrickgold** [comment] 2021-03-06 10:58
Looks like there's an issue with the Unicode encoding, will investigate into this.

**Comment by rex07** [comment] 2021-04-07 03:25
This is not fixed yet I'm on the last release

**Comment by rex07** [comment] 2021-04-16 02:46
@patrickgold Thank you for the best keyboard
i'm on the last release and this is not fixed yet.

**Comment by rex07** [comment] 2021-05-01 04:34
Hi @patrickgold his is still not fixed by the layout rework is there  away to fix this annoying letter problem.

And by tha way thanks for the good work:smile::

**Comment by patrickgold** [comment] 2021-05-01 11:27
Hmm yeah I didn't really address this issue specifically sorry. If possible, could you tell me which character you specifically mean in the layout file (https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/text/characters/arabic.json). Is the code incorrectly defined or does the keyboard only write this letter incorrectly when used in conjunction with another letter or even if it is standalone?

**Comment by rex07** [comment] 2021-05-01 14:04
The character  code": 1608, "label": "و" the problem is in the way that the contextual form of the code 1608 it happened when it is joined by another letter like

In the other keyboard is gone be like this
سؤال
In floris 
سﺅال

And its the only bug that is in this keyboard from the layout prospective.

**Comment by rex07** [comment] 2021-05-03 01:54
@patrickgold any updates on this bug

**Comment by patrickgold** [comment] 2021-05-04 17:50
Found the problem:

Normal keyboards use this form of the key in question: https://unicode-table.com/en/0624/

FlorisBoard for whatever reason uses this form instead, which is a specifically separated form of the key: https://unicode-table.com/en/FE85/

Above commit is a fix for this issue, v0.3.11-beta04 will release this fix!

**Closed** 2021-05-04 17:51 UTC
Labels: bug, needs investigation
