### ISSUE TITLE
Capitalization does not get disabled after typing a character in Termux

### ISSUE THREAD

**Issue by Ahmedazim7804** [florisboard/florisboard#1405] opened 2021-11-25 08:47 UTC
#### Short description
Capitalization does not get disabled automatically after typing a capital letter in Termux.

#### Steps to reproduce
1. Open Termux
2. Click on Shift key in Florisboard
3. Type any character
4. Shift does not get disabled like it does everywhere, instead it stays on and have to manually press shift 2 times to disable capitalization.

#### Environment information
- FlorisBoard Version: 0.3.14-beta05 (61)
- Install Source: F-Droid
- Device: Lenovo Tab 4 8504x
- Android: 10, Crdroid Rom

**Comment by nvllsvm** [comment] 2021-11-25 15:31
Duplicate of https://github.com/florisboard/florisboard/issues/1010

**Comment by patrickgold** [comment] 2021-11-28 10:18
Thanks for your bug report! This is a known issue and already filed in #1010, although currently I do not know the cause of this issue. Closing this issue as a duplicate.

**Closed by patrickgold** 2021-11-28 10:18 UTC
Labels: bug
