### ISSUE TITLE
Glide typing trail not shown when Popup Visibility is disabled

### ISSUE THREAD

**Issue by crisp5** [florisboard/florisboard#1704] opened 2022-03-26 11:06 UTC
#### Short description
Glide typing trail not shown when Popup Visibility is disabled

#### Steps to reproduce
1. Fresh install
2. From the Settings UI, go to 'Gestures & Glide Typing' and toggle 'Enable glide typing' on.
3. From the Settings UI, go to 'Keyboard' and toggle 'Popup Visibility' off.
4. Start glide typing. The glide trail is only shown for a brief moment at the end of the glide gesture.

#### Environment information
- FlorisBoard Version: 0.3.14 (also present in 0.3.15-beta01)
- Install Source: 0.3.14 from F-Droid, 0.3.15-beta01 from GitHub
- Device: Samsung Galaxy J7
- Android: 8.1.0

**Comment by tsiflimagas** [comment] 2022-03-26 11:13
That's a general bug of glide typing, it doesn't depend on popup visibility. It can be fixed temporarily by killing the app.

**Comment by crisp5** [comment] 2022-03-26 18:40
After trying to replicate this issue with the steps in the other issue I opened (https://github.com/florisboard/florisboard/issues/1703), I found that the invisible glide trail issue only shows up if 'Popup Visibility' is off. Pasting the steps for convenience:
1. Kill the app with Glide disabled AND Popup Visibility off
2. Open the app
3. Tap on the "Try out" box to reload the keyboard
4. Reenable glide

Following the steps with Popup Visibility on instead shows the trail. Like the other issue, killing the app fixes it.

**Comment by crisp5** [comment] 2022-04-02 17:58
Another way of triggering this is disabling Popup Visibility and disabling Smartbar. As far as I can see, these two settings together 100% hide the glide trail, even after restarting the app. Toggling Enable Smartbar also toggles the bug without having to reload the app, maybe that'll help with testing.

**Comment by patrickgold** [comment] 2022-04-05 19:47
So parts of the bugs discussed here (#1703) are fixed in #1756, currently I am investigating the popup visibility bug.

Interestingly disabling popups somewhere prevents the glide trail from showing, and toggling it on will immediately fix the glide trail again, toggling off and it won't show. No app kills needed, this applies instantly.

**Comment by patrickgold** [comment] 2022-04-05 20:16
Above PR now also fixes the popup visibility interferes with glide trail visibility bug. The cause was that the current glide status was not a state, but the popup forces a re-drawing anyways, so this state bug only appeared when popup visibility was off.

This means that the most annoying bugs around glide enabling and glide trail not showing should be fixed. Still an issue are the long words and of course English (US) only, the latter not fixable before 0.4.0 though. Will be included in 0.3.15-rc01 later today, thanks for reporting!

**Closed** 2022-04-05 20:21 UTC
Labels: bug, bug-confirmed, area: glide-typing
