### ISSUE TITLE
Previous Apps' Colors get Transferred to New Themes

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#274] opened 2021-01-29 11:29 UTC
This bug was created due to #226.

### 2. The (real) keyboard's background keeps its color
![Screenshot_20210126-160233_Firefox Klar.jpg](https://user-images.githubusercontent.com/59611881/106269973-8f2be100-622d-11eb-9b95-669d2b0775bd.jpg)
 
**Environment information**
- FlorisBoard Version: 0.3.5
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment] 2021-02-02 23:31
I haven't directly worked to resolve this issue yet, but have indirectly changed some lines of code in the v0.3.6 release which changed some theme value assignments as well as forcing the drawing cache invalidation of the `InputView`. When you get the new version update in Google Play, could you give me feedback if anything has changed in regards to this issue or if this bug is still persistent? Thanks in advance!

**Comment by Glitchy-Tozier** [comment] 2021-02-03 07:08
Will do.

**Comment by Glitchy-Tozier** [comment] 2021-02-03 07:58
Ta-Daaaaa:
![Screenshot_20210203-081717_Firefox Klar.jpg](https://user-images.githubusercontent.com/59611881/106715901-fc5cbf00-65fd-11eb-936f-3cc7e5fa9888.jpg)

**Comment by Glitchy-Tozier** [comment] 2021-02-03 09:29
Also, I _think_ I saw an incorrect loading screen flash up for a split second. Not 100% sure though.

**Comment by patrickgold** [comment] 2021-02-03 18:55
Above commit is a possible fix for the bug (at least for the input view, the landscape bug is still a thing I think). I've investigated the `setTint()` method and found out, that the input view background does not even use it. So I doubt that this is the error. What has changed here is that now all theme receivers get a force-update when the adaptive theme evaluates, maybe this helps with this bug.

**Comment by Glitchy-Tozier** [comment] 2021-02-03 19:05
I'll definitely give feedback when 0.3.7 arrives  :)

**Comment by Glitchy-Tozier** [comment] 2021-02-06 16:06
Yo.

1. The mixed-theme issue hasn't happened as of yet. I feel like it's gone.
2. The horizontal textbox-color also is fixed.
3. What still persists thought is that _sometimes_ the loading-preview-keyboard shows up in the previous app's theme.

What is intesesting about this is that it sometimes happens even though i never opened the keyboard in the first app before switching to the second one.

**Comment by patrickgold** [comment] 2021-02-07 01:33
Thanks for your feedback!

> The mixed-theme issue hasn't happened as of yet. I feel like it's gone.

That's great to hear! So it seems to force update the UI after fetching the theme updates seems to improve/solve the problem. So should we let this issue open then or see it as resolved and close it?

> The horizontal textbox-color also is fixed.

Great to hear. Again, I am force-updating the UI after computation so this even works (some vendors, especially Samsung though really like to draw their own theme over some keyboard components, which results in messed up situations like the landscreen input UI bug you reported.

> What still persists thought is that sometimes the loading-preview-keyboard shows up in the previous app's theme.

Hmm maybe I need to check if I am also force-updating the loading keyboard theme.

> What is intesesting about this is that it sometimes happens even though i never opened the keyboard in the first app before switching to the second one.

Maybe the FlorisBoard service was alive in the background, in which case it still gets notified about new inputs and thus has the ability to compute the target app colors. This especially happens when doing this:

[start in App Z] -> FlorisBoard -> Gboard -> [switch to App A] -> Gboard -> [switch  to App B] -> Gboard -> FlorisBoard

The FlorisBoard service was never actually dead and thus the previous app color is taken. The Android system may do this if it notices you switch around a lot between keyboards and then it caches these IME services to enable faster switching.

**Comment by Glitchy-Tozier** [comment] 2021-02-07 13:10
> So should we let this issue open then or see it as resolved and close it?

Your choice. To me it seems like it's 50% fixed. (The more important half of the bug is fixed)

That being said, I'm actually not 100% sure if it's the loading-keyboards that flashes up.

I managed to screen-record one instance of the bug and it seems like _it's actually the real previous keyboard_ pops up for a split second.

**Comment by patrickgold** [comment] 2021-02-07 14:03
This just seems to me that Android is slow in returning the colors for the new app, thus the old colors flash up before the new ones get applied. I am unsure how to fix that one yet, maybe I find a way to evaluate the colors sooner so the new colors are ready when the keyboard is first drawn in the new app.

**Comment by Glitchy-Tozier** [comment] 2021-02-07 16:01
Is there maybe some 'more direct' way of getting the data directly from the app instead of waiting for android to give it to you?

**Comment by patrickgold** [comment] 2021-02-07 18:09
The only thing I can do is to fetch the colors when `onStartInput()` is called, rather than doing so on `onStartInputView()`. Currently I am prepping dictionary suggestions which of course takes priority.

**Comment by Glitchy-Tozier** [comment] 2021-02-07 21:19
Of course, focus on the things everyone (including me) is looking forward to!  :)

**Comment by yashpalgoyal1304** [comment] 2021-02-13 14:48
it happens with me too. Is there any input that maybe needed from my side? Asking as the issue is labelled ~not_reproduced

**Comment by patrickgold** [comment] 2021-02-13 17:44
@yashpalgoyal1304 Difficult to say at the moment, because this issue is not reproducible on ANY testing device (both physical and emulted) and I don't even know anymore what it is caused by. The only thing I could maybe find useful is if I knew what Android version you are on and what device you use, maybe I can narrow it down to some vendor bug or problem with a specific Android ROM.

**Comment by Glitchy-Tozier** [comment] 2021-08-11 17:52
Just for the record: it happens rarely, but it still exists.

My current Version: **v0.3.13-beta08**.

**Comment by yashpalgoyal1304** [comment] 2021-08-11 19:34
heyyy! @Glitchy-Tozier OT: i just stumbled upon ur app GITHO - it seems nice in concept 👍

**Comment by Glitchy-Tozier** [comment] 2021-08-11 19:49
@yashpalgoyal1304 Hey, thanks dude! I hope it's useful to some people!  :)

**Comment by patrickgold** [comment] 2024-05-13 00:03
This feature is not supported by FlorisBoard anymore, thus I am closing this issue as not-planned.

**Closed** 2024-05-13 00:04 UTC
Labels: bug, not reproducible, area: kbd-theme
