### ISSUE TITLE
keyboard crash error showed after browsing twitter and kept working

### ISSUE THREAD

**Issue by keatit71** [florisboard/florisboard#2031] opened 2022-08-29 18:44 UTC
#### Environment information
- FlorisBoard [0.4.0-alpha03](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha03) (89)
- Device: Samsung SM-G975F (beyond2lteeea)
- Android: 12 (cn=S sdk=31)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-08-29T18:40:53.612Z
Manufacturer        : samsung
Model               : SM-G975F
Product             : beyond2lteeea
Android             : 12 (cn=S sdk=31) [SP1A.210812.016.G975FXXUFHVG4]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.98 GiB (68.70% used, 7.25 GiB max)
Font scale          : 1.0
Locales             : en-GB

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha03 (89)
Build type          : beta
Build commit hash   : 26650d2a00d509efbbd58bafa8606ba11bc5961f
Java heap memory    : 10.55 MiB (4.12% used, 256.00 MiB max)
Native heap memory  : 30.71 MiB (78.75% used, 38.99 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1661798432539.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.lib.StateAdaptersKt.observeAsNonNullState(StateAdapters.kt:10)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardManager.observeActiveState(Unknown Source:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1$1.invoke(FlorisImeService.kt:73)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1$1.invoke(FlorisImeTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1.invoke(FlorisImeTheme.kt:13)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:4)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:6)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:6)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:132)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt.FlorisImeTheme(FlorisImeTheme.kt:32)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1.invoke(FlorisImeService.kt:7)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt$ProvideKeyboardRowBaseHeight$2.invoke(FlorisImeSizing.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt.ProvideKeyboardRowBaseHeight(FlorisImeSizing.kt:116)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt$ProvideLocalizedResources$1.invoke(Resources.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt.ProvideLocalizedResources(Resources.kt:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUiWrapper(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ComposeInputView.Content(FlorisImeService.kt:4)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:23)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:8)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:88)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:23)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at kotlin.LazyKt__LazyJVMKt.invokeComposable(LazyJVM.kt:2)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:5)
	at kotlin.text.UStringsKt.observeDerivedStateRecalculations(UStrings.kt:8)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:22)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:10)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:7)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:15)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:2)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Unknown Source:12)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:5)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:13)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:11)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:17)
	at android.view.View.dispatchAttachedToWindow(View.java:21976)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4293)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6127)
	at android.view.ViewGroup.addView(ViewGroup.java:5903)
	at android.view.ViewGroup.addView(ViewGroup.java:5875)
	at android.inputmethodservice.InputMethodService.setInputView(InputMethodService.java:2540)
	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:2304)
	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2843)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2790)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:964)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:921)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:231)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>

**Comment by noesterle** [comment] 2022-08-29 21:08
I ran into this same crash as well.
I opened Boost For Reddit, clicked the header to start typing a subreddit name and received the error notification. I have yet to be able recreate it, I've tried re-entering the subreddit name, closing Boost and doing it again, locking the device with Boost closed and opening to enter a subreddit name.
I also had Incognito mode on at the time, as usual.

#### Environment information
- FlorisBoard [0.4.0-alpha03](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha03) (89)
- Device: Google Pixel 6 Pro (raven)
- Android: 12 (cn=S_V2 sdk=32)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-08-29T21:00:23.272Z
Manufacturer        : Google
Model               : Pixel 6 Pro
Product             : raven
Android             : 12 (cn=S_V2 sdk=32) [SQ3A.220705.003.A3]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 7.38 GiB (65.09% used, 11.33 GiB max)
Font scale          : 1.0
Locales             : en-US

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha03 (89)
Build type          : beta
Build commit hash   : 26650d2a00d509efbbd58bafa8606ba11bc5961f
Java heap memory    : 11.64 MiB (4.55% used, 256.00 MiB max)
Native heap memory  : 31.24 MiB (85.67% used, 36.46 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1661806779263.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.lib.StateAdaptersKt.observeAsNonNullState(StateAdapters.kt:10)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardManager.observeActiveState(Unknown Source:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1$1.invoke(FlorisImeService.kt:73)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1$1.invoke(FlorisImeTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1.invoke(FlorisImeTheme.kt:13)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:4)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:6)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:6)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:132)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt.FlorisImeTheme(FlorisImeTheme.kt:32)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1.invoke(FlorisImeService.kt:7)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt$ProvideKeyboardRowBaseHeight$2.invoke(FlorisImeSizing.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt.ProvideKeyboardRowBaseHeight(FlorisImeSizing.kt:116)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt$ProvideLocalizedResources$1.invoke(Resources.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt.ProvideLocalizedResources(Resources.kt:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUiWrapper(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ComposeInputView.Content(FlorisImeService.kt:4)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:23)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:8)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:88)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:23)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at kotlin.LazyKt__LazyJVMKt.invokeComposable(LazyJVM.kt:2)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:5)
	at kotlin.text.UStringsKt.observeDerivedStateRecalculations(UStrings.kt:8)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:22)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:10)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:7)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:15)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:2)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Unknown Source:12)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:5)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:13)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:11)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:17)
	at android.view.View.dispatchAttachedToWindow(View.java:20812)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5290)
	at android.view.ViewGroup.addView(ViewGroup.java:5076)
	at android.view.ViewGroup.addView(ViewGroup.java:5048)
	at android.inputmethodservice.InputMethodService.setInputView(InputMethodService.java:2031)
	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:1866)
	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2277)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2244)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:814)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:788)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:225)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>

**Comment by patrickgold** [comment] 2022-08-29 21:37
Thanks for your bug reports and possible ways to reproduce the crash.

This is a duplicate of #2025, as such I will close this issue and use #2025 for further discussion on this. I am already locally experimenting with some fixes, as I cannot reproduce the crash however it is difficult for me to say if it is fixed.

**Closed by patrickgold** 2022-08-29 21:37 UTC
Labels: bug
