### ISSUE TITLE
0.4.0-alpha01: Display suggestions displays placeholder suggestions and behaves unexpected

### ISSUE THREAD

**Issue by vixpr** [florisboard/florisboard#1976] opened 2022-07-27 15:11 UTC
#### Short description
(Please check the screen recording.)

#### Steps to reproduce
1. Enable display suggestions
2. Open keyboard
3. Type "auto" then press the space button.

#### Environment information
- FlorisBoard Version: 0.4.0-alpha01 (87) 
- Install Source: GitHub
- Device: Poco X3 Pro
- Android: Android 12 & MIUI13 

https://user-images.githubusercontent.com/71558811/181283292-d7943874-32a3-4407-9095-18a0f48f4d09.mp4

**Comment by patrickgold** [comment] 2022-07-27 15:13
Yes this is a placeholder, and if you type anything which begins with "auto" it activates the auto-insert of the suggestion framework. Without a suggestion backend this is just a demo for the features and not meant to be used yet.

**Comment by patrickgold** [comment] 2022-07-27 15:14
Technically not a bug but we can let it be one until the first alpha suggestions backend is here. You decide.

**Comment by patrickgold** [comment] 2022-07-27 15:31
Kk, will label this bug properly then

**Comment by jeroen7s** [comment] 2022-08-16 18:07
> and if you type anything which begins with "auto" it activates the auto-insert of the suggestion framework.

I hope this is only for the beta?
In dutch and german the word for "car" is "auto" so it's very anoying having to remove the 0 everytime i type it :D

**Comment by patrickgold** [comment] 2022-08-16 18:47
> I hope this is only for the alpha?

Yep only for alpha. And like I said just a placeholder, this will definitely not make it into stable 0.4 :)

**Comment by patrickgold** [comment] 2022-08-31 18:24
Above linked commit simply comments out the auto0 placeholder, as the reports of this annoyance are going up a lot. Will be released with 0.4.0-alpha04 soon.

**Closed by patrickgold** 2022-08-31 18:24 UTC
Labels: bug, bug-confirmed, area: word-prediction
