### ISSUE TITLE
Keyboard UI does not re-draw / refuses input

### ISSUE THREAD

**Issue by Raif1** [florisboard/florisboard#1714] opened 2022-03-27 14:05 UTC
**If you experience an issue where the UI will randomly refuse to accept input or ignore the shift key, symbols etc. this issue is the collector for it. There's currently an confirmed bug in the UI rendering which causes this state, unfortunately the cause has not been found yet. Temporary workaround: Hide and open the keyboard again, then it should work fine again.**

---

#### Short description
Sometimes I dunno why after the latest update it  seems like i cant click or tap scroll whatever anything when florisboard is up .
#### Steps to reproduce
1.An example .. Search florisboard on fdroid while using florisboard
2. Click on florisboard
3.Cant open florisboards download page on fdroid

#### Environment information
- FlorisBoard Version: 0.3.14
- Install Source: fdroid
- Device: phh
- Android: 11 lineage gsi

**Comment by Raif1** [comment] 2022-03-28 08:23
Now everything seems fine again . I guess its fixed?

**Comment by Raif1** [comment] 2022-03-30 13:44
Well it often happens and i cant click anything when the keyboards up

**Comment by patrickgold** [comment] 2022-03-30 14:02
Yeah that's exactly one point of the known issues in the changelogs. I am not sure why it happens but it happens (also on AOSP-like systems), I just haven't found a fix for it yet.

**Comment by Raif1** [comment] 2022-03-31 05:36
Its actually not after idling i think bcs its really hard to notice

**Comment by patrickgold** [comment] 2022-03-31 06:15
Maybe but I can only somewhat reproduce this issue if FlorisBoard was idling for a bit. I think that fixing the post-idling issue also fixes input refusal issues in your case.

**Comment by opusforlife2** [comment] 2022-06-13 21:21
FYI: Even Google Keyboard has this bug. The same workaround is needed. (The bug might have been fixed on GBoard.) Sometimes, the entire app needs to be switched away from for the keyboard to start working again. I don't know if the root cause for both apps is the same. If it is, it might be something in the OS itself.

**Comment by patrickgold** [comment] 2022-06-14 20:31
It may be some sort of window weirdness that is a bug from the system but can be worked around by the app if it knows what the weirdness is (wouldn't be the first time in Android). I am not that profound with the depths of the system behavior though, so I just don't really know where to really start searching for the bug.

**Comment by atikattar1104** [comment] 2022-09-08 07:36
I Think That's Definitely An Android's System Issue. Other Keyboards Like - Hacker's Keyboard, OpenBoard, etc. Also Behaves Like That.

**Comment by lm41** [comment] 2024-04-23 22:43
The issue has been open for two years now, if this is really an Android bug, is it possible that it has already been fixed? Or has this happened to someone else recently.

**Comment by patrickgold** [comment] 2024-06-01 10:30
Yeah I think so too. Will close this issue but let it stay pinned until we make the v0.4 release, and if we then do not get any additional comments on this we can see it as fixed.

**Closed by patrickgold** 2024-06-01 10:30 UTC
Labels: bug, area: kbd-ui, bug-confirmed
