### ISSUE TITLE
"Delete Words Precisely" gesture deletes many characters/words

### ISSUE THREAD

**Issue by WillyWonksters** [florisboard/florisboard#1733] opened 2022-03-31 22:20 UTC
#### Short description

This issue is intermittent, and is caused by an inconsistent and sometimes very high sensitivity in the swipe gesture. 

After typing many words into a text field (app independent), deleting 30 words sometimes only takes a gesture large enough to go from the delete key to the "n" key. Other times, I needed to go the "c" or "v" key. 

After the 31 word point, the selection jumps all the way to the top of my long note to delete everything.

Sometimes many words are selected by the smallest gesture that is recognized, meaning that precise selection is impossible.

**Edit:** The point at which the selection jumps up to the top of the text box depends on character count, at around 321 characters. Standard characters and emoji seem to all count the same, but a flag emoji counts for 4 characters towards that limit. This would be because of how flags are represented in Unicode, so that may be a hint. (Although I expected it would count as only [2 characters](https://www.youtube.com/watch?v=sTzp76JXsoY))

I've seen these inconsistencies in the FlorisBoard "try your setup" box, the "simple notes" app, and Signal.

Another oddity is that swiping *right* on the delete key also deletes words to the left, which means I have to be annoyingly precise in order to release at the exact point that doesn't delete anything.
 
#### Steps to reproduce
1. Go to "Gestures & Glide Typing" 
2. Scroll down to "Delete key swipe left" (under the "Other gestures" heading)
3. Select "Delete Words Precisely"
4. Enter many words into text box and swipe left on the delete key.
5. With many attempts you should see huge variability in how large of a gesture is needed to delete several words. 
6. If you do not encounter the bug, maybe try going to a different screen and coming back.

#### Environment information
- FlorisBoard Version: 0.3.14
- Install Source: F-Droid
- Device: Pixel 5
- Android: GrapheneOS (Android 12) SP2A.220305.012.2022033013

**Comment by tsiflimagas** [comment] 2022-03-31 22:37
Hi. Please, fill the issue form, else I'll have to close the issue, since no information is provided.

**Comment by WillyWonksters** [comment] 2022-03-31 22:38
I am doing that now. I accidentally submitted before I meant to.

**Comment by WillyWonksters** [comment] 2022-03-31 23:27
I have seen similar issues in the cursor movement and text selection gestures.

**Comment by tsiflimagas** [comment] 2022-04-01 00:28
Thanks for filling the form out. Please also fill out the FlorisBoard version. Also, maybe mention some of the apps in which this issue occurs.

**Comment by WillyWonksters** [comment] 2022-04-01 01:32
Ok, got it. See my edit above for additional details and observations.

**Comment by WillyWonksters** [comment] 2022-04-02 20:44
Should I update the title to indicate that this is a general issue with the gesture sensitivity consistency, or is it preferred that titles generally stay as they are?

**Comment by patrickgold** [comment] 2022-04-08 15:53
Thank you for your bug report!

Your bug report is really a collection of three separate bugs:

1. **The delete key allows selection of left words via swiping right**  
   This bug has been reported in #1765 and just now fixed by me, so in the soon to be released 0.3.15-rc02 release this will not be possible anymore.
2. **The delete key selects everything up to the start of the text box at a certain word**  
   Yes, this is indeed correct. It is because I only see a specific "window" around the current cursor position, and if you select out of that window I cannot determine the word boundaries anymore and just use 0 as the first word start point. I could ofc increase the window size but that comes with a performance decrease with the current logic, so I need to see if reworking the input logic in the next small release 0.3.16 helps with this.
3. **Gestures are sensitive**  
   Yeah I know, gestures are _really really difficult_. The annoying thing: for you they are too sensitive, for another user they might be way too less sensitive. I have not found a direct relation between the user's screen density moved pixels yet, so this issue occurs. You can try however playing around with the velocity and distance threshold settings to try to resolve this issue.

> Should I update the title to indicate that this is a general issue with the gesture sensitivity consistency, or is it preferred that titles generally stay as they are?

Please let it as is, it makes most sense this way.

**Comment by patrickgold** [comment] 2022-04-28 23:15
Above linked PR majorly reworks the input cache. With this, as you move the selection and make it larger, FlorisBoard auto-determines more text as your selection grows, thus avoiding the character limit and being able to determine words correctly. As I cannot reproduce this bug anymore I will close this issue once the PR is merged and it will be parts of the 0.3.16-beta01 release this weekend. It would still be great if you could test out the beta if it indeed works for you too. Thanks!

**Closed** 2022-05-02 21:18 UTC
Labels: bug, bug-confirmed, area: kbd-logic
