### ISSUE TITLE
Pop-up-stems are too thin in landscape mode.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#504] opened 2021-03-26 19:29 UTC
The pop-up visuals are way to thin for the big landscape-letters.
It looks a little weird. I suggest making them as wide as the keys are. (meaning it might be optimal not to hard-code popup-stem-width if that's what is currently done)

![Screenshot_20210326-203051_WhatsApp.jpg](https://user-images.githubusercontent.com/59611881/112683672-37e36f00-8e72-11eb-93fb-56cdf9d434a5.jpg)

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by Glitchy-Tozier** [comment] 2021-03-27 08:53
I guess this is more of a proposal than an actual bug.

**Comment by patrickgold** [comment] 2021-03-27 12:18
As already mentioned in #505 the width is intended, but I am thinking of expanding it not for the looks of it (personally I like the thin width as it is) but to prevent some bugs and unexpected behaviors.

**Comment by Glitchy-Tozier** [comment] 2021-03-27 12:34
I absolutely understand if there's some hesitance. Making everything wide might be weird as well.

What do you think about making only the popup-options directly over the key wider?

![20210327_133439.jpg](https://user-images.githubusercontent.com/59611881/112720874-3319cc00-8f01-11eb-8a7c-a83e6e6f334e.jpg)

**Comment by patrickgold** [comment] 2021-03-27 12:49
That could be an option but is very difficult to add to the existing popup calculation. Increasing the width of every popup in landscape is easier to implement and quite a few keyboards do this (AnySoftKeyboard, Microsoft SwiftKey, etc.).

**Comment by patrickgold** [comment] 2021-03-28 17:45
Above PR fixes the width of the popups and makes them the same width as the key view in landscape. Will be released later this day with v0.3.10-beta04.

**Closed** 2021-03-28 17:47 UTC
Labels: proposal, proposal-accepted

**Comment by Glitchy-Tozier** [comment] 2021-03-28 17:48
Good job, I'll test it once it arrives on the PlayStore.  :)
(I try to stay away from installing non-Play-Store/Fdroid apps)

**Comment by patrickgold** [comment] 2021-03-28 17:50
No problem :) As a preview you can view the images I've attached to the PR, so you see how it looks.

**Comment by Glitchy-Tozier** [comment] 2021-03-28 18:09
Already saw it, they look great. (Still pondering over the version I suggested though xD )

By the way, how did you correct the popup-ordering-bug? (The one I didn't post)
Did you hardcode it or was it an accidental fix by making pop-ups wider? Or did you do something completely different?

**Comment by patrickgold** [comment] 2021-03-28 23:38
> By the way, how did you correct the popup-ordering-bug? (The one I didn't post)

Widening the popup width to the same as the keyview results in the same relative positions of each popup, regardless if it is landscape of portrait. Thus the ordering algorithm also produces the same result for both orientations. No hard-coding required :)

>  Question: Is f the key width?

`f` means `float` so the Kotlin compiler doesn't accidentally interpret it as a `double` (better version of `float` but Android works with floats only). `keyboardView.desiredKeyWidth` is the baseline for position calculation and you can see this as the key width.

**Comment by Glitchy-Tozier** [comment] 2021-03-29 06:05
I see, thank you for the explanation!  :)
