### ISSUE TITLE
SmartBar only visible in alphabetic kb

### ISSUE THREAD

**Issue by angriness-sleek** [florisboard/florisboard#74] opened 2020-12-08 07:04 UTC
![Screenshot-2020-12-08-12-31-56](https://user-images.githubusercontent.com/62484249/101451078-78e76000-3923-11eb-8953-17c5586e1cab.jpeg)
not visible in num and special kb:
![Screenshot-2020-12-08-12-32-16](https://user-images.githubusercontent.com/62484249/101451168-99afb580-3923-11eb-963c-dd1049e55e3c.jpeg)

**Comment by patrickgold** [comment] 2020-12-08 20:35
This is actually the intended behavior in v0.3.0. With the upcoming Smartbar rework I will rethink the concepts what and when things are displayed, I'll definitely improve this as well.

**Comment by patrickgold** [comment] 2020-12-21 18:09
I've just merged the Smartbar rework branch into master, which also fixes the logic behind the disappearing Smartbar. Now, the Smartbar will display the same content when switching from a character layout to the symbols and vice versa. Will release with the next release v0.3.1. Thanks again for your mentioning this issue!

**Closed** 2020-12-21 18:10 UTC
Labels: bug, bug-confirmed
