### ISSUE TITLE
It returns always to the default keyboard 

### ISSUE THREAD

**Issue by heberjeur** [florisboard/florisboard#220] opened 2021-01-22 00:48 UTC
**Environment information**
- FlorisBoard Version: 0.3.4
- Install Source: GitHub
- Device: Samsung a50
- Android version, ROM: Android 10

**Steps to reproduce**
1. Go to theme mode
2. Change it, for example follow system  or any other value
3. Quite
4. It returns to the default keyboard

It doesn't when you change the theme mode and directly you go to  the home screen of FlorisBoard 

Also it happened when I choose a custom keyboard color

**Comment by patrickgold** [comment] 2021-01-22 09:09
This indicates that reapplying the new theme mode upon existing results in a fatal Exception, in which case the Android system sometimes switches back to the default keyboard. I will definitely have to investigate this further, as this should absolutely be avoided.

**Comment by heberjeur** [comment] 2021-01-22 22:40
You can see the bug in this screen recording 
https://youtu.be/gJhzRI3AXOY

**Comment by heberjeur** [comment] 2021-01-26 19:29
Same problem for 0.3.5, I can't use The app 😕,  it's still returning to the default keyboard

**Comment by patrickgold** [comment] 2021-01-26 22:27
@heberjeur Sorry I completely oversaw your issue when fixing the adaptive themeing. Based on your video I think you have a crash which happens upon closing the Settings activity. This will also crash the Service IME class with it. On most devices, the Service is re-instantiated upon clicking on an input field. It seems that your device immediately returns to the default keyboard for whatever reason. I will try to fix this, as I can reproduce this bug on one of my emulated devices.

**Comment by heberjeur** [comment] 2021-01-27 08:18
OK thanks 🙂

**Comment by heberjeur** [comment] 2021-01-29 08:19
I have no problem with 0.3.2, the discard of settings start from 0.3.3 !

**Comment by patrickgold** [comment] 2021-01-29 09:19
@heberjeur I've been able to reproduce the crash but was unable to fix it yet, as the crash is indirectly produced, not directly. I will inform you of any progress on this issue.

**Comment by Stenafo** [comment] 2021-01-30 08:47
I have a similar problem, while typing (without me changing the settings) the keyboard closes and the system keyboard appears.  if I then reopen the floriskeyboard application I have the message that I have to change the default keyboard.
i am using the dark theme.

I have: samsung galaxy s6, android 7.0

**Comment by patrickgold** [comment] 2021-01-30 11:33
@Stenafo This seems like a crash to me, but not related to this one here. The output is the same, though closing the Settings crashes an input channel and I don't know why and how to fix it. Your described behavior more seems like that FlorisBoard encounters a crash and then switches back to the default keyboard while in the keyboard context. As you said you are seeing a message that you have to switch back to the default keyboard - If this is from FlorisBoard and not the system, you can click on it and copy the stacktrace, which would definitely help me fixing this. Could you open a new issue for this? Thanks in advance!

**Comment by Stenafo** [comment] 2021-01-31 09:35
@patrickgold I suppose it's a floris problem because I've never had this problem with any other keyboard.
where can i find the stacktrace?

**Comment by patrickgold** [comment] 2021-01-31 12:35
@Stenafo Wen you get the notification which tells you that FlorisBoard is reverting to the default keyboard, you can click it and copy the stacktrace displayed into an issue at GitHub.

**Comment by Stenafo** [comment] 2021-01-31 13:33
@patrickgold unfortunately I don't have any kind of notification, surely the keyboard crashes and the system resets the default keyboard without reporting anything.

**Comment by patrickgold** [comment] 2021-01-31 13:57
@Stenafo I have an idea: maybe you are accidentally triggering the space bar swipe up gesture, which brings you to the last used keyboard (mostly this is the default keyboard). Try disabling it in Settings > Gestures > Space bar swipe up (Set it to `No action`). If it then does not occur anymore we know the source of this behavior.

**Comment by Stenafo** [comment] 2021-02-01 23:34
@patrickgold hahahahahah omg sorry
yes, that was the problem, maybe it's better to remove that default setting

**Comment by heberjeur** [comment] 2021-02-05 06:59
The problem has been resolved in the lastest version  😀

**Comment by patrickgold** [comment] 2021-02-05 14:50
@heberjeur Thanks for letting me know! Great to hear that it has to been resolved in the latest version for you. I am not sure though why it has been resolved, as I didn't even do some specific fix for this... I will let this issue open to further investigate into this.

**Comment by lm41** [comment] 2024-09-17 00:10
I think after 3.5 Years we can close this issue as stale.

**Closed** 2024-09-18 01:03 UTC
Labels: bug, bug-confirmed, needs investigation, area: kbd-logic
