### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Panak252** [florisboard/florisboard#2438] opened 2024-04-04 15:33 UTC
### Short description

Tapped on something and the keyboard crashed. 

### Steps to reproduce

Mess about with the settings

#### Environment information
- FlorisBoard [0.4.0-beta01](https://github.com/florisboard/florisboard/releases/v0.4.0-beta01) (93)
- Device: Samsung SM-S908B (b0sxeea)
- Android: 13 (cn=TIRAMISU sdk=33)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-04-04T15:30:49.590371Z
Manufacturer        : samsung
Model               : SM-S908B
Product             : b0sxeea
Android             : 13 (cn=TIRAMISU sdk=33) [TP1A.220624.014.S908BXXS6CWI1]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.96 GiB (48.29% used, 10.27 GiB max)
Font scale          : 0.9
Locales             : en-US

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-beta01 (93)
Build type          : beta
Build commit hash   : 0dd1f90c83409865e2def316d7cb4089b2f1c8be
Java heap memory    : 7.97 MiB (3.11% used, 256.00 MiB max)
Native heap memory  : 29.43 MiB (89.96% used, 32.72 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1712244646700.stacktrace</summary>

```
java.lang.ClassCastException: dev.patrickgold.florisboard.lib.ext.ExtensionComponentName cannot be cast to java.lang.String
	at androidx.compose.foundation.lazy.grid.LazyGridMeasureKt$measureLazyGrid$5.invoke(SourceFile:39)
	at androidx.compose.foundation.lazy.grid.LazyGridMeasureKt$measureLazyGrid$5.invoke(SourceFile:3)
	at dev.patrickgold.florisboard.app.settings.theme.EditRuleDialogKt$EditCodeValueDialog$3$1.invoke(SourceFile:21)
	at androidx.collection.ScatterSet$toString$1.invoke(SourceFile:95)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(SourceFile:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlin.ResultKt.resume(SourceFile:1)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:100)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SourceFile:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:30)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Unknown Source:4)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Unknown Source:4)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:157)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:136)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(SourceFile:30)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(SourceFile:122)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(SourceFile:79)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(SourceFile:214)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:76)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
	at android.view.View.dispatchPointerEvent(View.java:15803)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8153)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7877)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7213)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7434)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7491)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10788)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10676)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10632)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10926)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:285)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@c06b4e5, androidx.compose.runtime.BroadcastFrameClock@816fbba, StandaloneCoroutine{Cancelling}@e580a6b, AndroidUiDispatcher@86b39c8]

```
</details>

**Comment by lm41** [comment] 2024-05-31 09:29
Closing as duplicate of #2482

**Closed by lm41** 2024-05-31 09:29 UTC
Labels: bug
