### ISSUE TITLE
Add Vietnamese Keyboard

### ISSUE THREAD

**Issue by zT2Dz** [florisboard/florisboard#931] opened 2021-05-23 16:11 UTC
Your keyboard looks perfect for me, and I really want to use it in my everyday text conversations, but it doesn't support Vietnamese for now. Could you please add Vietnamese in the next update?. The Vietnames keyboard has the QWERTY design and Telex/VNI input encoding method. Thanks for reading.
Some helpful links: 
An opensource Android Keyboard: https://github.com/AgeOfMobile/Vietnamese-LatinIME
Unikey source: https://www.unikey.org/source.html

**Comment by patrickgold** [comment] 2022-05-12 16:01
thanhhocse96 did rework Telex by a lot and enhanced Telex. Could you please have a look at the latest beta release 0.3.16-beta02 and check it out?

**Comment by patrickgold** [comment] 2022-05-12 16:04
Also this issue is technically a duplicate of #183, so to avoid too many duplicate threads I will close this issue. If you have feedback on Telex please share it in #1841!

**Closed by patrickgold** 2022-05-12 16:04 UTC
Labels: proposal
