### ISSUE TITLE
Re. add recently used emoji like Gboard

### ISSUE THREAD

**Issue by csgonks** [florisboard/florisboard#907] opened 2021-05-18 12:38 UTC
I am using v0.3.12 florisboard, and it is best foss keyboard I used.
I am requesting to Dev. Can you add add recently used emoji like Gboard. It will be very useful.
![WhatsApp Image 2021-05-18 at 18 06 16](https://user-images.githubusercontent.com/84389179/118652263-0d73b980-b804-11eb-8b16-09d6bc6f36d9.jpeg)

Thank.

**Comment by debnone** [comment] 2021-05-18 18:23
it's a very good idea. 😍
 the recently used emoji it's very helpful and practical. most people use a few emojis. it can be implemented on the bottom line.
 and it need to be editable, so you can choose what layout you want, in the future it will be open  for more expressions layouts.

file:///home/tamerdab/Pictures/photo_2021-05-18_21-20-44.jpg

**Comment by Glitchy-Tozier** [comment] 2021-05-26 15:47
Hi, I just realized this is a duplicate of #268, thus closing this issue.

Should you have any further thoughts regarding this topic, please share them there.  :)

**Closed by Glitchy-Tozier** 2021-05-26 15:47 UTC
Labels: proposal
