### ISSUE TITLE
Latest version conflicts with previous version

### ISSUE THREAD

**Issue by hrshtein** [florisboard/florisboard#2571] opened 2024-09-19 07:58 UTC
### Short description

I was using florisboard v0.3.16 but when i tried to update to the latest version, the update failed! Is the app signature changed?
![Screenshot_2024-09-19-13-25-14-64_3d73e98b1ad3bd2575f7a56513d89a0c_1](https://github.com/user-attachments/assets/0d7b1ef6-2dce-460b-a338-04f8ddb03c9f)

### Steps to reproduce

1. Download v.0.3.16
2. Try to update to the latest version v.0.4.0
3. See error

### FlorisBoard Version

0.3.16

### Install Source

GitHub

### Device

Realme 9pro 5g

### Android

14

**Comment by BHydden** [comment] 2024-09-19 08:49
Same experience on my Pixel 6

**Comment by lm41** [comment] 2024-09-19 09:20
This works for me without any problems. Was the 0.3.16 possibly installed by fdroid? 
F-Droid uses different signkeys than the github releases.

**Comment by lm41** [comment] 2024-09-19 09:55
The package id of the preview track (alpha/beta/rc) is `dev.patrickgold.florisboard.beta`.
The package id of the release version is `dev.patrickgold.florisboard`.

I don't know how obtainium handles the versions of the two tracks internally, as they can be installed side by side

**Comment by hrshtein** [comment] 2024-09-19 10:10
> This works for me without any problems. Was the 0.3.16 possibly installed by fdroid? F-Droid uses different signkeys than the github releases.

Yeah! It can be the case, i installed v.0.3.16 when obtainium was not there. And this stable update is after a very long time.

**Comment by mfathurr** [comment] 2024-09-19 10:21
> The package id of the preview track (alpha/beta/rc) is `dev.patrickgold.florisboard.beta`.
> The package id of the release version is `dev.patrickgold.florisboard`.
> 
> I don't know how obtainium handles the versions of the two tracks internally, as they can be installed side by side

Is the only solution to reinstall the app directly to version 0.4.0?

**Comment by BHydden** [comment] 2024-09-19 10:27
> > The package id of the preview track (alpha/beta/rc) is `dev.patrickgold.florisboard.beta`.
> > The package id of the release version is `dev.patrickgold.florisboard`.
> > I don't know how obtainium handles the versions of the two tracks internally, as they can be installed side by side
> 
> Is the only solution to reinstall the app directly to version 0.4.0?

0.4.0 should be identical to 0.4.0rc2 IIUIC so just ignore it and wait for 0.4.1 i guess?

**Comment by BHydden** [comment] 2024-09-19 10:28
> Same experience on my Pixel 6

Uninstalling and reinstalling 0.3.16 allowed me to update to 0.4.0, unsure why 🤷‍♂️

**Comment by lm41** [comment] 2024-09-19 10:30
> Is the only solution to reinstall the app directly to version 0.4.0?

You can add florisboard a second time to obtainium and then select “Include prereleases”. From this source the stable versions should be installable without problems

**Comment by patrickgold** [comment] 2024-09-19 10:45
Hmm I think we need to also build stable releases for the preview track just for tools like obtainium to not be confused

**Comment by SaltyRhino95857-2** [comment] 2024-09-19 10:54
> F-Droid uses different signkeys than the github releases.
I can't update on Xiaomi Poco F4, and I installed it through F-Droid, so I'm gonna wait for the F-Droid release

**Comment by patrickgold** [comment] 2024-09-19 14:40
I am currently preparing a strategy which allows the preview track to receive stable releases when useful (e.g. no alpha/beta counterpart is available). I need to ensure that it is compatible with F-Droid (exclusion), IzzyOnDroid and Obtainium though and will apply it with v0.4.1+ (maybe backport to v0.4.0).

Note that this solves the namespacing issues when updating via Obtainum, however not the signature issue for the stable track (which is caused by mixing stable F-Droid and stable official builds), this is not really an issue and more like just the way it is.

**Comment by patrickgold** [comment] 2024-10-11 10:55
This issue has been resolved by #2623 and with the release of 0.4.1. Please make sure to read the release notes for how to update the Obtainium configs. CLosing as resolved.

**Closed by patrickgold** 2024-10-11 10:55 UTC
Labels: bug, area: other
