### ISSUE TITLE
Key light feed back

### ISSUE THREAD

**Issue by Triplesweet** [florisboard/florisboard#280] opened 2021-01-29 19:51 UTC
The feed back is 
1. Sometimes its not there 
2. It stuck in one key if you are fast
And for some reason i feel its getting worse too
Just wanted make sure its something that every one have before making a bug report

https://user-images.githubusercontent.com/77248142/106320642-671d9b80-6288-11eb-8866-b9f87e9ff115.mp4

**Comment by RickyM7** [comment] 2021-01-29 22:30
Probably a duplicate of #105, but in fact this bug exists (I can confirm that this occurs on my Redmi Note 4 [MIUI 11 - Android 7.0]) and in my opinion this is the worst bug in the app (this bug that prevents me from making FlorisBoard my main keyboard).

**Comment by Glitchy-Tozier** [comment] 2021-01-30 06:53
I don't quite understand #105, but I can telly you that what I see in the video doesn't happen on my Samsung Galaxy S9.

I understand that you'd want it to be fixed though.

**Comment by patrickgold** [comment] 2021-01-30 11:07
Thanks for your report! This one is more visible when popups are disabled, though still popups aren't the fastest on older devices. I will investigate into this.

**Comment by Tmpod** [comment] 2021-01-31 17:32
I can confirm I also get this "sticky" behaviour on my Redmi 4X with Lineage 16. The input itself is processed fast, it's just that the pressed animation (and popups if enabled) tend to get stuck if you type fast.

**Comment by patrickgold** [comment] 2021-02-28 18:09
Version 0.3.8 which will release later this evening contains a lot of bug fixes in the core editor instance and which also improves the responsiveness of the UI. When the new version arrives, could you give me feedback if the described bug is now fixed? This would be very helpful, thanks in advance!

**Comment by Triplesweet** [comment] 2021-02-28 18:14
Sure and thanks for caring as well

**Comment by Triplesweet** [comment] 2021-03-01 18:53
Hey sorry to answer so late I had some classes. But I can say it became a lot better and much harder to get. It is still there but you have to look for it.

**Comment by patrickgold** [comment] 2021-03-02 10:41
> Hey sorry to answer so late I had some classes. But I can say it became a lot better and much harder to get. It is still there but you have to look for it.

Hmm great to hear that it has improved! I will let this issue up to see if I can further improve somewhere in the KeyView UI responsiveness.

**Closed** 2021-03-10 15:08 UTC
Labels: bug, bug-confirmed
