### ISSUE TITLE
App getting reset every time phone is restarted

### ISSUE THREAD

**Issue by justaguydoinghisstuff** [florisboard/florisboard#1304] opened 2021-10-04 18:43 UTC
#### Short description
The app keeps resetting my preferences (customizations) every time the phone restarts.

#### Steps to reproduce
1. Set up the app with the new settings
2. Check if keyboard is to your liking 
3. Restart phone
4. Keyboard is now with default settings and need to be configured again

#### Environment information
- FlorisBoard Version: 
- Install Source:  F-Droid 
- Device: Oneplus 6T 
- Android: OxygenOS 10.3.12

**Comment by patrickgold** [comment] 2021-10-04 22:14
Thanks for your bug report! This could be an issue with the direct boot support. If you customize FlorisBoard, then switch to another keyboard, reboot and after rebooting switch to FlorisBoard again are all the customizations kept?

**Comment by patrickgold** [comment] 2021-10-07 23:12
I still think this is directly related to the direct boot thing. When you boot your phone and display the keyboard before a user has logged in for the first time, the files dir points to a generic app data dir, where of course no user-related preferences are stored. As soon as you unlock your phone by entering the password, the context now points to the encrypted user data app dir, where the pref file with your customizations is located. The preference model however does not recognize this change and thus happily overwrites your customizations upon syncing to disk.

I will add this to my list of issues for the keyboard logic, but will also add this to the preference rework project because it is a pretty serious issue.

**Comment by BobIsMyManager** [comment] 2021-10-08 18:25
Similar @jorgeluiscarrillo , if i switch to a different keyboard before i shut down my phone and boot it up then switch back i still have my settings applied.

**Comment by patrickgold** [comment] 2021-10-31 23:46
Ok so I've put quite some effort into debugging, fixing and testing the fix I provide and on my testing rig and no preference values are lost anymore in #1370.

If anyone is interested in giving feedback if it actually works on your device, you can download the debug artifact from #1370 here: https://github.com/florisboard/florisboard/pull/1370/checks (will install separately as "FlorisBoard Debug"). This feedback would be incredibly helpful to see if my fix also works for devices other than my own ones, because direct boot mode may not work the same on all Android ROMs/devices.

The expected outcome should be the following:
1. Before rebooting make sure the active keyboard is FlorisBoard Debug
2. Reboot
3. Enter your SIM pin
4. In the initial password field the default config/subtypes/themes are used, because the user storage (where the preferences are stored) is still encrypted. 
5. After unlocking either when you tap on any text field or when opening the Floris Preferences, you should see that all preferences/themes/... are kept as you set them before you rebooted.

**Comment by justaguydoinghisstuff** [comment] 2021-11-01 10:07
Hi,
Im running the same device and OS version of when i opened this issue.  I cant say about different devices but 
I can confirm that this worked for me, tried rebooting a couple of times and it kept my settings.

**Comment by TecWyn-ca** [comment] 2021-11-03 05:46
So i'm seeing in use reset of settings, some not all.
Specifically glide and pop up symbols.
This is happening in use same session, no power off
0.3.14-beta05 (61) on GoS

Kudos for the great job! Btw

**Comment by patrickgold** [comment] 2021-11-03 20:25
@TecWyn-ca beta05 does not have the fix in that the current debug builds have and it is confirmed that beta05's pref loading logic is bugged (which beta06 with #1370 once released) will fix.

When beta06 arrives for you, could you give feedback if this bug is fixed for you?

**Comment by BobIsMyManager** [comment] 2021-11-03 21:40
The bug seems to be fixed with that debug version

**Comment by patrickgold** [comment] 2021-11-03 22:14
Thanks for confirming!

**Closed** 2021-11-27 19:56 UTC
Labels: bug, needs investigation, area: kbd-logic

**Comment by nvllsvm** [comment] 2022-03-16 17:23
I'm experiencing this with 0.3.14-rc01. Force stopping the app resolves the issue.
