### ISSUE TITLE
Flashing Keyboard

### ISSUE THREAD

**Issue by MathSteve22** [florisboard/florisboard#589] opened 2021-04-08 12:47 UTC
#### Short description
When using custom themes, I have noticed the keyboard will be flashing in and out. By flashing here, I am referring to that it fades in and out between the keyboard's normal theme and near completely transparent. This has happened with multiple custom themes I have used. It does occur every time, but it does happen often. If this is a duplicate, I did not notice.

#### Steps to reproduce
1.) Create and set custom theme
2.) Bring up keyboard

#### Environment information
- FlorisBoard Version: 0.3.10-BETA06 
- Install Source: F-Droid
- Device: Samsung Galaxy S20 FE
- Android version, ROM: Android 11

**Comment by Glitchy-Tozier** [comment] 2021-04-08 13:24
1. Does it happen everytime? Your description may be missing a "not".
2. Can you trigger it with 100% consistency by just rotating your phone from vertical mode to horizontal mode to vertical mode (and so on)?

**Comment by MathSteve22** [comment] 2021-04-08 13:26
It was happening I would say 80% of the time, particularly when it was switching between my light and dark mode themes. I did not think of trying horizontal mode, but that did work. It is no longer doing it.

**Comment by Glitchy-Tozier** [comment] 2021-04-08 14:10
Wait, let's leave the issue open! If it happened once, it might happen again.
@patrickgold ?

**Comment by Glitchy-Tozier** [comment] 2021-04-08 14:13
Ty  :)

**Comment by Surendrajat** [comment] 2021-04-08 14:48
I've also noticed this issue with `Floris Night Borderless` theme at least 2 times using Tusky app. The background fades in and out in like 2 sec interval until I hide and open keyboard again.
However, I was using Debug build from `gesture typing` branch at that time.

**Comment by Glitchy-Tozier** [comment] 2021-04-08 14:59
Were you guys able to type on the keyboard **while** it was flashing?

**Comment by Surendrajat** [comment] 2021-04-08 15:05
Yes. It worked.

**Comment by patrickgold** [comment] 2021-04-08 17:48
Could be in theory caused by the fade in-out animation, which is supposed to only show if the layouts are initially loaded (upon service start/hard restart). What confuses me a bit though is that you were able to type while it was flashing, will have to investigate into this.

**Comment by arghfrank** [comment] 2021-04-08 19:58
had the same effect, when i had set theme mode (initially) to "always day". switching to "follow system" and BACK to "always day" fixed it apparently, no more flashing for me now ..

**Comment by xtyrrell** [comment] 2021-04-09 07:18
Here's a screen recording of the issue if it helps triaging

https://ufile.io/efuj2bom

v0.3.10-beta06
Android 10

**Comment by xtyrrell** [comment] 2021-04-09 07:23
Here's a screen recording of the issue if it helps triaging


![Brave](https://user-images.githubusercontent.com/6854494/114144069-35beed00-9915-11eb-95f3-8bffc0cd1fe0.gif)


v0.3.10-beta06
Android 10

**Comment by Glitchy-Tozier** [comment] 2021-04-09 08:50
The blinking looks kind of sick actually. Might request that as a feature one day 🤔

**Comment by Glitchy-Tozier** [comment] 2021-04-09 15:56
Happened to me as well, with Swiping and suggestions enabled.
It started flashing immediately after aetting the Themes to adapt to app-colors.

**Comment by pietrini** [comment] 2021-04-09 19:05
I'm in follow system theme, no suggestion, no swipping, no adaptation to app and I have this issue 100% of the time
Didn't had the issue when I was in `light` mode earlier but not that my phone moved to night mode I got it

**Comment by gammerboy** [comment] 2021-04-11 06:49
OS version: LineageOS 18.1 (android 11) - Not sure if this happens only on a few OSs based on how it handles it's own system theming.
Steps to reproduce issue:
1. Set theme mode to "Follow system".
2. Switch on or off dark mode / night mode depending on if it already on or off. (ie. switch the theme state).
3. click on the text input field in any app to open the keyboard overlay.
4. You will find the keyboard "flashing" or "fading in and fading out".
Note: Happens almost everytime the system theme state is switched (which causes the theme state in the keyboard to switch nd the issue comes up).
Ways to temp fix the flashing: (will start flashing once the theme state switches again)
1. force close keyboard from settings or using any other shortcut you might have and then reopen florisboard and might have to switch keyboards from the notification or settings. Force closing generally switches the keyboard to what is available.
2. Change theme mode to "always day" or "always night" (Haven't tested "follow time" yet)(The easy method)
Note: Changing the "Selected theme" under day theme heading or night theme heading does not seem to fix the flashing even thought. The theme changes by making a change here but the flashing also persists. So only changing theme in "Theme mode" stops the flashing.

**Comment by main-character** [comment] 2021-04-14 06:38
Could be reproduced to Realme 6 RMUI 1  android 10. In fact, as im typing right now, it is blinking lol.

How i reproduce the error:

1. Changing from light mode to dark mode.
2. Open keyboard
3. See the keyboard blinking.

**Comment by patrickgold** [comment] 2021-04-14 15:55
Above commit is attempt 1 at fixing the flashing bug. If possible, could some of you who want to install the [debug version](https://github.com/florisboard/florisboard/pull/669/checks?check_run_id=2344740692) and try out if this bug is resolved? I am not able to reproduce the bug on any testing devices and thus am not 100% sure how to fix it thus.

**Comment by xtyrrell** [comment] 2021-04-14 17:41
Oh no! It doesn't seem to be fixed. I just installed the debug build and followed the below steps to reproduce and the flashing still happened for me.

I think the previous reproduction instructions may be a bit unclear — you need to change the SYSTEM theme, not the keyboard theme, to trigger the bug (in my experience).

Here are my steps to reproduce (tested just now):

0. Set your phone's system theme to light (if your phone has a light / dark theme choice).
1. Install, enable, and switch to the keyboard.
2. Open the keyboard app, go to the Theme tab, and make sure Theme Mode is set to Follow System, with adapt colours to app set to off for both Day and Night theme. (Screenshot of settings that produce the bug: 
![Screenshot_2021-04-14-19-35-19-815_dev patrickgold florisboard debug](https://user-images.githubusercontent.com/6854494/114754362-c6a02900-9d58-11eb-9f23-2d5ef0e14a3b.jpg) )
3. Focus a text field so the keyboard pops up
4. Go to your phone's settings, and change your phone's system theme from light to dark.
5. Focus on a text field so the keyboard pops up. The keyboard will have switched to the dark theme, but will now be flashing / pulsating.

If it's useful, I can make a screen recording of me going through these steps.

**Comment by geludwig** [comment] 2021-04-14 18:32
I have the same error since the last update to 0.3.10 (via F-Droid). No errors in v0.3.9.

I use custom themes (changed Enter key color) and automatic switching between night and day theme.
As far as I can tell, the flashing keyboard only occurs, after the system theme is changed (day to night and vice versa).

System:
OnePlusNord
Android 11 (OxygenOS 11.1.2.AC01BA)
FlorisBoard v0.3.10

**Comment by patrickgold** [comment] 2021-04-15 03:21
Thanks for testing the changes out and describing the detailed steps to reproduce! Sadly, no method described works for me to reproduce the bug still, I've tried settings the system theme, changing the theme by enabling battery saver and also by changing the theme via follow time.

I've pushed attempt number 2 to fix this bug, could you please check again if this change is any progress? Thanks in advance! ([Debug APK](https://github.com/florisboard/florisboard/pull/669/checks))

**Comment by geludwig** [comment] 2021-04-15 05:46
It works!
Last attempt seemed to have fixed the issue (for me at least). I cant reproduce the flashing issue anymore.

**Comment by patrickgold** [comment] 2021-04-15 15:28
Thanks for the feedback! Will wait if someone else can also confirm that it is fixed and then merge the change into master.

**Comment by Glitchy-Tozier** [comment] 2021-04-15 15:58
If you do, I'd be interested in what you changed! :)

**Comment by nkm8** [comment] 2021-04-15 16:02
Confirmed as fixed for me - Pixel 3 on Android 11

**Comment by Donnnno** [comment] 2021-04-15 16:03
The fix worked for me too! :) (poco f3, android 11)

**Comment by geludwig** [comment] 2021-04-15 16:18
> If you do, I'd be interested in what you changed! :)

Im not really a programmer in any way. But it seems like Patrick added three seperate animation pointers with definite duration and ending arguments instead of a general one.

Maybe he will tell us  : )

**Comment by main-character** [comment] 2021-04-15 17:28
it worked. no more flashing in realme 6 android 10

**Comment by patrickgold** [comment] 2021-04-15 17:39
Thanks everyone for the feedback, seems like the change really helped. Will merge it into master and release it in the next beta v0.3.11-beta02.

> If you do, I'd be interested in what you changed! :)

The loading animation has three phases:

- **0.9->1.0** (was `ObjectAnimator 1`)
- **1.0->0.4->1.0 loop (modified `ObjectAnimator 1` after 125msecs)
- **x->1.0** (was `ObjectAnimator 2`)

The problem for the logic was, that the layout loading upon a system theme change for some devices was actually faster than 125msecs (Sad OnePlus 7T noises), thus this happened: Phase 1 -> Phase 3 -> Phase 2. Important to note is that Phase 2 got only cancelled by Phase 3. If Phase 2 now starts after Phase 3, well you have a flashing keyboard xd.

The new logic initializes Phase 1 & 2 at once (Phase 2 gets a `startDelay` of 125msecs), cancelles both Phases 100% after the loading and then starts Phase 3. This way I can prevent the flashing.

**Closed** 2021-04-15 17:43 UTC
Labels: bug, not reproducible

**Comment by Glitchy-Tozier** [comment] 2021-04-15 17:44
I see, thank you for the explanation and good job!

**Comment by LongJohn-Silver** [comment] 2021-04-27 15:46
Any estimated date for the release? I switched back to my native keyboard because it was crashing too much and it is not something I like too much since it is proprietary.

**Comment by patrickgold** [comment] 2021-04-28 03:49
@LongJohn-Silver Do you use the beta channel or stable? As for the beta it should be Friday, as for the stable I suspect ~7-10 days (I will release v0.3.11 after beta03).
