### ISSUE TITLE
General gestures

### ISSUE THREAD

**Issue by HAXEK** [florisboard/florisboard#1174] opened 2021-08-21 12:55 UTC
❌➡️General gestures: none work. 
❌➡️Space bar gestures: Swipe up, does not work.

- FlorisBoard Version: 0.3.12 
- Install Source:  F-Droid 
- Device: Redmi 7 MIUI 11 
- Android: 10, Stock

**Comment by Glitchy-Tozier** [comment] 2021-08-22 06:46
Is swipe-typing activated on your phone?

**Comment by KLaurence** [comment] 2021-08-22 09:48
While I can't reproduce your spacebar gesture issue in my 0.3.12 installation, I think general gestures not working was already reported in #1086.

While general gestures not working has been fixed before in 0.3.13-beta08, the stable 0.3.13 version that will also contain the fix hasn't been released yet, but [Patrick has said](https://github.com/florisboard/florisboard/pull/1109#pullrequestreview-735509598) that it will be released at the end of next week.

In the meantime, you can download the latest Florisboard Beta version in [the repo's releases](https://github.com/florisboard/florisboard/releases) if you want to.

**Comment by HAXEK** [comment] 2021-08-22 11:55
Thanks, general gestures, they were fixed in the beta phase. ✅😃

**Comment by patrickgold** [comment] 2021-08-25 14:59
As you downloaded and tested beta09, is this issue still relevant or can we close it?

**Comment by HAXEK** [comment] 2021-08-25 15:02
solved thanks, you can close it.✅

**Closed** 2021-08-25 15:03 UTC
Labels: bug
