### ISSUE TITLE
Preview/Try-Button in Settings

### ISSUE THREAD

**Issue by SeriousM** [florisboard/florisboard#221] opened 2021-01-22 05:52 UTC
In order to see how changed settings apply we need a very simple textbox in the settings screen to trigger the keyboard.

**Comment by D3SOX** [comment] 2021-01-22 07:49
Duplicate of #190

**Comment by patrickgold** [comment] 2021-01-22 09:13
Thanks for your suggestion! This has already been suggested in #190, although I have to admit the previous title didn't instantly indicate that the text box is for the preview. I changed the title of that issue to something more meaningful, so further duplicates can be avoided. For further development in this feature please follow along the referenced issue. Closing this issue as it is a duplicate.

**Closed** 2021-01-22 09:13 UTC
Labels: duplicate, proposal

**Comment by SeriousM** [comment] 2021-01-22 09:27
Alright, thank you! I searched for an existing one but as you said the title wasnt clear.
