### ISSUE TITLE
incorrect behaviour send key in Signal app

### ISSUE THREAD

**Issue by betweenwater** [florisboard/florisboard#1037] opened 2021-06-21 08:53 UTC
#### Short description
Shift + send key does not create new line in Signal app, instead it sends the message. Similar to
https://github.com/florisboard/florisboard/issues/33 
Have not noticed issue in other apps

#### Steps to reproduce
1. Open Signal app and click message box to compose message
2. Press shift key + send key
3. See error

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: GitHub
- Device: Pixel 4a 5G
- Android: GrapheneOS (Android 11)

**Comment by Glitchy-Tozier** [comment] 2021-06-22 12:40
For that to happen you have to set some Signal-option to send on Enter, right?

With the default seittings, i couldn't reproduce.

**Comment by betweenwater** [comment] 2021-06-22 13:33
Yes you are right. I have the option "Enter key sends" enabled, but with every other keyboard app I could still use "shift" + "Enter" to insert a new line. It's just Florisboard that responds to the setting by changing the key entirely - it even has a different icon (a "send" icon I presume).

Ideally the "Enter" key should send (per the setting) and "shift" + "Enter" should be new line? This is the behaviour across different apps, as mentioned in the other issue I linked to?

**Comment by patrickgold** [comment] 2021-06-25 00:07
Thanks for your bug report! I just tried this bug out and it is indeed reproducible, although many keyboard behave "incorrect" and sends the message with shift+enter on my phone. (Tested with Gboard, SwiftKey, Hacker's Keyboard). OpenBoard and AnySoftKeyboard do work though, so I guess that many keyboards (including FlorisBoard) just react incorrectly to the requested parameters. I am not entirely sure why though, because afaik FlorisBoard propagates the shift press to the target app. Will have to investigate into this.

**Comment by henk717** [comment] 2021-11-28 10:55
> Thanks for your bug report! I just tried this bug out and it is indeed reproducible, although many keyboard behave "incorrect" and sends the message with shift+enter on my phone. (Tested with Gboard, SwiftKey, Hacker's Keyboard). OpenBoard and AnySoftKeyboard do work though, so I guess that many keyboards (including FlorisBoard) just react incorrectly to the requested parameters. I am not entirely sure why though, because afaik FlorisBoard propagates the shift press to the target app. Will have to investigate into this.

I am also running into this on KoboldAI which uses a web interface that you can access with your phone, in that case its the webbrowser interpreting the input, not an app.

Behavior is consistent with the use of the enter key, however in many different programs the behavior of a shift + enter is different. For example in many word processors you get less spacing with a shift + enter than with enter. The Office app is another one where this behavior is very apparent in word document editing mode.

So what you will most likely change to change is what the app ends up sending when you hit enter since to my knowledge it will be a different keyboard input with shift + enter than just enter. Your app seems to be always sending enter instead of shift + enter.

**Comment by patrickgold** [comment] 2022-04-29 17:53
Above PR is a major rework of the input logic and with the latest linked commit the enter key now respects the shift key state. Note though that the target app must cooperate, else this won't work.

In detail the target app must behave the following so this shift+enter thing works:
- "Enter key sends" is disabled in target app:
  - `action` MUST NOT be set and `flagTextMultiline` must be set
- "Enter key sends" is enabled in target app:
  - `action` MUST be set to something valid and `flagTextMultiline` must be set

If `flagTextMultiline` is not set, FlorisBoard assumes that the target editor is single line and will either execute a set `action` or perform a raw enter, if action is unset, as normal.

This means that for Signal this works really well now, but Element for instance acts up and removes the multi-line flag if this option is enabled, so then it does not work correctly.

This will be released in 0.3.16-beta01, thanks for reporting!

**Closed** 2022-05-02 21:18 UTC
Labels: bug, bug-confirmed, area: kbd-logic
