### ISSUE TITLE
Crash while typing in a different app

### ISSUE THREAD

**Issue by absoluteinc** [florisboard/florisboard#1376] opened 2021-11-02 01:44 UTC
#### Short description
Just installed newest beta version from previous beta version. Customized keyboard settings in the app. Quit the app. Opened a messaging app and started typing and it crashed.

#### Steps to reproduce
1. Open any app
2. Start typing
3. It crashes with a notification that opens FlorisBoard app to show crash report.

#### Environment information
- FlorisBoard Version: 0.3.14-beta05 (61)
- Device: Samsung SM-G973U
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1635817234886.stacktrace</summary>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter jsonConfig
	at dev.patrickgold.florisboard.res.AssetManager.loadJsonAsset-NtoHnFg(Unknown Source:12)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.indexAssetsModule(ExtensionManager.kt:155)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.access$indexAssetsModule(ExtensionManager.kt:103)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex$1.invokeSuspend(ExtensionManager.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1635817234885.stacktrace</summary>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter jsonConfig
	at dev.patrickgold.florisboard.res.AssetManager.loadJsonAsset-0E7RQCE(Unknown Source:12)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.indexInternalModule(ExtensionManager.kt:184)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.refresh(ExtensionManager.kt:145)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.access$refresh(ExtensionManager.kt:103)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex$1.invokeSuspend(ExtensionManager.kt:139)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment] 2021-11-04 17:15
Thanks for your bug report! This bug is currently being investigated by me, but is also a duplicate of #1351. Will close it thus.

**Closed by patrickgold** 2021-11-04 17:15 UTC
Labels: bug
