### ISSUE TITLE
Improve clipboard-manager-pop-up.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1113] opened 2021-07-28 11:48 UTC
1. Make sure the icons have the same size. Currently, the last icon is smaller than it's predecessors.
2. Make sure the text isn't cut off

![florisPlace](https://user-images.githubusercontent.com/59611881/127317274-67fc45e2-9861-4402-adc2-cd3bc13e14e4.jpeg)

#### Environment information
- FlorisBoard Version: 0.3.13 – beta 6
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment] 2021-08-14 09:57
Thanks for your bug report!

I guess this is (again) an issue with smaller sized screens, because on my phone it looks rather normal to me, no small icon and no cut-off text. Will assign it to the list of clipboard issues to work on!

P.S. Does my new "Will add it to the todo list!"-phrase sound better?

**Comment by Glitchy-Tozier** [comment] 2021-08-14 11:06
> I guess this is (again) an issue with smaller sized screens...

I use a Samsung Galaxy S9, which by no means is a small phone. 5,8 Zoll, according to Wikipedia. What do you use?
The weird thing is, there's enough space that the pop-up could have expanded to.

> P.S. Does my new "Will add it to the todo list!"-phrase sound better?

It definitely is more truthful 😜
It's longer, but i think it sounds better!  :)

Off-topic: My Github-app is a bit overwhelmed by your actions:
![Screenshot_20210814-120013_GitHub.jpg](https://user-images.githubusercontent.com/59611881/129444366-88fa918d-666d-415e-9de5-5b40d05314cb.jpg)

**Comment by patrickgold** [comment] 2021-08-14 11:24
> I use a Samsung Galaxy S9, which by no means is a small phone. 5,8 Zoll, according to Wikipedia. What do you use?

OnePlus 7T with 6.55 Zoll, so definitely a bit bigger. I have smaller testing devices though so I can definitely reproduce your issue.

> It definitely is more truthful stuck_out_tongue_winking_eye

Yeah this is what I thought too :)

> Off-topic: My Github-app is a bit overwhelmed by your actions:

Interesting, mine does show it normal. Seems like even GitHub has some small flaws :)

**Comment by Glitchy-Tozier** [comment] 2021-08-14 11:44
> OnePlus 7T with 6.55 Zoll, so definitely a bit bigger. I have smaller testing devices though so I can definitely reproduce your issue.

Kk, in that case you're probably right about screen-size being an important factor.

> Interesting, mine does show it normal. Seems like even GitHub has some small flaws :)

Upon reload it's gone now, but i thought it was funny  :)

**Comment by patrickgold** [comment] 2021-12-11 19:23
This should be fixed with beta07, could you please check if this is actually the case when the beta07 update arrives for you? (I don't have a small phone rn where I could test this out)

**Comment by patrickgold** [comment] 2021-12-11 19:23
Note that I will close this issue with the PR merge, but if you manage to reproduce this bug feel free to reopen!

**Comment by Glitchy-Tozier** [comment] 2021-12-12 16:05
I'll do my best!

**Closed** 2021-12-12 17:24 UTC
Labels: bug, bug-confirmed, area: clipboard

**Comment by Glitchy-Tozier** [comment] 2021-12-16 07:37
@patrickgold You've improved the design a lot! Not just this part, but overall.

One small suggestion: It feels a bit weird to have clipboard-items "move" when selected. (The following item was on the right, and it kinda confused me for a sec):
![Screenshot_20211216-083514_WhatsApp.jpg](https://user-images.githubusercontent.com/59611881/146327926-96974311-741f-4399-b002-7bc719efc3af.jpg)

How about highlighting the original item in its original position, and placing the options-pop-up on the opposite side!

**Comment by patrickgold** [comment] 2021-12-16 09:16
> You've improved the design a lot! Not just this part, but overall.

Thanks, great to hear! The only thong I currently miss (but absolutely don't know how to implement) is the smooth dismissal of clipboard entries (there's no animation for that, it just immediately re-layouts).

> One small suggestion: It feels a bit weird to have clipboard-items "move" when selected.

What I could do is to find a way to recognize if an item is on the left or right and flip the popup layout correspondingly, thus it will only move vertically and not horizontally.

**Comment by Glitchy-Tozier** [comment] 2021-12-16 09:28
> Thanks, great to hear! The only thing I currently miss (but absolutely don't know how to implement) is the smooth dismissal of clipboard entries (there's no animation for that, it just immediately re-layouts).

Yeah, animating old_position -> new_position sounds difficult.

>What I could do is to find a way to recognize if an item is on the left or right and flip the popup layout correspondingly, thus it will only move vertically and not horizontally.

That's pretty much what I meant, but why do you need to move it at all? Why not leave it where it is, highlight it (or darken everything else), and show the pop-up?
If you wanted to make sure that it's fully on-screen, you could quickly scroll it into view first.

**Comment by patrickgold** [comment] 2021-12-16 15:14
> That's pretty much what I meant, but why do you need to move it at all?

To bring the item in focus and to ensure that the vertical baseline is centered through the popup and the item.

**Comment by Glitchy-Tozier** [comment] 2021-12-16 15:42
Hmmm... Maybe it would become less jarring if there was an animation, showing the icon moving from it's original place to the centered location.
