### ISSUE TITLE
Spacebar deletes some characters when tapped rapidly.

### ISSUE THREAD

**Issue by Bantul-the-great** [florisboard/florisboard#1792] opened 2022-04-15 05:15 UTC
#### Short description
The spacebar sometimes deletes the characters if it is tapped several times very rapidly in the typing space present at the very bottom of Florisboard app.

#### Steps to reproduce
1. Go to 'Florisboard app'
2. Click on 'the down-most typing space for checking current keyboard setup.
3. The spacebar sometimes deletes the characters if it is tapped several times very rapidly.
4. It is only seen on the Typing space present at the very bottom of the app itself. It is not reproducible so far in any other field while typing. 

#### Environment information
- FlorisBoard Version: 0.3.15(80)
- Install Source: F-Droid
- Device: Redmi note 7s (lavender)
- Android: 10, MIUI Global 12.5.1 stable

https://user-images.githubusercontent.com/88554859/163524647-cff033dd-0a19-4390-aa66-057ad9dba080.mp4

**Comment by Glitchy-Tozier** [comment] 2022-04-15 05:29
Looks like it's a bug involving the "double-space turns into period"-feature.

**Comment by patrickgold** [comment] 2022-04-15 17:12
Thanks for your bug report, can confirm this bug.

Above commit improves the behavior a bit, but for me to be able to fix it a lot better I need to wait on the cached input re-write, which I will do soon as I need it that new cached input system anyways for the word suggestions in 0.4.0.

**Comment by patrickgold** [comment] 2022-04-28 23:11
As above PR fixes the double-space-period bug (based on initial testing) I cannot reproduce this bug anymore using the latest commit in above PR. As such I will close this issue once I merge the PR in. Could you still try it out if it is fixed once 0.3.16-beta01 is released this weekend? This would help a lot confirming if it is fixed or if it needs tweaking. Thanks!

**Closed** 2022-05-02 21:18 UTC
Labels: bug, bug-confirmed, area: kbd-logic
