### ISSUE TITLE
Swipe typing in English only

### ISSUE THREAD

**Issue by xDonatello** [florisboard/florisboard#980] opened 2021-06-01 14:13 UTC
I have set Italian, however typing via swipe only takes English words.

#### Environment information
- FlorisBoard Version: 0.3.12 and 0.3.13-beta03
- Install Source: GitHub
- Device: Mi 9 Lite
- Android: 11

**Comment by GoRaN909** [comment] 2021-06-01 22:19
Word suggestions and glide typing is only availabe to English(US) not availabe for other languages YET this app is on the developing stage, Maybe @patrickgold add support for all other locale and languages :)

**Comment by Micha-Btz** [comment] 2021-06-08 11:10
I stumbled over this. I don't know how much work it is, but I would like swipe for German.

**Comment by Luensche** [comment] 2021-06-08 11:21
As I understood it is related to #325. Without suggestions no swiping.

**Comment by Glitchy-Tozier** [comment] 2021-06-11 13:23
This is not a bug, it's just that development didn't quite make it to non-English languages yet. Be rest assured that adding more languages is on the roadmap, it may take one or two more updates though.
As Luensche said, the plan for this feature can be found in #352.

If you don't mind, I'll close this issue to keep the list free of duplicates!

**Closed by Glitchy-Tozier** 2021-06-11 13:23 UTC
Labels: bug
