### ISSUE TITLE
Respect capital when using suggestions

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1375] opened 2021-11-01 15:14 UTC
When I type "Automotibe" and I then use the suggestion "automotive" the capital A has changed to a lower case. It would be nice if capitals could be preserved.

**Comment by patrickgold** [comment] 2021-11-03 22:23
This is a well-known issue and will be fixed with the new suggestions in 0.3.15/16/17. Closing as a duplicate of #441

**Closed by patrickgold** 2021-11-03 22:23 UTC
Labels: proposal
