### ISSUE TITLE
iOS emoji

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#2236] opened 2023-06-04 04:03 UTC
hi i know this are FOSS but it's likely android system emoji looks ugly as heck 

i recommend to use iOS emoji style for florisboard as other emoji style are not good as iOS 

thank you for consideration 🙏

**Comment by Glitchy-Tozier** [comment] 2023-06-17 08:07
I agree that an emoji-rework would be a good idea.  If I'm not mistaken, the emojis Twitter/Telegram use are open-source (and look great), so that might be an option as well.

**Comment by kadisonm** [comment] 2023-12-28 15:15
I would also like to switch emoji packs. Maybe offering a choice between iOS, the current and twemoji would be nice.

**Comment by obakha** [comment] 2024-11-21 19:36
I second this.

**Comment by lm41** [comment] 2024-11-24 18:46
Duplicate of https://github.com/florisboard/florisboard/issues/1965

**Closed** 2024-11-24 18:46 UTC
Labels: proposal, area: emoji-kaomoji
