### ISSUE TITLE
Allow option for cut/copy/paste/slect all action icons to appear over keyboard like in 0.3.16

### ISSUE THREAD

**Issue by LeggoMahEggo** [florisboard/florisboard#2599] opened 2024-09-24 20:12 UTC
### Feature idea

I was trying 0.4.0 a few days ago, but I found the "go to different screen to use cut/copy/paste/select all" very annoying -- it was mighty useful having access to those above the keyboard while in the middle of a conversation, and I didn't see a way to do it in 0.4.0. So I reverted back to 0.3.16 for the time being. If possible, I would like to request a feature that allows this option to be selected.

**Comment by patrickgold** [comment] 2024-09-24 22:16
Related to or Duplicate of #2595

**Comment by patrickgold** [comment] 2024-09-24 22:19
Closing this issue in favor of continuing this discussion in the referenced issue.

**Closed by patrickgold** 2024-09-24 22:19 UTC
Labels: proposal

**Comment by BHydden** [comment] 2024-09-24 22:21
Just in case all they want to do is reorder the actions, tap on `...` and then scroll down and select `Reorder actions` and you can put all those options on the main bar. 🙏

**Comment by patrickgold** [comment] 2024-09-24 22:27
Yes ofc if just that is needed you make a good point, I think though that there is actually a wish for more display of actions in the keyboard screen itself without having to tap anywhere-
