### ISSUE TITLE
unexpected

### ISSUE THREAD

**Issue by krillnt** [florisboard/florisboard#1511] opened 2022-01-17 08:30 UTC
#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Realme RMX2020
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1642407601611.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 402653184, growth limit 402653184
	at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
	at android.os.Binder.execTransact(Binder.java:992)

```
</details>

<details>
<summary>1642407601699.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 0 free bytes and 0B until OOM, target footprint 402653184, growth limit 402653184
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1642407605528.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and 0B until OOM, target footprint 402653184, growth limit 402653184
	at android.os.BinderProxy.getInstance(BinderProxy.java:411)
	at android.os.Parcel.nativeReadStrongBinder(Native Method)
	at android.os.Parcel.readStrongBinder(Parcel.java:2178)
	at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:179)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```
</details>

**Comment by Glitchy-Tozier** [comment] 2022-01-17 08:46
This is a duplicate of #1268.
The crashes you experience are OutOfMemory issues, which are caused by word suggestions. The current workaround is to disable word suggestions if they cause trouble and wait for version 0.3.15, where Patrick will re-implement them to make sure this specific crash does not occur again.

**Closed** 2022-01-17 18:38 UTC
Labels: bug, duplicate
