### ISSUE TITLE
Spacebar-text is too large

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#862] opened 2021-05-13 11:23 UTC
Currently, the language-indicator on the spacebar is too big. (It kind of looks like a keyboard for people with sight-problems now)

Go for whatever solution you think is optimal!

Old keyboard (which has the perfect font size)
![20210513_132256.jpg](https://user-images.githubusercontent.com/59611881/118119277-67ccde80-b3ee-11eb-81a3-99362fded7b4.jpg)

New spacebar:
![Screenshot_20210513-130540_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/118119127-2fc59b80-b3ee-11eb-8144-583bf8a059d2.jpg)

**Comment by kurdikeyboard** [comment] 2021-05-13 12:33
You right the language name is to biggy and ugly on space-bar i wish that in the feature versions add an option to hide the language name on SPACEBAR :)

**Comment by zareami10** [comment] 2021-05-15 15:56
For me the language-indicator text ("English (United States)") is big enough to span outside of the space-bar area, making the keyboard look "broken".

So it would be nice to to have some kind of a temporary fix before adding options, etc.

![photo_2021-05-15_20-24-34](https://user-images.githubusercontent.com/59122438/118370174-c72c1980-b5bb-11eb-9624-dba8fe8dffbd.jpg)

**Comment by patrickgold** [comment] 2021-05-15 18:13
@zareami10 That's one thing where I am unsure how exactly this occurs - I am asking the system to measure the text if it fits inside the space bar and somewhere in there (probably on FlorisBoard's end) the measurement info gets messed up and then this happens. Just to make sure - your system primary locale is set to en_US (English (United States))?

**Comment by zareami10** [comment] 2021-05-15 19:29
> @zareami10 That's one thing where I am unsure how exactly this occurs - I am asking the system to measure the text if it fits inside the space bar and somewhere in there (probably on FlorisBoard's end) the measurement info gets messed up and then this happens. Just to make sure - your system primary locale is set to en_US (English (United States))?

I have two subtypes in FlorisBoard, English (United States) and Persian (FA), with system language being set to English (United States).

I played around a bit with the settings and it appears that the issue is caused by the "Show utility key" option being set to off. If I turn it back on then the size is normal and the issue is no more present.

**Comment by Glitchy-Tozier** [comment] 2021-05-15 19:47
Can reproduce zareami's steps.

**Comment by patrickgold** [comment] 2021-05-17 01:55
@zareami10 Thanks for your explanation, I've heard from some other users too that the utility key seems to play a role in the measurement bug of the space bar. Interestingly on my devices the space bar text is always within bounds, maybe a bit to large but not clipping out.

**Comment by patrickgold** [comment] 2021-05-22 18:13
Above PR adds a maximum value to the space bar text size calculation, thus the space bar text does not seem to be sooo large anymore. It still automatically gets smaller if the subtype label should require it. Will be released in v0.3.13-beta02 in the next few days.

**Closed** 2021-05-22 18:16 UTC
Labels: proposal, proposal-accepted
