### ISSUE TITLE
Added Bengali (INDIA) Characters Layout

### ISSUE THREAD

**Issue by MayaBi7** [florisboard/florisboard#2140] opened 2023-01-08 17:57 UTC
Plz added Bengali (বাংলা) characters layout
Screenshot Source - GBoard - The Google Keyboard
![IMG_20230108_231858](https://user-images.githubusercontent.com/96541364/211211317-f96935dd-ae49-4fde-bb01-b0b98b50e642.jpg)
![IMG_20230108_232641](https://user-images.githubusercontent.com/96541364/211211414-50fca674-d0ca-43d1-a93d-93917306cfb6.jpg)

**Comment by tsiflimagas** [comment] 2023-01-08 19:14
Duplicate of #1885.

**Closed by tsiflimagas** 2023-01-08 19:14 UTC
Labels: proposal
