### ISSUE TITLE
Add tabs/categories to Clipboard History

### ISSUE THREAD

**Issue by Tombstone2K** [florisboard/florisboard#2272] opened 2023-07-20 17:17 UTC
Maybe adding tabs/categories to clipboard history would be great. Something like having a tab for email templates, another for contact information, etc would be really cool

**Comment by tsiflimagas** [comment] 2023-09-28 00:29
Thank you for you proposal! This is actually a duplicate of #1558. As answered there, as nice as the idea may sound, it goes too far for a keyboard app thus it doesn't make that much sense to add it, but it would rather make sense to implement this in a notes app.

**Closed by tsiflimagas** 2023-09-28 00:29 UTC
Labels: proposal
