### ISSUE TITLE
Automatic Addition Of '0' After Typing 'auto' Or Any Word That Starts With It.

### ISSUE THREAD

**Issue by atikattar1104** [florisboard/florisboard#2041] opened 2022-08-31 11:37 UTC
#### Short description
Just As The Title Says, Number '0' Is Added Automatically When You Type That Word. But It Only Happens When The First Letter 'a' Is Lowercase, And Not With Uppercase Letter 'A'. I Saw This Issue At First In 'v0.4.0-alpha02', And It Still Occures In alpha03 Release As Well. I Am Not Sure Either This Issue Is Only Happening In My Device Or With Other Devices As Well, But I Will Try To Check Whether This Issue Occures In Other Devices Or Not.

#### Steps to reproduce
1. Go To Any App That Have Text Input Field (I.E. - Edittext View)
2. Type 'auto' Or Any Word That Starts With It, With Lowercase 'a' At The Beginning.
3. Hit Spacebar Or Add Any Symbol Just After It.
5. See Error.

#### Environment information
- FlorisBoard Version: v0.4.0-alpha03
- Installation Date: 3 Days After Release.
- Install Source: GitHub
- Device: Redmi 7A
- Android: 10, Stock
- MIUI: 12.0.3.0

**Comment by atikattar1104** [comment] 2022-08-31 11:43
![Screenshot_2022-08-31-17-10-37-000_com android chrome](https://user-images.githubusercontent.com/93785261/187670586-cc001526-338a-4895-b049-b7af7bf7aafa.jpg)
![Screenshot_2022-08-31-17-10-44-901_com android chrome](https://user-images.githubusercontent.com/93785261/187670597-4171c893-5ac9-44fc-8030-189e309cb87a.jpg)
![Screenshot_2022-08-31-17-10-50-982_com android chrome](https://user-images.githubusercontent.com/93785261/187670604-45e7291b-86c3-43eb-9aad-257c21f899e0.jpg)
![Screenshot_2022-08-31-17-10-58-680_com android chrome](https://user-images.githubusercontent.com/93785261/187670605-ed7ef768-de86-4d66-ad9e-c8f1698668dc.jpg)
![Screenshot_2022-08-31-17-11-06-554_com android chrome](https://user-images.githubusercontent.com/93785261/187670607-22dd34af-6def-498b-99b1-8187fac12593.jpg)

Screenshot For Reference

**Comment by atikattar1104** [comment] 2022-08-31 11:49
Also, When I Was Writing This Issue, And Typing The Word 'auto', And Correcting The Word By Removing '0' Using Backspace And Adding A Space After That, Another 'auto0' Is Added Just After The Corrected 'auto' Word, Making It 'autoauto0'.

**Comment by atikattar1104** [comment] 2022-08-31 11:52
Also, When I Typed 'auto0' For Making My Previous Comment, And Hitting Spacebar After That, Another '0' Got Added. Making It 'auto00'.

**Comment by atikattar1104** [comment] 2022-08-31 11:59
When You Add '0' After 'auto' (I.E. - Typing 'auto0'), Another 0 Gets Added Without Hitting Spacebar Or Adding Any Symbol. Making It 'auto00'. And When You Add Space Or Any Symbol After That, Another '0' Is Added.

**Comment by atikattar1104** [comment] 2022-08-31 12:02
This Thing Is Not Happening With Other Keyboards Though.

**Comment by atikattar1104** [comment] 2022-08-31 12:05
New One Found. When You Add A '0' After 'auto0' Or 'auto00', Two '0's Get Added Each Time You Press '0' Key.

**Comment by atikattar1104** [comment] 2022-08-31 12:07
![Screenshot_2022-08-31-17-36-50-800_com android chrome](https://user-images.githubusercontent.com/93785261/187674659-ee24aefd-4be5-4e85-a30b-897161ad0907.jpg)
Like This.

**Comment by patrickgold** [comment] 2022-08-31 18:25
Duplicate of #1976, this annoying placeholder will be removed with 0.4.0-alpha04. Closing thus.

**Closed by patrickgold** 2022-08-31 18:25 UTC
Labels: bug
