### ISSUE TITLE
Theme Creator: Don't scroll all the way up

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#427] opened 2021-03-03 10:10 UTC
In the theme creator, everytime you "OK" out of pop-up, the screen scrolls up all the way to the top off the options.
Leave the screen where it is, please.

EDIT: Now I can't reproduce this.

EDIT2: Found out how to reproduce it: Go into the design-editor **and click/edit the name of the theme**. Only then will the bug show itself.

EDIT3: This probably should be tagged as a Bug.

**Comment by patrickgold** [comment] 2021-03-03 18:36
Thanks for the report! This bug has already been reported in #379,k but at the time I was unable to reproduce it. Now I know why it happens: auto-scroll by Android to focus the previously focused text input field. Will place this one on my todo list, but use the already existing issue, closing this one.

**Closed by patrickgold** 2021-03-03 18:36 UTC
Labels: proposal
