### ISSUE TITLE
Add support for Bangla (Bângladesh)

### ISSUE THREAD

**Issue by mitexleo** [florisboard/florisboard#2100] opened 2022-10-28 05:07 UTC
Thanks to  Everyone who contributed to this project...

Please Add Support For Bangla Language ... (Also Phonetic Bengali)

**Comment by tsiflimagas** [comment] 2022-10-28 05:15
Thanks for your suggestion. This seems to be a duplicate of #1885 though, so let's track this layout addition there.

**Closed by tsiflimagas** 2022-10-28 05:15 UTC
Labels: proposal
