### ISSUE TITLE
Crash mid typing, possibly related to gesture typing?

### ISSUE THREAD

**Issue by SanJacobs** [florisboard/florisboard#810] opened 2021-05-05 00:38 UTC
#### Short description
Sudden crashes mid typing. I did nothing special, I think I hit the letter K. It has happened a couple of times, started happening after I added a second layout, Norwegian, and enabled gesture typing.

#### Steps to reproduce
Type. I was using the Norwegian layout at the time, but I'm not sure if it matters.

#### Environment information
- FlorisBoard Version: v0.3.10
- Install Source: F-Droid
- Device: Note 9
- Android: 10, OneUI 2.5

~~~ 1620132570129.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 868120 free bytes and 847KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 63438848 bytes)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1$1.invoke(GlideTypingManager.kt:81)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1$1.invoke(GlideTypingManager.kt:18)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:422)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1620174433183.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 300160 free bytes and 293KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at org.json.JSONObject.put(JSONObject.java:272)
	at org.json.JSONTokener.readObject(JSONTokener.java:394)
	at org.json.JSONTokener.nextValue(JSONTokener.java:104)
	at org.json.JSONObject.<init>(JSONObject.java:164)
	at org.json.JSONObject.<init>(JSONObject.java:181)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1620048091033.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 1048840 byte allocation with 1818592 free bytes and 1775KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 21757952 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3257)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
	at java.lang.StringBuffer.append(StringBuffer.java:367)
	at java.io.StringWriter.write(StringWriter.java:94)
	at kotlin.io.TextStreamsKt.copyTo(ReadWrite.kt:125)
	at kotlin.io.TextStreamsKt.copyTo$default(ReadWrite.kt:120)
	at kotlin.io.TextStreamsKt.readText(ReadWrite.kt:107)
	at dev.patrickgold.florisboard.ime.extension.AssetManager.loadAssetRaw-IoAF18A(AssetManager.kt:202)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:78)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


Some time passes between each time it happens, and since I want to actually use my phone and its keyboard, I can't experiment to find out exactly what the causal factor was just hope the debug info will be useful.

**Comment by patrickgold** [comment] 2021-05-05 01:17
Thanks for your crash report! This crash seems to be a OOM (OutOfMmeory) issue directly caused by glide typing. This kind of issue is known and summarized in #677. When exactly glide typing will be fixed in terms of memory is unclear, but it has a pretty high priority on my todo list. Closing this issue thus as a duplicate.

**Closed** 2021-05-05 01:17 UTC
Labels: bug, duplicate
