### ISSUE TITLE
Cant open Florisboard settings in device's keyboard and input settings.

### ISSUE THREAD

**Issue by main-character** [florisboard/florisboard#573] opened 2021-04-05 07:35 UTC
#### Short description

I just installed florisboard and whenever i wanted to change some settings, i cant open the florisboard keyboard settings in my keyboard and input devices settings.

#### Steps to reproduce
1. Go to Settings
2. Click on keyboard and input menu
3. Scroll down and try to open the florisboard keyboard settings
4. No response

#### Environment information
- FlorisBoard Version: 0.3.10-beta05
- Install Source: Fdroid
- Device: Realme 6 G90T
- Android version, ROM: Android 10, RMUI 1

[Video of bug](https://drive.google.com/file/d/1T6EcbF7-7vT5sAwDD0S5smu9NUl977Cf/view?usp=sharing)

**Comment by Glitchy-Tozier** [comment] 2021-04-05 07:53
Can reproduce on Samsung Galaxy S9, v.0.3.9.

**Comment by main-character** [comment] 2021-04-05 08:39
I installed the github version first when i encountered that bug so i thought maybe it's because i have outdated florisboard. I installed the beta and still got the same result.


And thank you lols

**Comment by patrickgold** [comment] 2021-04-05 15:21
Thanks for your bug report! Unfortunately this is a bug I know since pre-v0.1.0 but which I have been unable to solve after many attempts at fixing, its probably just a stupid missing declaration somewhere but I've looked at the code of many other FOSS keyboards where it works and still can't figure out what I am doing differently for this to work. If either I or someone else stumbles across a solution for this, the Settings will be accessible via the Language&Input system screen :) Closing this issue as a duplicate of #366.

**Closed by patrickgold** 2021-04-05 15:21 UTC
Labels: bug
