### ISSUE TITLE
Multilingual Typing

### ISSUE THREAD

**Issue by TheSmilingTurtle** [florisboard/florisboard#2358] opened 2024-01-03 14:03 UTC
Gboard has a feature that can "combine" multiple languages called multilingual typing. This combines the word suggestions from the diffetent languages and more importantly the secondary symbols of each language. It would be nice if florisboard had a similar feature, where you could either automatically or manually compose the secondafy symbol maps of different languages. 

For example I use Czech, German and English symbols regularly, which is awesome in gboard because i can just have all three keyboards active and don't need to switch to the Czech keyboard to type " ř ".

**Comment by loucasal** [comment] 2024-11-02 11:36
Duplicate of #155, this can be closed.

**Comment by tsiflimagas** [comment] 2024-11-02 14:07
Thanks for pointing out, let's keep the discussion in the original issue.

**Closed by tsiflimagas** 2024-11-02 14:07 UTC
Labels: proposal
