### ISSUE TITLE
Pop-up Won't Disappear

### ISSUE THREAD

**Issue by jetrosut** [florisboard/florisboard#515] opened 2021-03-28 08:58 UTC
#### Short description
The pop-up that appears when you hold the return button does not disappear (visually). I have no idea how this can be reproduced. I opened up the keyboard and was faced with this issue. Half an hour later, it was fixed by itself. [Here's a video of the bug](https://i.imgur.com/CfEz3sY.mp4).

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: GitHub
- Device: A Samsung Galaxy Note
- Android version, ROM: 7, Stock (Samsung's)

**Comment by Glitchy-Tozier** [comment] 2021-03-28 16:26
How much of how the keyboard looks is theme-related?

**Comment by jetrosut** [comment] 2021-03-28 18:06
> How much of how the keyboard looks is theme-related?

Most of it. I just dimmed the colors of the Floris Black theme down. Made all the buttons uniform colored and set the text color to the key background color so that what character I am inputting can be seen only when I press the the key, which makes the key background completely black. Anyway, it's just Floris Black with only a few modifications.

**Comment by patrickgold** [comment] 2021-03-28 18:16
Thanks for your bug report! I am completely unable to reproduce it, even after trying around several touch bugs which are often known to occur in Android apps. Will have to investigate into this.

Unrelated question out of curiosity: Why exactly did you opt to make the key background the same as the font color? Is it so you train your muscle memory where every key is or is there another reason for that?

**Comment by jetrosut** [comment] 2021-03-28 18:45
> Unrelated question out of curiosity: Why exactly did you opt to make the key background the same as the font color? Is it so you train your muscle memory where every key is or is there another reason for that?

There are multiple reasons behind it. One of them is aesthetics: I love physical keyboards that don't have any text on them, so I knew I had to reproduce it on Android the moment I saw Florisboard and the customizations it offers. Another reason is I like my room pitch black at night, so the less bright my phone is, the less my eyes hurt; dark text rather than white surely makes a difference. In addition to those, having recently switched to Florisboard, I need to learn where each character I use is especially symbols and popups. This surely helps.

**Comment by Glitchy-Tozier** [comment] 2021-03-28 19:19
Is it the same version that is available in the Play-Store or some beta-test version?

I can't replicate it either, as much as I try to  :/

**Comment by jetrosut** [comment] 2021-03-28 19:31
> > FlorisBoard Version: 0.3.9
> 
> Is it the same version that is available in the Play-Store or some beta-test version?
> 
> I can't replicate it either, as much as I try to :/

It's [this one](https://github.com/florisboard/florisboard/releases/download/v0.3.9/florisboard-0.3.9.apk). I too cannot replicate it as I don't know how it occured in the first place. Unlocked my phone, tapped an input field and the keyboard appeared like that with the bug. I ignored it for some time, put my phone away; next time I picked it up, the popup was gone.

**Comment by jetrosut** [comment] 2021-04-03 19:02
[Here we go again](https://i.imgur.com/DCkRYQR.jpg). Is there anything I can do to help reproduce the issue? The popup is still there on my phone.

**Comment by Glitchy-Tozier** [comment] 2021-04-03 19:18
Huh, so this can happen with all pop-ups?

One way to remove this might be to simply rotate your phone, thus resetting the keyboard.

One great thing you can do is continuing what you currently do: report when you encounter the bug and (if possible) share how you got there.

**Comment by Glitchy-Tozier** [comment] 2021-04-04 08:03
1. Hold down multiple keys to trigger multiple popups
2. Perform an action that closes the keyboard.
Examples for this are pressing the home button, the back button, that task-manager button, or locking your screen.
3. Reopen the keyboard and see bug.


Is this your bug?


(Btw, it can be stacked. You can do a lot of damage using this.)
![Screenshot_20210404-100052_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/113502514-0848fc80-952d-11eb-8ff8-3169c0e09073.jpg)

**Comment by jetrosut** [comment] 2021-04-04 17:14
@Glitchy-Tozier No, they seem to be different. I can reproduce that bug by holding multiple keys and locking the screen but the pop-up disappears when I tap the key again. In my bug, tapping the key again does not do anything.

**Comment by Glitchy-Tozier** [comment] 2021-04-04 17:16
@jetrosut I guess i should've outlined some differences between the methods.

If you use any of the other methods, the pop-ups shouldn't be cancle-able.

**Comment by jetrosut** [comment] 2021-04-04 18:38
@Glitchy-Tozier Well, in my case, the menu and back buttons don't do anything as long as I am holding my finger on the screen. I can't reproduce the issue with the home button at all.

**Comment by Glitchy-Tozier** [comment] 2021-04-04 18:52
Found another way :)

Do the exact same thing, but click on any  option on the screen that closes the keyboard.

For example this button in the Github-App: ![Screenshot_20210404-204847_GitHub.jpg](https://user-images.githubusercontent.com/59611881/113518558-4a9f2780-9587-11eb-8286-c7ae8169563b.jpg)

Alternatively, you can click on the settings-button on florisboard instead.
![Screenshot_20210404-205152_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/113518590-981b9480-9587-11eb-9d9f-6486b673e4fb.jpg)

Do those work for you?

**Comment by jetrosut** [comment] 2021-04-05 08:54
@Glitchy-Tozier Nope, the pop-ups are gone once I hit that button.

**Comment by Glitchy-Tozier** [comment] 2021-04-05 08:56
So you tried every single action I suggested and it still is only temporary?

In that case it's probably something different, yeah  :/

**Comment by Glitchy-Tozier** [comment] 2021-04-05 16:34
Anyway, those things I've mentioned should all be fixed once #513 is fixed.

Maybe that doesn't aply for your version of the bug though.

**Comment by agichim** [comment] 2021-04-14 16:09
Changing keyboards made the pop-up disappear. I changed from Floris to Swiftkey and back to Floris.

**Comment by jetrosut** [comment] 2021-04-14 16:51
> Changing keyboards made the pop-up disappear. I changed from Floris to Swiftkey and back to Floris.
That's not what it's meant here. Sure, you can make them disappear by restarting Florisboard. Though, the issue is that there are pop-ups that won't automatically go away (even when you aren't holding down your finger), they just stay there until you restart Florisboard.

**Closed** 2021-04-30 16:51 UTC
Labels: bug, needs investigation, not reproducible
