### ISSUE TITLE
Question mark charchter is wrong in "arabic"

### ISSUE THREAD

**Issue by EgyCrash** [florisboard/florisboard#373] opened 2021-02-18 18:10 UTC
#### Short description
Question mark charchter is wrong in "arabic"
It should be "؟"
But it draw "?" Just  like english charachter

#### Environment information
- FlorisBoard Version: 0.3.6
- Install Source: F-Droid
- Device: Huawei matepad
![Screenshot_20210218_200853](https://user-images.githubusercontent.com/12765580/108401631-372d3c80-7225-11eb-8819-99b8172d8b02.jpg)

- Android version, ROM: 10

**Comment by Waelwindows** [comment] 2021-02-18 20:38
Duplicate of #120

**Closed** 2021-02-18 23:33 UTC
Labels: bug
