### ISSUE TITLE
no colour choice for emojis

### ISSUE THREAD

**Issue by EzekealI** [florisboard/florisboard#1264] opened 2021-09-16 10:24 UTC
Hi, I'm having an issue with the emojis, if I long press on for example the thumbs up emoji I am not able to choose from the different coloured options because the menu for it opens only for a second before closing and not doing anything. 
I'm on a Huawei P20 if thats any help.

**Comment by GoRaN909** [comment] 2021-09-16 13:50
This issues is duplicate of #1047

**Comment by Glitchy-Tozier** [comment] 2021-09-16 19:14
Thanks to @GoRaN909 for pointing out the duplicate, please continue further discussion in the mentioned issue. :)

**Closed by Glitchy-Tozier** 2021-09-16 19:14 UTC
