### ISSUE TITLE
Crash - reason unknown

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1383] opened 2021-11-04 12:52 UTC
#### Environment information
- FlorisBoard Version: 0.3.14-beta05 (61)
- Device: Xiaomi Mi 9T Pro
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1636030328875.stacktrace</summary>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter jsonConfig
	at dev.patrickgold.florisboard.res.AssetManager.loadJsonAsset-NtoHnFg(Unknown Source:12)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.indexAssetsModule(ExtensionManager.kt:155)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex.access$indexAssetsModule(ExtensionManager.kt:103)
	at dev.patrickgold.florisboard.res.ext.ExtensionManager$ExtensionIndex$1.invokeSuspend(ExtensionManager.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment] 2021-11-04 17:14
Thanks for your crash report(s)!

Crash 1 and 4 are a duplicate of #1351

Crash 2 and 3 are a duplicate of pinned issue #1268

**Closed by patrickgold** 2021-11-04 17:14 UTC
Labels: bug
