### ISSUE TITLE
Florisboard crashed while switching keyboard during having a theme bug

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#1096] opened 2021-07-24 01:50 UTC
Short description(Area theming)
When switching between system dark/white theme the florisboard changes to bad looking theme ,
Currently i do not have screenshot ,but i will post screenshot when i will reproduce the issue.

Steps to reproduce
1. Enable florisboard to follow system theme
2. Toggle system dark/white theme
3. Click on any input text box
4. See florisboard  is having a mismatch theme based on mix value of black and white which isnt good looking
5. Then i switched to aosp keyboard by holding space gesture
6. Again i used space gesture to switch to florisboard but florisboard crashed

Here is log 
[Crash.txt](https://github.com/florisboard/florisboard/files/6871755/Crash.txt)

Environment information
- florisboard Version: 0.3.13beta06
- Install Source: Github
- Device: Poco M2 Pro 
- Android: 11 ArrowOS

**Comment by GithbUser** [comment] 2021-07-24 11:03
Look at this screenshot 
This is what i am getting
![IMG_20210724_163306_189](https://user-images.githubusercontent.com/75420364/126866491-92f77227-2495-4f10-9b3f-791b5682e928.jpg)

**Comment by GithbUser** [comment] 2021-07-24 11:06
Here is the another crash log 
[Crash2.txt](https://github.com/florisboard/florisboard/files/6872305/Crash2.txt)

Hope it contains something useful

**Comment by patrickgold** [comment] 2021-07-24 17:35
Thanks for your bug report! It seems like the coroutine context for executing tasks in parallel gets messed up, but I am not exactly sure, as there are quite a few different stack traces in your report. I will see if I can reproduce the crash on my device, because then I will be able ton fix this bug much quicker.

**Comment by patrickgold** [comment] 2021-07-24 17:44
I just discovered that your provided crash logs are related to #1097, so it is currently possible that either those two are connected with each other or if there's some other issue.

**Comment by patrickgold** [comment] 2022-03-19 11:59
Based on looking at the crash logs all of them are fixed in the latest debug builds (and will be in today's 0.3.14-rc0s release). Closing thus. Should you still be able to reproduce this issue in the latest rc release please tell me, thanks!

**Closed by patrickgold** 2022-03-19 11:59 UTC
Labels: bug, needs investigation, area: kbd-logic
