### ISSUE TITLE
Can't draw long words when gesture typing

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1851] opened 2022-05-14 02:50 UTC
#### Short description
It's not a new report, it's already been mentioned on Matrix and it's even mentioned in release notes, but since the current effort is to improve gesture typing, probably having it here will help in tracking it. Though it seems to be a hard one to tackle, so I don't know if you're gonna do it in this iteration.
A few things to note are that sometimes it actually works fine, maybe occasionally after the app has been terminated, but it breaks again later on. Another one, is that I usually test it with the word "performance" since that was the word I typed when I first noticed the issue. It lock out on "perform", if correctly detected. Not sure if it's the same on different devices.
Something that will probably be helpful is to find out on which build, approximately, this first occured. I'll try to pinpoint this, since it certain that this bug wasn't there somewhere in the past. It was somewhere in the UI rewrite, if I remember well.

#### Steps to reproduce
1. Gesture-type a long word like "performance"
2. See the prediction locking out early on a shorter substring of the word you meant to type.

#### Environment information
- FlorisBoard Version: 0.3.16-beta02
- Install Source: GitHub
- Device: Xiaomi Redmi note 8
- Android: 12.1, custom

**Comment by patrickgold** [comment] 2022-05-14 11:02
Yes this is indeed a hard one to tackle. I just tried to investigate a bit further but without a result thus far. The internal statistical glide logic is very complex (and also still tailored to the old code base a bit), which makes matters very difficult.

I definitely know that this bug does not affect the `GlideTypingDetector` (which delegates the touch events to the internal glide logic), else the glide trail would also stop working.

What I am currently trying to figure out is, if this lock out of the word happens at a constant time (e.g. always 2 sec after start?) or if it is more dependent on distance and glide points generated. Do you have any observations in this area when playing around with the glide gesture?

> Something that will probably be helpful is to find out on which build, approximately, this first occured. I'll try to pinpoint this, since it certain that this bug wasn't there somewhere in the past. It was somewhere in the UI rewrite, if I remember well.

Yep that's true, it happened in one of the 0.3.14 betas IIRC. Still I don't see a reason why the "new" TextKeyboardLayout should bug out in this regard, as gestures and the glide trail work normally too...

**Comment by tsiflimagas** [comment] 2022-05-14 15:49
> Do you have any observations in this area when playing around with the glide gesture?

Good question! Now that you asked, I tried in this direction and it actually seems to be like that. If I draw the word really fast, it's detected correctly. I can't quite calculate how long is this "threshold" which has been formed, but 2s maybe is a good approximation.

**Comment by patrickgold** [comment] 2022-05-15 11:26
After quite some debugging I found the reason, why long words weren't detected, and it indeed was caused by the new touch logic:

The new touch logic provided unnecessary ultra-precise touch movements, with accurate history points, while the old logic did omit the history, to save on performance. The gesture logic is quite memory intensive, so it has a maximum gesture points cap per gesture, to prevent OOM issues (300 gesture points at most per gesture). So this was the reason why the cap was hit so fast.

I solved the issue by removing the touch point history from the new touch logic, as this ultra-precision is not really needed (it is sometimes as precise as 1px per history point, which is super unnecessary). Also I upped the gesture point limit from 300 to 500 per gesture, this means that long words can now be properly gestured on a phone screen.

With this in mind, I now fully know why issue #579 on tablets occurs -> bigger screen, more sample points -> hit limit waay sooner. I don't know how to fix this though, because I don't have unlimited memory (OOM flashbacks to 0.3.9/10 haha). I think this can be fixed/circumvented by re-usable float arrays or even the full Gesture object, instead of allocating a new one each time a gesture calculates a suggestion. But to fix that I need to rework some other inner glide logic parts, which my current iteration is not addressing (need to finish up with the glide fixes and work on some other improvements for 0.3.16, so I have a good base for the 0.4.0 dev cycle).

IMO this issue is fixed (and for tablets we use #579 for tracking/discussion), and thus I attached it to PR #1844. Will be released in 0.3.16-beta03 in a few days.

**Comment by tsiflimagas** [comment] 2022-05-15 14:19
Well, I'm in awe! I tried it with various long words and it indeed works fine and nicely again, amazing job! Also, I'm glad to see that you have ideas for future improvement already (looks like there's always something to add to the backlog XD). Thank you 😄

**Comment by patrickgold** [comment] 2022-05-15 16:33
Thanks for trying it out!

> looks like there's always something to add to the backlog XD

Yup there always is, this is the life of a software dev :)

**Closed** 2022-05-15 16:35 UTC
Labels: bug, bug-confirmed, area: glide-typing
