### ISSUE TITLE
Addition of an Emoji search feature

### ISSUE THREAD

**Issue by HzbiTigrinya** [florisboard/florisboard#2550] opened 2024-09-05 13:48 UTC
### Feature idea

Sometimes when needing a specific Emoji but being unable to find it by looking one by one, I'm forced to switch to another keyboard to use the search feature. I like the security and privacy of Florisboard, which is why I want to completely switch instead of depending on other keyboards.

**Comment by lm41** [comment] 2024-09-05 15:50
Duplicate of #45

**Closed by lm41** 2024-09-05 15:50 UTC
Labels: proposal
