### ISSUE TITLE
App crashed randomly

### ISSUE THREAD

**Issue by paritosh9199** [florisboard/florisboard#1369] opened 2021-10-31 10:42 UTC
#### Environment information
- FlorisBoard Version: 0.3.14-beta05 (61)
- Device: OnePlus LE2101
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1635676847256.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 0 free bytes and 0B until OOM, target footprint 268435456, growth limit 268435456
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1019)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment] 2021-11-01 00:07
Thanks for your issue! This is a well known issue and a duplicate of pinned issue #1268. Closing thus.

**Closed by patrickgold** 2021-11-01 00:07 UTC
Labels: bug
