### ISSUE TITLE
General Gestures not working

### ISSUE THREAD

**Issue by l2eused** [florisboard/florisboard#2605] opened 2024-09-26 15:18 UTC
### Short description

**Settings** > **Gestures & Glide typing** > all options under **General gestures** are not working at all.

### Steps to reproduce

1. under general gestures, try to playarond with some/any options
2. under other gestures / gesture thresholds, adjust some/any options
3. try them

### FlorisBoard Version

0.4.0-rc02

### Install Source

GitHub

### Device

Xiaomi 14

### Android

14 HyperOS

**Comment by tsiflimagas** [comment] 2024-09-28 00:03
This must be a duplicate of #2515. Let's keep the discussion there. In the meantime, maybe you can try playing with swipe velocity and swipe distance thresholds at the bottom of gestures settings and see if this changes anything.

**Closed by tsiflimagas** 2024-09-28 00:03 UTC
Labels: bug
