### ISSUE TITLE
Crash deletes characters

### ISSUE THREAD

**Issue by WikiBayer** [florisboard/florisboard#1078] opened 2021-07-18 09:36 UTC
Sometimes the keyboard deletes characters and does not stop until you restart the keyboard.
I have android 11 (crdroid)

**Comment by Glitchy-Tozier** [comment] 2021-07-18 11:29
Thank you for your bug-report!

Could you please fully fill in the bug-report-template? This would help a lot in fixing your issue.

**Comment by Glitchy-Tozier** [comment] 2021-07-21 08:32
This is a duplicate of bug #986, closing it as such.
Should you have any further information, please mention it there!

**Closed by Glitchy-Tozier** 2021-07-21 08:32 UTC
