### ISSUE TITLE
System navigation bar is not correctly rendered sometimes

### ISSUE THREAD

**Issue by Ansarmughal99** [florisboard/florisboard#2461] opened 2024-04-27 10:26 UTC
### Short description

Sometime the space below the keyboard shows different color look like it is background color which match with homescreen wallpaper. But sometime the color is same as keyboard material color. 
See image attached 
![IMG_20240427_155417](https://github.com/florisboard/florisboard/assets/74392407/5bed110c-88dd-4539-b19f-46afb04b3c97)

### Steps to reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

### FlorisBoard Version

0.4.0 beta 2

### Install Source

GitHub

### Device

realme gt neo 2

### Android

Android 13

**Comment by itsmartashub** [comment] 2024-04-27 12:18
I just wan't to make sure, but I can't conclude 100% from the cropped screenshot. Do you use gestures or navigation buttons for navigation? If you use gestures, is your full-screen indicator shown or hidden? Just so I know which navigation mode to test at least the theme. 
Even the color of the submit button stands out a bit, as if the theme didn't apply properly. Also, have you noticed if this happens immediately after changing the wallpaper, or randomly?

I recently experienced a bug when I switched to a new ROM, where when I changed the wallpaper, the theme wasn't properly applied to Florisboard, and the colors were somehow mixed with the previous theme (from the previous wallpaper). However, I just exited the text field and dismissed the keyboard, then re-entered the typing field to make the keyboard reappear, and the theme applied properly. However, I thought this was a small bug in the new ROM, hm

**Comment by patrickgold** [comment] 2024-04-27 12:39
This bug is actually related to the fact that the system UI helpers of Google Accompanist are not actively maintained anymore and I have to get creative once again fixing the background color. The issue is that the system navigation bar (the bar with the gesture bubble or the classic 3 buttons) is system space but apps have some sort of control over it.

Ofc that doesn't mean there isn't an issue with the internal theme handling too, if colors within the keyboard area are messed up for instance.

**Comment by patrickgold** [comment] 2024-04-27 12:49
Here is a screenshot of the bug occurring, took me some tries to force it (as it often times still works as intended):

![Screenshot_2024-04-27-14-44-37-95_c853220993b0ed55eb2e57645fcd343d](https://github.com/florisboard/florisboard/assets/19412843/cb0ebd14-4da4-4f8b-b85a-a026336017fe)

And another occurrence in Spotify, here you see a very good demonstration that keyboards in Android basically just overdraw the app:

![Screenshot_2024-04-27-14-47-28-87_0438eb925998df20b3482ec25499d226](https://github.com/florisboard/florisboard/assets/19412843/41c3e8a0-057e-4ed3-bb3d-83e869cc5cdd)

**Comment by Ansarmughal99** [comment] 2024-04-27 12:55
Yes I am using gestures on my device. Now this issue  is resolved
automatically.

**Comment by itsmartashub** [comment] 2024-05-28 19:48
> This bug is actually related to the fact that the system UI helpers of Google Accompanist are not actively maintained anymore and I have to get creative once again fixing the background color. The issue is that the system navigation bar (the bar with the gesture bubble or the classic 3 buttons) is system space but apps have some sort of control over it, although it is only partially documented and not the most stable system API...

I get that it’s tough with the Google Accompanist system UI helpers not being maintained anymore. It sounds like a real challenge to come up with creative fixes for the background color issue. Your efforts to sort this out despite those hurdles are really appreciated, Patrick 🥹

> Ofc that doesn't mean there isn't an issue with the internal theme handling too, if colors within the keyboard area are messed up for instance.

I checked the internal theme handling and found a small "issue". When changing the theme while the keyboard is open, some material you colors from the previous wallpaper, mix with the new wallpaper's colors. However, closing and opening the keyboard fixes the issue. So, not a big deal I guess

**Closed** 2024-06-01 10:27 UTC
Labels: bug, area: kbd-ui, bug-confirmed

**Comment by patrickgold** [comment] 2024-06-01 10:34
> I checked the internal theme handling and found a small "issue". When changing the wallpaper while the keyboard is open, some material you colors from the previous wallpaper, mix with the new wallpaper's colors. However, closing and opening the keyboard fixes the issue. So, not a big deal I guess

That's probably an issue with the internals of the Google Material lib, and considering the fact that wallpaper changes rarely happen I think we can say that this small issue is not a big deal in fact.

**Comment by patrickgold** [comment] 2025-01-16 21:59
Just for clarification I can reproduce this bug using Gboard (see screenshot), soo yeah I think we can't do anything about it and this is a system vendor bug :/

![Image](https://github.com/user-attachments/assets/45112446-26cf-44ee-af03-e38b73db2e9a)

**Comment by Ansarmughal99** [comment] 2025-01-17 09:31
@patrickgold @itsmartashub thanks for ur response but  i can tell u I was having the same issue with Heliboard see pic 1 but after the recent update an option is added in appearance as color navigation bar, see pic 2 after this option there is no issue with color in navigation bar see pic 3 . Might this is not a system issue. 
Pic 1:- ![IMG_20250117_145540.jpg](https://github.com/user-attachments/assets/51e647f4-e661-4775-a927-1b8c77a43dea)

Pic 2 :- ![IMG_20250117_145458.jpg](https://github.com/user-attachments/assets/6d6b274b-774b-48e6-96fa-2f65f0f9a555)

Pic 3:- After Navigation bar color is set On ![IMG_20250117_145532.jpg](https://github.com/user-attachments/assets/7339c264-80e7-4a85-9d05-07a97396ebf6)
