### ISSUE TITLE
Add Korean layout please

### ISSUE THREAD

**Issue by Yaurok** [florisboard/florisboard#305] opened 2021-02-02 22:53 UTC
Would love to see a Korean language option, I really like this keyboard and I have Korean friends whom I'm talking to. I'd appreciate were the Korean layout implemented! Thank you very much for this wonderful open source keyboard and looking forwrard to next updates!

**Comment by patrickgold** [comment] 2021-02-02 23:26
Thanks for your suggestion! I will add this to the v0.5.0 milestone when I will add a bunch of non-Latin script keyboard layouts.

**Comment by Yaurok** [comment] 2021-02-05 15:34
Thanks for hearing me out! Good work there 👍

**Comment by patrickgold** [comment] 2021-02-05 16:33
Adding an issue to a milestone != it is already implemented :)

Reopening this issue, as this issue is not yet resolved.

**Comment by puelp** [comment] 2021-02-22 22:33
I would just like to add that Korean uses an alphabet system, and is fully compatible with/utilizes the Latin keyboard layout that we are used to.

It is not like Chinese or Japanese, it doesn't have thousands of characters that need a special way to select them.

**Comment by Yaurok** [comment] 2021-03-23 12:56
I know I'm late to reply but, would that mean Korean layout could be implement sooner? Not putting any pressure of course. But yours is the only keyboard I'm currently using and struggling a lot without Korean, no other open-source option out there sadly. This is the best one I've used so far and while Korean is important to me I can't stop using this! As I said take your time and appreciate your work 👍

**Comment by jangboolee** [comment] 2021-03-31 08:16
Dropping in to say that I'm also looking for a FOSS keyboard that supports Korean input, and Florisboard is the only option that seems remotely promising. As a beginner/intermediate Python programmer, I don't think there's much I can help with the development aspect, but I would be more than happy to do any testing if necessary. 

Thank you for all your hard work with the keyboard.

**Comment by patrickgold** [comment] 2021-03-31 21:43
@jangboolee As long as the Korean language follows some kind of alphabet and which doesn't require special input handling (like with Chinese or Japanese for instance) it is actually easy to add it as a layout json file. Just a heads up though: I am currently implementing subtype specific layouts for all types and with this the syntax of the IME config charges and also the layout meta slightly changes. So it would be best if you create the layout only after the `subtype-specific-layouts` branch is merged in.

**Comment by jangboolee** [comment] 2021-04-03 18:19
> @jangboolee As long as the Korean language follows some kind of alphabet and which doesn't require special input handling (like with Chinese or Japanese for instance) it is actually easy to add it as a layout json file. Just a heads up though: I am currently implementing subtype specific layouts for all types and with this the syntax of the IME config charges and also the layout meta slightly changes. So it would be best if you create the layout only after the `subtype-specific-layouts` branch is merged in.

That's great to hear. As you can see below, the Korean alphabet system has a very easily mappable QWERTY keyboard layout. There is another Korean typing system called Cheonjiin that some people prefer for mobile typing, but that's a 3x4 keyboard that will not be easily added to the existing QWERTY layout, so I think that can come later, if at all. 

![Korean-Keyboard-Idea](https://user-images.githubusercontent.com/11282732/113487560-19582600-94b9-11eb-9f3b-df137e1902fa.png)

But there are some rules for constructing a Korean letter (consonants always come first and one letter can't hold more than two consonants etc) that may complicate things for the input handling, but I will first wait until the branch  merge before doing anything.

**Comment by Hayleia** [comment] 2021-04-15 17:13
I wasn't sure if this issue was the best place to ask or if the other one about the common manager was better, sorry if this is the wrong place.

If this project is going the json route to describe composing rules, would there be a limitation on the json size?
I tried to find all the rules the Korean keyboard would need and I found 72618.
- 11172 of them are `character + character → composed_character`
so for example `ㄱ + ㅏ → 가` or `가 + ㄱ → 각`
- The rest is `syllable_with_composed_final_consonant + vowel → two_syllables`
so for example `갃 + ㅏ → 각사`, or `밡 + ㅓ → 발터`

Maybe not all of the characters in these rules are used in modern Korean (so some rules could be trimmed from the json), or maybe 72618 is entirely manageable in a rule json, or maybe i'm wrong on that number. But if that number is correct, is that an issue?

**Comment by patrickgold** [comment] 2021-04-15 17:57
> 72618

_OutOfMemoryError intensifies_ - No seriously, if the rule files are that big this indeed poses a problem. Less for the JSON part but more for the runtime caching part - as you can see the suggestions are posing a huge problem right now as they are cached in Kotlin/JVM. This would mean that these rulesets have to be parsed and cached natively in C++, requiring a more complex rework of the layout manager part, else the RAM usage will explode.

**Comment by Hayleia** [comment] 2021-04-16 05:50
Well I was expecting news as bad as "impossible" so that's still good news to me.

BTW if people are interested in how I find that number of rules, it's the "hangulrules.py" file here <https://github.com/Hayleia/HangulExperiments> (note that I got rid of a small number of them in the meantime).
It's all theoretical and based on possible Unicode characters, so maybe someone can still walk in and say "in practice, most of these characters are not used" and then rules can be discarded.

(And hangulcompose.py would be the algorithm to edit the string when a new character is typed if it had to be hardcoded for Korean rather than modular with rules, with the obvious drawback of losing modularity.)

**Comment by Yaurok** [comment] 2021-04-30 22:02
So this is looking like it will take a lot of time after all? Well, so much for that initial hype I had... No problem, I'll still use this keyboard as my main as I've been for months now

Just one little question, if it's allowed, could someone suggest me a fair Korean keyboard to use as secondary while I still enjoy this for English? If not, could you please dm me one? Would really appreciate any alternatives while waiting for the big update here (not leaving anytime soon, this is now my favorite keyboard by a long shot, yet again compliments to the dev and contributors!)

**Comment by Hayleia** [comment] 2021-05-01 08:09
If you really want Korean support now, and if you really love florisboard, there is my non-production-ready branch [here](https://github.com/Hayleia/florisboard/releases/tag/v0.3.11-beta01%2Bko).

I say "non-production-ready", not as in "it doesn't work" (you tell me if it works, maybe I messed up syllable composition) but as in "it will never be merged as is in the original florisboard and will not be maintained". It was only me messing around with code, seeing how things (mainly Hangul and Kotlin) worked so as soon as the common manager for composing input methods is ready, I'll be ready too.

(And of course, don't trust a random stranger on the internet. If you can compile it yourself, you can look at the `composing1` branch on my repo rather than use the apk files I shared.)

**Comment by jangboolee** [comment] 2021-05-01 11:05
@Yaurok The keyboard I'm using now for Korean support is SwiftKey. I like it because it has an incognito mode built-in, and if you use it without signing in to a Microsoft account, it should be a moderately private keyboard. But the app does send data to telemetry.api.swiftkey.com, in.appcenter.ms, and bibo.api.swiftkey.com but I block these requests with my system blocker, which helps me with my peace of mind. I would much prefer to use a FOSS keyboard like Florisboard if there was one available, but this was the best solution I could come up with at the moment.

@Hayleia Wow, this is amazing, I'm super happy that we have a working prototype, even if it's just a thought experiment at this stage. I tried it out, and it seems like a great start. I know that you're not going to be maintaining the branch, but if you're interested in feedback - the double consonants don't seem to work. Korean has 5 double consonants that can come at the beginning of a letter (ㄲㄸㅃㅆㅉ), which is usually inputted by pressing their respective keys after pressing shift. But other than this, it still seems to be quite usable, and it gives me a lot of hope for the future of Korean implementation in Florisboard.  Thanks a lot for putting this branch together.

**Comment by Hayleia** [comment] 2021-05-01 11:26
@jangboolee the double consonants are available as long press on my branch, but yeah that would probably make more sense on shift.

**Comment by jangboolee** [comment] 2021-05-02 05:18
> @jangboolee the double consonants are available as long press on my branch, but yeah that would probably make more sense on shift.

Ah, I didn't think of trying long presses. Confirmed! I will definitely be using your branch (already using it actually) as my main keyboard for the forseeable future until it's officially merged somehow & sometime.

**Comment by Yaurok** [comment] 2021-05-03 03:29
@Hayleia Currently using your branch and I must say I commend your effort into this! I'm so glad someone tried to make a temporary solution for us Korean typing users!

That said, maybe I'm doing it wrong but looks like consonants + vowels don't get attached and you get something like this "ㅅㅏㄹㅏㅇ", while the letters are indeed right that basically doesn't make any sense in Korean typing because they need to form a complete syllable to form a word, so the correct form would be: "사랑"

I'm not versed into programming at all (let alone Android/apps etc.) so I don't know how hard or if it possible with the current state of Florisboard to fix this, but as of now the apk with the Korean subtype you shared can't be functional in a Korean talking context because letters do need to get attached to form a sensate word and so phrase, it's different from the latin one

In any case, I appreciate the hard work! And please let me know if it possible to achieve with how the keyboard is now operating (I'm far from knowledgeable to all this the programming world so... sorry for my ignorance if I missed something or said anything wrong! I would be happy to help any way I can though as a normal user)

**Comment by jangboolee** [comment] 2021-05-03 04:33
@Yaurok Which apk version are you using? I have no issues using the _app-release.apk_ version on my device. I'm not sure if your issue is a device or apk-version specific issue, but it works for my device (Samsung Galaxy Note9 running iodéOS) with the _app-release.apk_ version.

**Comment by Hayleia** [comment] 2021-05-03 05:59
It works on my end too, and I'm also using the app-release one, not sure why that would make a difference.
Galaxy Note 3 on Havoc 2.9.
https://user-images.githubusercontent.com/7904776/116845150-53663600-abe5-11eb-8bac-c477c921f693.mp4

**Comment by Yaurok** [comment] 2021-05-03 10:42
I see, it was indeed my own issue... I'm on the same apk as you (release) on a Redmi Note 9 Pro (codename: miatoll); running Android 11, Arrow OS last updated 2021-04-23

**Comment by Hayleia** [comment] 2021-05-03 17:35
Ah nice, thanks for the information. It seems like when suggestions are enabled, the code goes into another branch of commitText (isComposingEnabled is true) so my composing code isn't called.
I just fixed it (well that branch got a little dirtier, I'll really need to make a clean branch and pretend that one never existed at some point), I'll make a release with the fix ASAP. It will be based on the latest commits of the main florisboard though so glide typing (for other languages) doesn't work among other things. If any of you use glide typing, I can make a branch based on the previous release.

**Closed** 2021-05-24 13:30 UTC
Labels: area: kbd-layout, proposal, proposal-accepted

**Comment by Hayleia** [comment] 2021-05-26 12:03
Just in case for people who haven't been following closely (and who didn't see it mentioned in the release notes because it is not mentioned), the release v0.3.13-beta02 supports Korean input 🎉

**Comment by jangboolee** [comment] 2021-05-27 07:47
> Just in case for people who haven't been following closely (and who didn't see it mentioned in the release notes because it is not mentioned), the release v0.3.13-beta02 supports Korean input 🎉

Absolutely amazing!!! Thank you so much for your work on this, @Hayleia!

**Comment by Jirafey** [comment] 2022-04-05 18:45
Korean keyboard, I seem to not be able to form  ㅚ ㅘ ㅟ ㅢ ㅟ ㅘ ㅝ ㅞ
