### ISSUE TITLE
Emoji suggestions

### ISSUE THREAD

**Issue by thedjdoorn** [florisboard/florisboard#1229] opened 2021-09-05 19:41 UTC
Hi, I'm a new (formerly SwiftKey) user, and there are some features in SwiftKey that I had grown really used to that I'd also like to see in Florisboard

One of those is emoji predictions. When you start typing the description for an emoji, it could suggest said emoji. For instance: when I type 'laug', it should suggest 😂[1].

Of course this should be an optional feature, toggleable in the settings

We could implement this by using the CLDR short descriptions [https://unicode.org/emoji/charts/full-emoji-list.html](used in the official Emoji list), but that might not make sense to most users. We might have to look into a different resource for keyword/emoji lists

[1]: This is kind of a bad example, since the CLDR short name for this emoji is 'face with tears of joy', but SwiftKey had this behavior and it saved me tons of time 🤷

**Comment by Fidgetcetera** [comment] 2021-09-19 19:33
A configurable key to always start searching for emoji (anysoftkeyboard let you do this with :, which is also common in many apps for emoji shortcodes) would be a nice addition to this, if it were added.

(ie, start typing ":heart" and the suggestions are only heart emoji)

**Comment by MXC48** [comment] 2021-09-19 19:41
> Hi, I'm a new (formerly SwiftKey) user, and there are some features in SwiftKey that I had grown really used to that I'd also like to see in Florisboard
> 
> One of those is emoji predictions. When you start typing the description for an emoji, it could suggest said emoji. For instance: when I type 'laug', it should suggest 😂[1].
> 
> Of course this should be an optional feature, toggleable in the settings
> 
> We could implement this by using the CLDR short descriptions [https://unicode.org/emoji/charts/full-emoji-list.html](used in the official Emoji list), but that might not make sense to most users. We might have to look into a different resource for keyword/emoji lists
> 
> [1]: This is kind of a bad example, since the CLDR short name for this emoji is 'face with tears of joy', but SwiftKey had this behavior and it saved me tons of time 🤷

I am a former user of "emojis keyboard" of Xiaomi I was also well accustomed to this function and gesture input at the same time but since I am French it is not yet implemented for my language

**Comment by thedjdoorn** [comment] 2021-12-06 14:20
I found a good resource for emoji keywords:
https://github.com/muan/emojilib

**Comment by jeremiah-miller** [comment] 2022-02-08 22:01
Looks like this is a duplicate of https://github.com/florisboard/florisboard/issues/56

**Comment by tsiflimagas** [comment] 2022-02-20 16:31
Thank you for your well made proposal! As @jeremiah-miller correctly pointed out, this is already tracked at #56, so let's keep the conversation about it there.

**Closed by tsiflimagas** 2022-02-20 16:31 UTC
Labels: proposal
