### ISSUE TITLE
Vietnamese keyboard

### ISSUE THREAD

**Issue by GitDerpian** [florisboard/florisboard#1987] opened 2022-07-31 13:17 UTC
#### Description
When you press space and type a new word, instead of putting the word next to the whitespace, FlorisBoard replaces the whitespace with the first letter of the word and then put in the rest of the word, resulting in a sentence with no spaces.

#### Example
Input: This is an example.

Expected output: This is an example.

Actual output: Thisisanexample.

#### Steps to reproduce
1. Add "Tiếng Việt (Việt Nam)" (Vietnamese) keyboard language/subtype.
2. Switch to Vietnamese keyboard.
3. Type a sentence.
4. See error.

#### Environment information
- FlorisBoard Version: 0.4.0-alpha01 (87)
- Install Source: F-Droid
- Device: Samsung Galaxy A02s
- Android: 11 (stock)

**Comment by patrickgold** [comment] 2022-08-01 11:08
Thanks for your bug report!

This is an indirect duplicate of #1947 (all languages with special composers had a conflict with the auto-space issue). Your issue should be fixed with #1949, and using the latest master state Vietnamese works fine again. This will be released in 0.4.0-aplha02 in a few days.

**Closed** 2022-08-01 11:08 UTC
Labels: bug, duplicate, area: kbd-logic
