### ISSUE TITLE
Emoji Search

### ISSUE THREAD

**Issue by RealFakeGitter** [florisboard/florisboard#2402] opened 2024-02-29 20:14 UTC
### Feature idea

Pretty self explanatory would be awesome if i can type in a word and get an emoji (as you can in gboard, yandex, and somewhat anysoft with the ":" 
Example 
Type: smile
See : 🙂

**Comment by lm41** [comment] 2024-02-29 20:32
duplicate of https://github.com/florisboard/florisboard/issues/45

**Closed** 2024-02-29 20:33 UTC
Labels: proposal
