### ISSUE TITLE
space bar swipe up activates caps-lock instead of shift

### ISSUE THREAD

**Issue by pierstitus** [florisboard/florisboard#627] opened 2021-04-12 15:24 UTC
If shift is selected as space bar swipe up action, Caps-lock is activated instead when swiping up.

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: F-Droid
- Device: Samsung S5
- Android version, ROM: LineageOS

**Comment by patrickgold** [comment] 2021-04-12 15:52
Thanks for your bug report! Just tried it out on my phone and was fully able to reproduce it. Will push a fix for it soon.

**Comment by patrickgold** [comment] 2021-04-12 16:50
Above PR fixes the caps lock instead of shift issue, the bug occurred because the space bar up gesture was triggered multiple times and this caused the input logic to think that caps should be activated. Will be released in v0.3.11-beta01.

**Closed** 2021-04-12 17:01 UTC
Labels: bug, bug-confirmed
