### ISSUE TITLE
Bug in candiate suggestions: String "test" is appended to input

### ISSUE THREAD

**Issue by formula-spectre** [florisboard/florisboard#24] opened 2020-10-19 20:51 UTC
**Environment information**
- FlorisBoard Version: 0.2.0
- Install Source: F-Droid
- Device: Samsung Galaxy A50 
- Android version, ROM: Stock, 10

**Actual problem**: the candidate suggestion is bugged: when i'm not typing i have the stock "candidate" "suggestions" "nyi", but when i type a word, it becomes that word with "test" appended. If i click that, it writes out the word with "test" appended", and if i re-touch it, it appends another "test" to it, becoming like this:
Wordtesttesttest
**Steps to reproduce:**
I.. actually don't know, sorry. I just recall that "test" was the first thing i wrote with this keyboard.  
Thanks for the patience.

**Comment by patrickgold** [comment] 2020-10-19 21:16
Actually that's not a bug but an feature which is currently missing. The term `nyi` means _not yet implemented_ (hence "candidate" "suggestions" "nyi"). As a test I let the string "test" appended to the user input to see if the word detection itself works (this was written back when I wrote the rough construct for Smartbar, but was since then never really touched. Candidate suggestions with a proper dictionary behind are planned to be implemented with version v0.4.0 or v0.5.0.

**Comment by patrickgold** [comment] 2020-10-26 15:28
Just changed the title so it is clearer and better prevents duplicates of the same issue.

**Comment by patrickgold** [comment] 2021-01-20 22:08
Closing this issue as the NYI badge is now better implemented and test is now not appended anymore.

**Closed by patrickgold** 2021-01-20 22:08 UTC
