### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jmft138** [florisboard/florisboard#735] opened 2021-04-22 16:12 UTC
~~~ 1619107580993.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 4648 byte allocation with 1035680 free bytes and 1011KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 36175872 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.concurrent.CopyOnWriteArrayList.add(CopyOnWriteArrayList.java:430)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.addEventListener(FlorisBoard.kt:812)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyView.onAttachedToWindow(EmojiKeyView.kt:73)
	at android.view.View.dispatchAttachedToWindow(View.java:22010)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
	at android.view.ViewGroup.addView(ViewGroup.java:5884)
	at android.widget.ViewAnimator.addView(ViewAnimator.java:193)
	at android.view.ViewGroup.addView(ViewGroup.java:5824)
	at android.view.ViewGroup.addView(ViewGroup.java:5796)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayout$2$1.invokeSuspend(EmojiKeyboardView.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by GenosseFlosse** [comment] 2021-04-22 16:15
Can you provide some context? Steps to reproduce, what you did to cause the OOM, Android version, app version and device?

And have you searched the open issues for OOM errors? Does #677 contain your Problem?

**Comment by Glitchy-Tozier** [comment] 2021-04-22 18:01
Ty @GenosseFlosse (netter Name :smile:) for suggesting good practices in issue-creation!

Yeah, if it's a duplicate of #677. I'll close it to keep the list of issues clean!

**Closed by Glitchy-Tozier** 2021-04-22 18:01 UTC
