### ISSUE TITLE
OOM crash when typing on url bar

### ISSUE THREAD

**Issue by castrik** [florisboard/florisboard#1209] opened 2021-08-29 21:30 UTC
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to 'web browser'
2. Type anything in url bar
3. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-G960F
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1630272233846.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 624688 free bytes and 610KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 93323264 bytes)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:125)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:134)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1630272233854.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 22424 free bytes and 21KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 49545216 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3136)
	at java.util.Arrays.copyOf(Arrays.java:3106)
	at java.util.ArrayList.grow(ArrayList.java:275)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
	at java.util.ArrayList.add(ArrayList.java:467)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:141)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1630272233861.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 59408 free bytes and 58KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 93323264 bytes)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.<init>(temp_suggestion_code.kt:188)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

<details>
<summary>1630272233853.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 2187024 free bytes and 2135KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 103546880 bytes)
	at android.os.VibrationEffect.createOneShot(VibrationEffect.java:177)
	at dev.patrickgold.florisboard.ime.keyboard.InputFeedbackManager.performHapticFeedback(InputFeedbackManager.kt:135)
	at dev.patrickgold.florisboard.ime.keyboard.InputFeedbackManager.keyPress(InputFeedbackManager.kt:49)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onTouchDownInternal(TextKeyboardView.kt:450)
	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardView.onTouchEventInternal(TextKeyboardView.kt:309)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView$1.invokeSuspend(KeyboardView.kt:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:479)
	at kotlinx.coroutines.channels.AbstractChannel$ReceiveHasNext.completeResumeReceive(AbstractChannel.kt:940)
	at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:84)
	at kotlinx.coroutines.channels.AbstractSendChannel.offer(AbstractChannel.kt:141)
	at kotlinx.coroutines.channels.ChannelsKt__ChannelsKt.sendBlocking(Channels.kt:21)
	at kotlinx.coroutines.channels.ChannelsKt.sendBlocking(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardView.onTouchEvent(KeyboardView.kt:83)
	at android.view.View.dispatchTouchEvent(View.java:14368)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3857)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:770)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1156)
	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:177)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:728)
	at android.view.View.dispatchPointerEvent(View.java:14636)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6579)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6357)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5968)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6025)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5846)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5812)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5820)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5793)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9029)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8886)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8839)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9166)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

**Comment by castrik** [comment] 2021-08-29 21:32
happened quite a lot, also it only happens in a url bar of web browser(I'm using bromite), doesn't happen anywhere else

**Comment by Glitchy-Tozier** [comment] 2021-08-30 06:12
Hi and thank you for taking the time to write this bug-report. :)

A few questions:

1. Which browser do you use?
1. Do word-suggestions show up in this URL-bar?
1. If there are other apps where you type a lot, do word-suggestions show up in those?
1. If you disable word-suggestions, does this crash still occur in the browser?

**Comment by patrickgold** [comment] 2021-08-30 09:59
Thanks for your bug report! I just tried to see if Bromite has any abnormalities and it behaves the same as other apps, so I do not see a reason why FlorisBoard only OOM crashes in Bromite.

Could you please try to disable suggestions and see if the crash is then gone?

**Comment by castrik** [comment] 2021-08-30 18:48
1. I'm using bromite
2. yes, they do show up(the keyboard crashed after I typed a few letters and I don't remember if suggestions showed up, but they do now
3. It only crashed in the browser url bar, not even in duckduckgo's search area

I've restarted my phone and it is stable for now
if it happens again, I'll let you know

**Comment by castrik** [comment] 2021-08-31 11:45
got it once again!
same thing, bromite url bar, if it make it more specific, I was using incognito mode in both cases

**Comment by patrickgold** [comment] 2021-08-31 15:37
Yeah the thing is OOM errors occur as soon as the Java heap is completely full, then any allocation will lead to this crash. It would be best as you stated to keep suggestions off and see if this crash disappears, if it does then you probably have to live without suggestions until 0.3.15.

**Comment by tsiflimagas** [comment] 2022-03-19 12:03
@patrickgold Is there anything different here, or should it be closed as another OOM error caused by current suggestions mechanism?

**Comment by patrickgold** [comment] 2022-03-19 12:06
OOM issues occur in the old word suggestions and also one spot in the glide logic (although the glide typing logic only rarely produces this). Both are connected to suggestions though and thus until 0.4.0 I think all OOM issues should be closed, because these duplicates don't help at all.

**Closed** 2022-03-19 12:09 UTC
Labels: bug, needs more info, area: word-prediction
