### ISSUE TITLE
Bug after enabling/disabling the dark mode

### ISSUE THREAD

**Issue by singhh9596** [florisboard/florisboard#1466] opened 2021-12-23 04:45 UTC
#description
Keyboard is acting weird after I enabled-disabled the system's dark mode. (Check the recording).

#### Steps to reproduce
1. Turn on-off system's dark mode
2. Open keyboard
3. Type anything

#### Environment information
- FlorisBoard Version: 0.3.14.beta 7
- Install Source: Google PlayStore
- Device: redmi k20 pro (Raphael)
- Android: 11 (Custom - ShapeShiftOS)
[Drive link - screenRecord](https://drive.google.com/file/d/1Nag1eytH9Dwn00fs6AqxysvDU_8Bx1HG/view?usp=drivesdk)

**Comment by patrickgold** [comment] 2021-12-23 17:56
Thanks for your bug report! This is a known issue and caused by a Xiaomi shenanigan, where the system tries to be smarter than it is and forces dark mode on apps, although FlorisBoard already has an inbuilt dark mode. FlorisBoard does not support system dark mode forcing and thus the colors clash horribly.

One workaround is to go to the system settings > Display > More dark mode options there should be a list of apps to separately toggle dark mode, there disable dark mode for FlorisBoard. This will allow for the correct dark colors to show.

It is possible to block the system from doing such shenanigans for an app automatically (without user action in system settings), and a possible fix for this will be included in beta08. If you want you can try out the debug build from https://github.com/florisboard/florisboard/pull/1440/checks to test if my patch is actually working (I do not own a device which behaves this way so I cannot test this out).

**Closed** 2022-02-06 22:29 UTC
Labels: bug
