### ISSUE TITLE
[FR]: Don't automatically insert whitespace after special characters (optional)

### ISSUE THREAD

**Issue by just-Nob** [florisboard/florisboard#806] opened 2021-05-04 13:50 UTC
#### Motivation
When typing any word after a special character like brackets or quotation marks (i.e. ', ", (, ), /, + etc.), a whitespace automatically is inserted between the special character and the following word.
Third sometimes is very annoying.

#### Feature Description
I'ld like to have an option in the settings to disable the automated insertion behind special characters.

**Comment by Glitchy-Tozier** [comment] 2021-05-04 14:28
Is this normal typing or glide typing?
Also, what version of Florisboard are you using?

**Comment by just-Nob** [comment] 2021-05-04 19:53
Sorry, you're right, my description was a bit poor.

This is only if the following word is entered by glide typing, using v0.3.10 from F-Droid repo.

**Comment by Glitchy-Tozier** [comment] 2021-05-05 05:47
In that case, this issue is a duplicate of #596.

Apparetly there already have been some improvements in #625, but i'm not sure how much was done.

**Comment by Glitchy-Tozier** [comment] 2021-05-06 07:14
I'll close this issue as a duplicate, If you have any further ideas, check out #596.

**Closed by Glitchy-Tozier** 2021-05-06 07:14 UTC
