### ISSUE TITLE
keyboard not disappeared

### ISSUE THREAD

**Issue by heberjeur** [florisboard/florisboard#716] opened 2021-04-20 10:15 UTC
#### Short description
Describe the bug in a short but concise way.
When I search for something and then I click to "ok" search bottom,the normal reaction that the keyboard hide.

#### Steps to reproduce
1. Go to the browser
2. Click and write something
3. Click to the green bottom for searching
4. Click and write another things
4. See that the keyboard was not disapeared

#### Environment information
- FlorisBoard Version: 0.3.10 and the others
- Install Source:/GitHub/
- Device: samsung a 50
- Android: 11
(Sorry for my bad english)

https://user-images.githubusercontent.com/11852634/115378919-59195000-a1d1-11eb-842d-ac27c7a4550b.mp4

**Comment by Glitchy-Tozier** [comment] 2021-04-20 11:01
This sometimes happens to me, aswell.

Not sure how to consistently reproduce it or whether it's a Florisboard-issue (as opposed to an Android-issue).

**Comment by heberjeur** [comment] 2021-04-20 11:14
It happens only on google search, not for an other search engine 
maybe it's google search issue

**Comment by Glitchy-Tozier** [comment] 2021-04-20 16:53
On any specific browser or in the Google-app?

**Comment by heberjeur** [comment] 2021-04-21 13:16
I use firefox(I don't know others), it happens when I browse google.com and not on image search

**Comment by patrickgold** [comment] 2021-04-24 01:43
Thanks for your bug report! This weird behavior is a mix of Android's keyboard state bug (as other keyboards tend to completely randomly stay on screen too, bug it happens very rarely) and a FlorisBoard one. The input view shown evaluation is currently near to the default, it can definitely be possible that I need to cover some edge cases. Will place this one on my todo list.

**Comment by patrickgold** [comment] 2021-05-08 13:46
@heberjeur I just released beta05, which fixes an infinite loop bug in the key sizing logic. This could have potentially lead to your described bug. If possible, could you try out the latest beta05 if this problem has been resolved for you? Thanks in advance!

**Comment by heberjeur** [comment] 2021-05-09 03:11
@patrickgold I tested the beta05 and it's ok,thanks

**Comment by patrickgold** [comment] 2021-05-09 10:07
Perfect! As your issue seems to be fixed, I will close this issue. Should it still exist, feel free to reopen this issue!

**Closed by patrickgold** 2021-05-09 10:07 UTC
Labels: bug, needs investigation
