### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by palitu** [florisboard/florisboard#1004] opened 2021-06-07 00:45 UTC
I was adding text into firefox when it crashed. 

~~~ 1622072162218.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 1336 byte allocation with 638680 free bytes and 623KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 74448896 bytes)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invokeSuspend(EmojiKeyboardView.kt:160)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayoutForCategory$2.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView.buildLayoutForCategory(EmojiKeyboardView.kt:149)
	at dev.patrickgold.florisboard.ime.media.emoji.EmojiKeyboardView$buildLayout$2.invokeSuspend(EmojiKeyboardView.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
~~~ 1622090182686.stacktrace ~~~

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.clip.provider.FileStorage.cloneURI(FileStorage.kt:42)
	at dev.patrickgold.florisboard.ime.clip.provider.FlorisContentProvider.insert(FlorisContentProvider.kt:77)
	at android.content.ContentProvider.insert(ContentProvider.java:1714)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:336)
	at android.content.ContentResolver.insert(ContentResolver.java:2152)
	at android.content.ContentResolver.insert(ContentResolver.java:2114)
	at dev.patrickgold.florisboard.ime.clip.provider.ClipboardItem$Companion.fromClipData(FlorisDatabase.kt:123)
	at dev.patrickgold.florisboard.ime.clip.FlorisClipboardManager.onPrimaryClipChanged(FlorisClipboardManager.kt:214)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:285)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:79)
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
~~~ 1622556795436.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 51768 free bytes and 50KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 30146560 bytes)
	at java.lang.CaseMapper.toUpperCase(CaseMapper.java:173)
	at java.lang.String.toUpperCase(String.java:2742)
	at dev.patrickgold.florisboard.ime.text.key.KeyHintMode$Companion.fromString(KeyHintMode.kt:32)
	at dev.patrickgold.florisboard.ime.core.PrefHelper$Keyboard.getHintedSymbolsMode(PrefHelper.kt:377)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:186)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onSubtypeChanged$1.invokeSuspend(TextInputManager.kt:340)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
~~~ 1623026622876.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 786464 free bytes and 768KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 40108032 bytes)
	at java.lang.String.fastSubstring(Native Method)
	at java.lang.String.substring(String.java:2069)
	at org.json.JSONTokener.nextToInternal(JSONTokener.java:348)
	at org.json.JSONTokener.readLiteral(JSONTokener.java:289)
	at org.json.JSONTokener.nextValue(JSONTokener.java:115)
	at org.json.JSONTokener.readObject(JSONTokener.java:394)
	at org.json.JSONTokener.nextValue(JSONTokener.java:104)
	at org.json.JSONObject.<init>(JSONObject.java:165)
	at org.json.JSONObject.<init>(JSONObject.java:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$setWordData$1.invokeSuspend(GlideTypingManager.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by patrickgold** [comment] 2021-06-07 01:10
Could you please specify what FlorisBoard version and Android device/version you are on? Thanks in advance!

**Comment by Glitchy-Tozier** [comment] 2021-06-15 13:36
This probably can be closed as a duplicate of #677.

**Comment by palitu** [comment] 2021-06-15 14:27
Yep!

Galaxy S20, android 11, floris board 3.12 i think, i dont think i have
updated it since the crash.

**Comment by Glitchy-Tozier** [comment] 2021-06-15 14:33
Do you remember whether you edited the crash log? Because that is the old crash-log, which only existed up until 0.3.10.

**Comment by palitu** [comment] 2021-06-15 23:22
i did not edit it.  It must be an earlier verion then.

**Comment by Glitchy-Tozier** [comment] 2021-06-16 07:28
Seems that way. For now, let's close this issue to keep the list clean. Should this happen again (this time we'll be certain it's post-0.3.10), please post your log in #677.  :)

**Closed by Glitchy-Tozier** 2021-06-16 07:28 UTC
