### ISSUE TITLE
Domains get extracted from copied emails

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1971] opened 2022-07-26 13:37 UTC
#### Short description
When copying an email or a text containing an email, the paste-shortcuts suggest both the email itself, as well as the email-provider's domain.

![Screenshot_20220726-153306_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/181019036-439f84f1-df37-4a3d-871d-2d067f5178d3.jpg)

#### Steps to reproduce
Copy this text:
```
example@email.com
```
or this text
```
Lorem ipsum example@email.com asdf jklgg.
```

#### Environment information
- FlorisBoard Version: 0.4.0-alpha01 (87)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment] 2022-07-26 13:42
As discussed, this is indeed a bug caused by the fact that email addresses and URLs are checked independently, will add this to the list of clipboard issues.

**Comment by Glitchy-Tozier** [comment] 2022-07-26 17:24
It might also be interesting to add detection for phone-numbers, but I'm not sure how reliably this can be achieved.

**Comment by Glitchy-Tozier** [comment] 2022-07-26 19:27
Also, there might still be room for imrovement in URL-detection.
I don't think there are single-letter-top-level-domains or domains starting with a period.
![Screenshot_20220726-211954_GitHub.jpg](https://user-images.githubusercontent.com/59611881/181095081-1d44de1f-e60a-429f-8f7f-e4b792cd662d.jpg)

**Comment by patrickgold** [comment] 2022-07-26 22:10
As for the URLs: I agree, seems to be a regex issue, will look into it tomorrow.

As for the phone numbers: I played around a bit and created this regex draft with examples: https://regexr.com/6qjfg  
What would you think, would this detection rate be enough? You can freely type your own phone number examples in the box and see if it would match, if you find that something doesn't match even if it should (or the other way around too), please tell me and I can try to adjust my regex. Once we have agreed on what regex to use I can add it to the code.

<details>
<summary>Screenshot of state as of now for reference</summary>

![image](https://user-images.githubusercontent.com/19412843/181120822-1253874a-80ab-4c94-8bab-10a7c81823b5.png)

</details>

**Comment by Glitchy-Tozier** [comment] 2022-07-27 05:43
> As for the phone numbers

Amazing, you've done a great job! Two tiny things possibly worth thinking about:
1. I noticed 3-digit numbers aren't accepted (think many emergency hotlines such as 911)... Adding this to the regex may result in tons of false positives though, so I'm not sure this does more good than harm.
2. I suggest adding a length-cap to prevent some false positives. See [here](https://stackoverflow.com/questions/723587/whats-the-longest-possible-worldwide-phone-number-i-should-consider-in-sql-varc).
![Screenshot_20220727-073830_Firefox Klar.jpg](https://user-images.githubusercontent.com/59611881/181170074-ec76781d-2c3e-406d-87ad-1ea1c30f6c3b.jpg)

**Comment by patrickgold** [comment] 2022-07-27 10:35
> I noticed 3-digit numbers aren't accepted (think many emergency hotlines such as 911)... Adding this to the regex may result in tons of false positives though, so I'm not sure this does more good than harm.

The only thing I could do is to build the regex dynamically and query the SIM card for all active emergency numbers that it knows. But still Android itself does not detect 911 or say 112 as phone numbers in plain texts, so I think we shouldn't consider these either for the sake of keeping false positives down.

> I suggest adding a length-cap to prevent some false positives. [More info](https://stackoverflow.com/questions/723587/whats-the-longest-possible-worldwide-phone-number-i-should-consider-in-sql-varc).

You are right, I added a length cap. Additionally I completely reworked my regex, so it now also supports the US format of 1-800-CALLNOW (letters in phone number) and to better support parentheses. Could you please try out some numbers again to see if this is now sufficient?

**Comment by Glitchy-Tozier** [comment] 2022-07-27 10:47
> Android itself does not detect 911 or say 112 as phone numbers in plain texts, so I think we shouldn't consider these either for the sake of keeping false positives down.

Sure thing!

> it now also supports the US format of 1-800-CALLNOW

That's pretty impressive!

> Could you please try out some numbers again (use the same link as above) to see if this is now sufficient?

Seems pretty good!
The only thing I don't quite understand ia why the parenthesises also are highlighted in numbers like the following:
![20220727_124325.jpg](https://user-images.githubusercontent.com/59611881/181229074-1b42be2d-c5e3-4887-bee8-b2952189dd81.jpg)

**Comment by patrickgold** [comment] 2022-07-27 10:51
> The only thing I don't quite understand ia why the parenthesises also are highlighted in numbers like the following:

That's where my regex skills are not advanced enough yet, I am currently sitting and thinking how I can distinguish surrounding parentheses from phone number parentheses:

Please call (123) 456789 vs (123 456789) - the problem is that the opening parentheses can either belong to the area code or be the surrounder, so I dunno how to fix this

**Comment by patrickgold** [comment] 2022-07-27 11:48
Above linked PR adds the phone number detection as discussed. The parentheses issue still persists but I don't see a good fix for it and it isn't that common that a phone number is in parentheses so I think it will stay this way (except someone has an idea how to adjust the regex so surrounding parentheses are cut out reliably)

**Comment by patrickgold** [comment] 2022-07-27 11:59
Above commit fixes the domain issue, I now ensure matches are unique and cannot be reused, so once an email address was matched the corresponding URL match which overlaps is ignored.

**Comment by Glitchy-Tozier** [comment] 2022-07-27 12:56
> That's where my regex skills are not advanced enough yet, I am currently sitting and thinking how I can distinguish surrounding parentheses from phone number parentheses

Unfortunately, my regex skills are close to none, so I'm not sure what to do.
Maybe sone manual adjusting might help, in the sense that

1. We receive part of the regex-selected text
2. In Kotlin, we manually check whether the string starts with `(` and ends with `)`
3. If it does, we grab a substring, from index 1 to length-2

> Above commit fixes the domain issue, I now ensure matches are unique and cannot be reused, so once an email address was matched the corresponding URL match which overlaps is ignored.

Good job! Does that mean there also won't be any duplicate entries (as seen [here](https://github.com/florisboard/florisboard/issues/1971#issuecomment-1195891236))

**Comment by patrickgold** [comment] 2022-07-27 14:28
> We receive part of the regex-selected text In Kotlin, we manually check whether the string starts with ( and ends with ) If it does, we grab a substring, from index 1 to length-2

That's actually a very smart idea I must say, I didn't quite think out-of-the-box on this one. Thanks for the inspiration! While I would still prefer a regex-only solution to this problem I will use your substring idea for now, as for the user the problem is not apparent anymore.

> Good job! Does that mean there also won't be any duplicate entries (as seen https://github.com/florisboard/florisboard/issues/1971#issuecomment-1195891236)

Ahh sh*t nope this isn't prevented yet, currently it only prevents duplicate matches based on the string indices and character position. Will push a commit later on to address this.

**Comment by Glitchy-Tozier** [comment] 2022-07-27 14:35
> While I would still prefer a regex-only solution to this problem I will use your substring idea for now

I agree that my idea is somewhat messy, but it might do the job, for now.

> Ahh sh*t nope this isn't prevented yet, currently it only prevents duplicate matches based on the string indices and character position. Will push a commit later on to address this.

👍🏻
I never explicitly mentioned this issue, no worries :)

**Comment by KLaurence** [comment] 2022-07-27 14:40
Can area codes contain spaces? If not, is it possible to modify the regex to match the text (numbers) inside the parentheses only if the text doesn't contain a space?

**Comment by patrickgold** [comment] 2022-07-27 14:43
> Can area codes contain spaces? If not, is it possible to modify the regex to match the text (numbers) inside the parentheses only if the text doesn't contain a space?

Phone numbers can be formatted in so many ways I am sure my regex is only covering half of them and I am waiting for my users to report formats that don't work. Currently I am anticipating spaces, dots, dashes and parentheses to be inside a phone number and at random places too, this is one reason why the regex is so long.

**Comment by Glitchy-Tozier** [comment] 2022-07-27 14:54
One last reminder, in case this flew under the radar: As mentioned in [this comment](https://github.com/florisboard/florisboard/issues/1971#issuecomment-1195891236), if I'm correct about top-level domains consisting of AT LEAST 2 characters, we could add this condition to URL-recognition.

**Comment by patrickgold** [comment] 2022-07-27 15:10
So my above three commits I just added fix:
- Phone numbers which are in parentheses now don't have parentheses when extracted using Glitchy's idea. If I find a solution to do this directly in the regex then I will change this, else it will stay like now
- Extracted URLs are now additionally checked if they are not already extracted at another position, so if a copied item has the same URL twice it will only appear once
- Domains with only a single character as the TLD will now not be seen as a valid domain anymore. (Worked on this before you commented but still thanks for the reminder Glitchy!)
- If you write a domain like ".example.com" then it will be extracted as "example.com" (without quotes of course)

I think we now should have fixed every mentioned issue in this thread, or did I forget something?

**Comment by Glitchy-Tozier** [comment] 2022-07-27 15:19
> Phone numbers which are in parentheses now don't have parentheses when extracted using Glitchy's idea. If I find a solution to do this directly in the regex then I will change this, else it will stay like now

The relevant search-term might be "regex look-ahead", but my knowledge on that whole subject is fairly limited.

> - Extracted URLs are now additionally checked if they are not already extracted at another position, so if a copied item has the same URL twice it will only appear once
> - Domains with only a single character as the TLD will now not be seen as a valid domain anymore. (Worked on this before you commented but still thanks for the reminder Glitchy!)

Nice job!

> If you write a domain like ".example.com" then it will be extracted as "example.com" (without quotes of course)

Initially, I thought ".example.com" should not be categorized as an URL, at all.
I don't have any good arguments for why, though. What was the reason you chose to categorize `.{url}` as `{url}`?


> I think we now should have fixed every mentioned issue in this thread

I think so, too. Close the issue whenever you're ready!  :)

**Comment by patrickgold** [comment] 2022-07-27 15:30
> The relevant search-term might be "regex look-ahead", but my knowledge on that whole subject is fairly limited.

I actually use the negative ones of that group family to prevent long numbers getting detected as 2 separate ones. I have thought of using a positive look-ahead but can't wrap my head around how the look-ahead can look "over" the phone number to see if there is a parentheses after the number.

> I don't have any good arguments for why, though. What was the reason you chose to categorize .{url} as {url}?

Because that's how Android also seem to handle a dot before a domain, so I inherited this behavior. I could add a negative look-behind, but I am not sure on that one.

> I think so, too. Close the issue whenever you're ready! :)

Issue is attached to linked PR, so once I merge the branch in this will auto-close :)

**Comment by patrickgold** [comment] 2022-07-27 18:46
I think for now I will let the .{url} as {url} categorization as is. Should it really pose a problem in the future it is a straightforward fix by adding `(?<!\.)` before the host expression.

I will now merge in the changes and release them in some days in 0.4.0-alpha02. Thanks everyone for the feedback!

**Closed** 2022-07-27 18:47 UTC
Labels: bug, bug-confirmed, area: clipboard
