### ISSUE TITLE
Swiping on the "backspace" button does not work in some applications.

### ISSUE THREAD

**Issue by snooppr** [florisboard/florisboard#2325] opened 2023-11-10 05:31 UTC
The "backspace" button's swipe action is configured to quickly select and delete text, but this does not work in popular applications such as: Termux;  Acode.

https://github-production-user-asset-6210df.s3.amazonaws.com/61022210/281965692-5ed37e80-cf12-4cce-9861-3ee08f487fe0.mp4

The video shows that swiping on the "backspace" button works in the "**QiuckEdit**" application and selects/deletes a range of characters.  Then the same operation in the "**Acode**" editor, but it doesn't work, and then the same operation in "**Termux**" doesn't work.  

Please note that in all these applications, swiping on the "space" button to move the cursor works.

OS: Android LOS16 (android 9)
FlorisBoard v0.3.15 (f-droid).

**Comment by unilock** [comment] 2023-12-24 18:00
This is likely a duplicate of #1854.

**Closed** 2023-12-28 04:43 UTC
Labels: bug
