### ISSUE TITLE
Add Bangla Language Google Layout 

### ISSUE THREAD

**Issue by mehedi2580** [florisboard/florisboard#2353] opened 2023-12-28 20:21 UTC
Add Bangla Language Google Layout 
![Screenshot_20231229-022100_Chrome](https://github.com/florisboard/florisboard/assets/39218757/33737d70-ecb2-46cd-91b3-5776363fda2d)

**Comment by Tarek-Hasan** [comment] 2024-01-03 06:31
Duplicate of #1885

**Closed** 2024-01-11 23:46 UTC
Labels: duplicate, proposal

**Comment by mehedi2580** [comment] 2024-01-12 05:46
why you close this proposal ? still this keyboard dont have google bangla layout.

**Comment by patrickgold** [comment] 2024-01-12 07:49
Because it is a duplicate of the linked issue.
