### ISSUE TITLE
 Allow typing in different languages simultaneously

### ISSUE THREAD

**Issue by loxoron218** [florisboard/florisboard#2512] opened 2024-07-22 15:35 UTC
### Feature idea

Would it be possible for the app to allow users to type in different languages simultaneously? Back when I used more proprietary software on my phone, I remember the default Android keyboard that shipped with my phone allowing me to type in up to three different languages and auto-correct/spell-check my words simultaneously.

I grew up speaking two languages **(Spanish and Catalan)** and I also need **English** to browser the internet. Moreover, as a foreigner living in a country that requieres me to use another language that isn't my native one **(German)** makes me use up to four languages almost daily.

As far as I remember, the keyboard I used back then was the official Android keyboard that Google ships with their system by default and looked like this:
![351001037-8a1de659-8d8b-4646-bbf0-f1b2bfc0b98c](https://github.com/user-attachments/assets/8e80c9af-6904-4a7d-8eee-0bbe0958ff89)

Heliboard solves this issue by allowing to add different languages to a certain keyboard. You can see here they called it multilingual typing:
<img src="https://github.com/user-attachments/assets/470b0d50-e581-47af-a0cc-75f9fe035c11" width=50% height=50%>

**Comment by loucasal** [comment] 2024-11-02 11:36
Duplicate of #155, this can be closed.

**Comment by tsiflimagas** [comment] 2024-11-02 14:06
Thanks for pointing out, let's keep the discussion in the original issue.

**Closed by tsiflimagas** 2024-11-02 14:06 UTC
Labels: proposal
