### ISSUE TITLE
Glide to type always is substituted with another character

### ISSUE THREAD

**Issue by thebiblelover7** [florisboard/florisboard#747] opened 2021-04-24 03:22 UTC
#### Short description
Glide to type always turns out to be a `Q` or `q` or nothing at all.

#### Steps to reproduce
Check above and below.

https://user-images.githubusercontent.com/61815862/115919594-b9361d80-a481-11eb-917f-528091b40ff6.mp4

#### Environment information
- FlorisBoard Version: v0.3.10
- Install Source: F-droid
- Device: Samsung S20 Snapdragon
- Android: 11, One UI 3

**Comment by adrielsand** [comment] 2021-04-24 03:25
This is now solved by restarting FlorisBoard but it might be useful to keep it open.

If you think I should close this, let me know.

**Comment by Glitchy-Tozier** [comment] 2021-04-24 05:56
I love this, it's really funny!  xD
@X-yl you might be interested in this.

**Comment by adrielsand** [comment] 2021-04-24 07:10
it's funny but not when it's happening to you. anyway, now I have the same problem but now it doesn't show anything at all.

Look below:

https://user-images.githubusercontent.com/61815862/115950639-24fda200-a4e5-11eb-9ddd-90659fe6d014.mp4

**Comment by Glitchy-Tozier** [comment] 2021-04-24 13:43
> anyway, now I have the same problem but now it doesn't show anything at all.

Does that output normal words? Space? Nothing?

**Comment by adrielsand** [comment] 2021-04-24 17:15
> > anyway, now I have the same problem but now it doesn't show anything at all.
> 
> Does that output normal words? Space? Nothing?

Nothing at all

**Comment by adrielsand** [comment] 2021-04-25 03:28
Now it works normally just that it might not work again soon.

**Comment by Glitchy-Tozier** [comment] 2021-04-25 13:49
If you find a way to consistently reproduce this issue, make sure to post it here!

**Comment by X-yl** [comment] 2021-04-25 19:51
Hmm seems like probably something is getting messed up and doesn't set the layout data, which would result in all the coordinates being (0,0) which is closest to q. Probably a similar (or the same?) issue causes the keyboard to think glide typing is not ready which makes it not output anything.

Please do share if you find a way to reproduce, these things are always really tricky to track down.

**Comment by Lurux** [comment] 2021-04-25 22:23
Restarting the app fixes it ? Maybe related to #677 then ?

**Comment by adrielsand** [comment] 2021-04-26 03:16
> Hmm seems like probably something is getting messed up and doesn't set the layout data, which would result in all the coordinates being (0,0) which is closest to q. Probably a similar (or the same?) issue causes the keyboard to think glide typing is not ready which makes it not output anything.

I was thinking that it could be something like that.

**Comment by adrielsand** [comment] 2021-04-26 03:20
> Restarting the app fixes it ?

Yes it does.

> Maybe related to #677 then ?

Maybe it could be, but I don't know how it would relate to what @X-yl said.

**Comment by patrickgold** [comment] 2022-05-15 13:10
Is this bug report still occurring in 0.3.16-beta02? A lot has changed and been fixed since then, so unsure if this is still relevant.

**Comment by thebiblelover7** [comment] 2022-05-15 15:50
@patrickgold Haven't been using the beta, and I can't reproduce on `0.3.15 (80)` so I doubt it is there anymore.

**Comment by patrickgold** [comment] 2022-05-15 16:18
Okay, thanks for confirming. Will close this issue then.

**Closed by patrickgold** 2022-05-15 16:18 UTC
Labels: bug, area: glide-typing
