### ISSUE TITLE
Repeating input

### ISSUE THREAD

**Issue by yant0** [florisboard/florisboard#986] opened 2021-06-02 17:30 UTC
#### Short description
Clicked once, repeated until pressed again. Is this a new feature? 

#### Steps to reproduce
1. Type things for a while
2. Catch the bug occur

#### Environment information
- FlorisBoard Version: 0.3.13 beta-3
- Install Source: Fdroid
- Device: Asus Zenfone Max pro m1
- Android: 9 stock

**Comment by zer0fl0w** [comment] 2021-06-02 21:55
confirmed here. same issue.

**Comment by Glitchy-Tozier** [comment] 2021-06-03 10:22
Gould you specify? What happens? Do some buttons rapid-fire when you hold them?

**Comment by patrickgold** [comment] 2021-06-03 10:47
> Clicked once, repeated until pressed again. Is this a new feature?

Nope, that's definitely a bug, one which I am absolutely not able to reproduce though.

Now as you opened an issue for this, could you specify:
- for which keys this happens (only delete, arrow etc.) or all keys like letters numbers etc.
- does this bug occur consistently
- does it happen with a single fast tap or only when holding down a key longer

Thanks in advance for answering these points, this would help me much in finding the culprit for this nasty bug!

**Comment by yant0** [comment] 2021-06-03 11:16
i think the bug is only with delete and arrow keys.
I was writing text and used delete and arrow keys multiple times and i see the bug 5-7 times when writing. I also find this bug right after updating beta and typing on search app.
Bug happened with fast tap, not sure if it can be replicated with long tap.

**Comment by zer0fl0w** [comment] 2021-06-04 09:41
can confirm. it is mainly the back/delete key. 
you misstype something in inputfields, want to delete the last character(s) quick and away goes everything you've just written until you fast enough press again deletekey but it not stops everytime on first try.

also i often have to doubleclick to get numbers row and shift / unshift. sometimes it does not go back after capital and stays locked in capital without really being locked in caps.

oh man, i hope what i just wrote makes sense and is understandable.

**Comment by Glitchy-Tozier** [comment] 2021-06-04 10:02
@zer0fl0w So you click on the delete key **once** and it just keeps deleting?

**Comment by zer0fl0w** [comment] 2021-06-04 14:13
sometimes (rare), but in most situations it happens after pressing 2 or more times. i eventually pause between first and following clicks/taps, like slow and not doubleclick, but it randomly still fires the constant backspace.

i also have the feeling that it is sometimes app-dependend.
i.e. in termux i always have the doubletap enter to send a cmd. it is weird.

it often feels like the settings in windows where you can set if you want to open links/folders with single- or doubleclick.

at least for shift, numberkey and enter.

**Comment by teemue** [comment] 2021-06-12 12:34
I can confirm this, I have noticed it happening on delete-key. Really annoying.

**Comment by teemue** [comment] 2021-07-18 12:55
I've noticed that this happens often in the web browser, when web site is loading and at the same time i'm typing  a new address. Also on other situations where the OS/CPU seems to be processing something.

**Comment by rex07** [comment] 2021-07-19 17:23
Same here is a video
https://user-images.githubusercontent.com/13156001/126200918-537eef6f-e961-4c58-81e3-f197239567b3.mp4

**Comment by rex07** [comment] 2021-07-19 17:27
Some times the delete button got stuck
Even if you type any letter it delete it instantly

**Comment by teemue** [comment] 2021-07-20 08:59
> Same here is a video
> https://user-images.githubusercontent.com/13156001/126200918-537eef6f-e961-4c58-81e3-f197239567b3.mp4

That shows exactly what happens. For me, It seems to hang sometimes even after one click of backspace button. Could this be related to the overall performance of the device (I have pretty old Nokia 5.1) @patrickgold  ?

**Comment by josephbadow** [comment] 2021-07-29 17:13
Just wanted to +1 this on the backspace key to delete text. In my case it happens when I hold the key to delete two or three words. Then it will delete a few more than it should and it actually feels as if there is some kind of lag. Like when you have a CPU heavy task running and confirm a dialog and it takes a couple of seconds until the confirmation is recognized by the system.

**Comment by Glitchy-Tozier** [comment] 2021-07-29 17:19
@josephbadow If you're using version v0.3.12 (the newest non-beta version), your problem may be connected to #883.

**Comment by josephbadow** [comment] 2021-07-29 18:23
> @josephbadow If you're using version v0.3.12 (the newest non-beta version), your problem may be connected to #883.

Dang, looks like I didn't search properly 🙈 #883 looks a lot more related to my issue. Thanks for the heads up.

**Comment by jeremiah-miller** [comment] 2021-08-06 06:24
Just wanted to chime in and say I'm getting the same issue with the delete key. Usually happens if I'm alternating between swyping and tapping to tap and need to delete something, but it seems pretty random

**Comment by GoRaN909** [comment] 2021-08-06 19:43
This bug is happen when you typing fast and when you tap on the Delete button at the end of a paragraph i think that appears after version 3.10 and newer versions till now.

**Comment by ElishaAz** [comment] 2021-08-12 11:09
I managed to actively reproduce this error on my device:
- Get a very large file (I used "2mb text file" from https://www.learningcontainer.com/sample-text-file/# )
- Open it in a text editor (I used [TEdit](https://github.com/ATryder/TEdit) )
- Insert a few letters
- Hit backspace
- The keyboard doesn't stop deleting.

It looks like the 'key up' for the backspace key is not getting registered when a lot of resources are being used.
Maybe because of the backspace key's gesture support?

**Comment by patrickgold** [comment] 2021-08-12 13:01
@ElishaAz Thanks for your comment I got a few ideas how to reproduce the bug and I am finally able to reproduce it :)

So it seems that this bug is dependent how busy FlorisBoard is and how much your device CPU can handle at once. Because of this I cannot reproduce the bug on my physical OnePlus 7T, even not for 10MB text files.

The good thing is I also have access to other physical devices, which are a lot weaker. The first one I tried was the Samsung Galaxy A20e - and bingo it worked (and lagged a lot with the 2 MB text!). I reproduced this in the Samsung Notes app, where I pasted 100kB of data 20 times, so the app you use isn't that much important. For me it is most consistently reproducible when quickly double-tapping delete in text fields with a lot of data.

As I can now finally reproduce the bug (at least for one option), I can start go debugging and fixing the bug.

**Comment by patrickgold** [comment] 2021-08-12 13:16
Ok after some quick debugging it seems the keyboard logic eats the second `UP` event of `KeyCode.DELETE` for lunch, thus the delete key technically stays down in the input dispatcher and is repeated. Very strange why this is happening though, probably a non-thread-safe access to the current pressed state. Will further investigate.

**Comment by patrickgold** [comment] 2021-08-12 13:37
Above PR is a draft fix for the repeating input bug. It would be very helpful for me if some of you could install the debug artifact of the PR to check if the bug has been fixed (the debug version installs separately and won't affect your main installation). On my Samsung device I wasn't able to reproduce the bug anymore, but this alone is not enough to validate if this bug has been fixed. Thanks in advance!

**Comment by rex07** [comment] 2021-08-12 18:37
It's fine now if i found it happening again i will let you know.

**Comment by GoRaN909** [comment] 2021-08-12 19:35
I think the bug was fixed in the latest debug apk now im using it the repeating is not happened till now.

Thanks

**Closed** 2021-08-13 18:04 UTC
Labels: bug, bug-confirmed, area: kbd-logic

**Comment by patrickgold** [comment] 2021-08-13 18:06
I've merged #1147 into master. The fix for the repeating input will thus be in the beta09 release, which will be published either tomorrow or on Sunday. Thanks all for reporting and helping out to fix this bug!
