### ISSUE TITLE
Keystrokes not registering

### ISSUE THREAD

**Issue by StefanTraistaru** [florisboard/florisboard#953] opened 2021-05-28 12:48 UTC
#### Short description
When hitting 2 keys fast, the first one is not typed. The phone vibrates 2 times, the key pop-up appears for both of the keys, but only the second key appears to have been registered. Now I have to type way slower or just redo words altogether because some letters are missing.

#### Steps to reproduce
1. Go to: I managed to reproduce this bug in all text fields I could find.
2. Click on: 2 sepperate keys really fast, one after the other.
4. See error: only the second letter appears

#### Environment information
- FlorisBoard Version: v.0.3.13-beta02
- Install Source: F-Droid
- Device: OnePlus 7T
- Android: 11, Stock

https://user-images.githubusercontent.com/23136219/119986066-161a7b80-bfcc-11eb-9be8-84f494fe1d61.mp4

**Comment by f1reflyyyylmao** [comment] 2021-05-28 13:05
Can confirm the issue, I've got the same behaviour

**Comment by patrickgold** [comment] 2021-05-29 18:35
Can confirm, this is an issue confirmed and will be fixed in the next beta! As I think you are the first to make an issue for this on GitHub I will use your issue to keep track of this.

**Comment by mf5y** [comment] 2021-05-30 01:18
Can reproduce this issue 100%: if a key is not fully released by the time the next key is pressed, it isn't input

**Comment by pokegamer5547** [comment] 2021-05-30 02:17
I noticed this issue too last tine when i used beta build, it's working fine now since i moved to stable build.

**Closed** 2021-05-31 15:52 UTC
Labels: area: kbd-logic, bug, bug-confirmed
