### ISSUE TITLE
Side Offset, Reorganizing keys, Clip-items multi-select, New keys

### ISSUE THREAD

**Issue by w0nd3r365** [florisboard/florisboard#2241] opened 2023-06-16 02:46 UTC
#### Environment information
- FlorisBoard Version: 0.4.0-alpha04 (90)
- Install Source: F-Droid
- Device: Samsung Galaxy Tab A7 (10.4 inch screen)
- Android: 11

#### Feature requests
- Ability to reorganize positions of keys and symbols. Makes switching to this keyboard easier as someone may be more familiar with a specific orientation of symbols.
- Implement side offset, similar to bottom offset for landscape view in devices with large screens like tablets.

__*side offset in samsung keyboard*__

![image](https://github.com/florisboard/florisboard/assets/97921087/b3ed9aab-05c5-4fe6-9786-cb2976b50425)

The side offset should help give keys a proportional shape when decreasing vertical height of keyboard, so that they wouldn't look stretched out horizontally.

__*no side offset in FlorisBoard-Beta keyboard*__

![image](https://github.com/florisboard/florisboard/assets/97921087/6453f2f3-4b30-4b42-a677-4cfb6b44065c)

- A delete key in addition to the backspace key. More key types if possible, like SHIFT, CTRL, TAB, ESC, function keys, etc.
-  Fill the keys without symbols, like `>`,  `` ` ``, `_`, `[`, etc before nesting similar symbols under one key. 
- Ability to multi-select clipboard items, for batch deletion and pinning
- When long-clicking arrow keys to change cursor position, don't show popup of their description.

Thank you for this great app, one of the best keyboards I've used. More options please, for customizability is key, 'cause people have different preferences and devices.

**Comment by Glitchy-Tozier** [comment] 2023-06-17 08:01
Hi there, thank you for your feature request.

Please stick to one requested feature per issue. I can see that this requires additional effort on your end and that many of your proposals have similar aims, however, this structure makes discussing and implementing your proposals much more difficult.
Please create a separate issue for each of those bullet points.

As for the bullet points themselves:
> Ability to reorganize positions of keys and symbols. Makes switching to this keyboard easier as someone may be more familiar with a specific orientation of symbols.

I'm not quite sure what you mean. Are you talking about the smartbar-actions? If so, they can already be reordered.

> A delete key in addition to the backspace key. More key types if possible, like SHIFT, CTRL, TAB, ESC, function keys, etc.

Duplicate of #962.

> Ability to multi-select clipboard items, for batch deletion and pinning

Love that suggestion. Please create a separate issue for it so we can tag it properly. :)

> When long-clicking arrow keys to change cursor position, don't show popup of their description.

Duplicate of #2095.


> Fill the keys without symbols, like `>`, `` ` ``, `_`, `[`, etc before nesting similar symbols under one key.

As far as I know, the symbol-layout aims to be similar to Gboard's layout. Therefore, there probably won't be any big changes to symbols and their positions. You can still create a issue for that request and see what Patrick thinks.

**Closed as completed** 2023-06-17 19:42 UTC
Labels: proposal
