### ISSUE TITLE
Colour of keys turned white on floris_day theme

### ISSUE THREAD

**Issue by FabiRich** [florisboard/florisboard#1779] opened 2022-04-11 22:23 UTC
#### Short description
The colour (black) of the keys of the keyboard turns sometimes white with the floris_day theme. I had this issue in version 0.3.14 in the settings app and the keyboard of florisboard. I tested it now with the new release 0.3.15 and I could not reproduce it in the keyboard which is good, but in the settings app it still switch after a few seconds of typing.

I could fix this with tapping on the utility key. Maybe it is already fixed with the new release, but it could probably reappear.
![screenshot1](https://user-images.githubusercontent.com/76914324/162842419-bde61a9f-4851-48ef-9d56-1f5d37d2d5f1.jpeg)

![screenshot2](https://user-images.githubusercontent.com/76914324/162842458-fcfebf92-2028-492c-a54e-f9874c366d02.jpeg)

https://user-images.githubusercontent.com/76914324/162842480-386384c4-cdb0-4bb0-91d4-b2e4e717eb8d.mp4

It does not happen with the floris_night theme. Can anybody reproduce it and did anybody faced this issue too?

#### Steps to reproduce
1. It switched after a few minutes.

#### Environment information
- FlorisBoard Version: 0.3.14 (not reproducible in 0.3.15)
- Install Source: F-Droid (for 0.3.15 from Github release page
- Device:  Poco F1
- Android: 10 MIUI 12

**Comment by tsiflimagas** [comment] 2022-04-11 22:44
I think this is a duplicate of #1694. As stated in 0.3.15 changelog, this issue is fixed, and since you can't reproduce it either, I'll consider this a reassurance. In case you encounter this issue again, feel free to reopen this issue.

**Closed by tsiflimagas** 2022-04-11 22:44 UTC
Labels: bug

**Comment by FabiRich** [comment] 2022-04-11 22:50
Thank you
