### ISSUE TITLE
Auto-Space after dot 

### ISSUE THREAD

**Issue by CuvlBoi** [florisboard/florisboard#1202] opened 2021-08-28 20:22 UTC
A simple option for auto-space after dot, comma, question mark...
And it should drag periods left
Example:
When the sun goes down , i will go to sleep. (there is space between 'down' and comma) 
When the sun goes down, i will... (there is no space between down and comma)

And suggestions for common English short forms like isn't, haven't, I'd...

I really appreciated the app, and hopefully will be able to help improve the app.

**Comment by heinhuiz** [comment] 2021-11-12 19:10
When typing numbers or currencies however, no space should be included, like in 100,000 or €45.00.

**Comment by patrickgold** [comment] 2022-07-05 23:39
Duplicate of #375, closing thus. Auto-spacing will be released as a preview tomorrow in 0.4.0-alpha1, see #1935 for more details.

**Closed by patrickgold** 2022-07-05 23:39 UTC
Labels: proposal
