### ISSUE TITLE
Paste does not work in GitJournal

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#412] opened 2021-03-02 06:56 UTC
#### Short Description

GitJournal is a wonderful Markdown app and FlorisBoard comes very handy to assist with the syntax and text editing. 
Unfortunately, one of the main keys - paste - does not work. 

#### Steps to reproduce
1. Start GitJournal
2. Create any type of entry (note, task list, journal) 
3. Copy and paste some text with FlorisBoard, either with the toolbar or the clipboard keyboard 
4. Select and copy work but not paste

#### Environment information
- FlorisBoard Version: 0.3.7
- Install Source: F-Droid
- Device: Xiaomi Mi 9T
- Android version, ROM: 10, LineageOS 17.1

**Comment by patrickgold** [comment] 2021-03-02 08:21
Thanks for your bug report! I've just tested out the FlorisBoard clipboard functionality with GitJournal was able to reproduce the bug. Will have to investigate why this occurs in the first place. As other keyboards works flawlessly with GitJournal, I highly suspect that the bug is within FlorisBoard.

**Comment by MisterY** [comment] 2021-03-02 08:33
Thank you! Just to reiterate here, as well - with 0.3.8 and the word suggestions on, the whole copy/paste smartbar never shows and the keyboard is always in word suggestion mode. Perhaps this adds some useful info.

**Comment by patrickgold** [comment] 2021-03-03 22:12
I am currently rewriting the selection logic and have discovered that the bug is NOT within FlroisBoard, but within GitJournal (partly at least). If you try Hacker's keyboard and use any normally supported selection/clipboard related shortcuts of Android, GitJournal will just ignore them. This is also the reason why FlorisBoard fails to properly send commands to GitJournal. Gboard does some magic and it mostly still works (except for jump to start/end of line, it always goes to the end of the textfield), just don't know what they are doing to get it running.

**Comment by MisterY** [comment] 2021-03-03 23:54
OK. Report there, as well. Perhaps we get more information.

SwiftKey only supports the Paste option (keeps the copied items for an hour) and that seems to work fine, at least. I think I'll be using that as a workaround.

**Comment by patrickgold** [comment] 2021-03-08 00:27
#444 completely reworks the input logic of FlorisBoard. While the performance and stability of the logic has improved on most apps, the issue with GitJournal has worsened and the app now refuses to update the UI correctly for cursor movements and delete actions (but executes the actions correctly in the background). Clipboard commands are completely ignored by GitJournal. I am unsure how I can fix this one, if I find a way I will let you know!

**Comment by tsiflimagas** [comment] 2022-09-06 11:26
Is this also fixed by #1844? I just tried the app and it seems to be working fine, but I thought to ask for a little confirmation.

**Comment by tsiflimagas** [comment] 2022-09-13 00:15
I guess my test is sufficient.

**Closed by tsiflimagas** 2022-09-13 00:15 UTC
Labels: bug, bug-confirmed, needs investigation, area: clipboard
