### ISSUE TITLE
Numbers popup appear below autofilling service

### ISSUE THREAD

**Issue by iStagnant** [florisboard/florisboard#2323] opened 2023-11-07 21:54 UTC
#### Short description
When in a password filed, and you have a system autofill button in the smartbar, the number's popup will appear below the autofill button, while normally they should be above it. (See recording below)
https://github.com/florisboard/florisboard/assets/82290573/d904ed51-d96a-41aa-af6d-0a76f73e300e

#### Steps to reproduce
1. Have system autofill sugestions on
2. Click on a password field
3. Click on the first few numbers to the left
4. The number's popup will appear below the autofill button

#### Environment information
- FlorisBoard Version: 0.4.0-alpha04 (90)
- Install Source: F-Droid(IzzyOnDroid repo)
- Device: Pixel 2 XL
- Android: 11

**Comment by patrickgold** [comment] 2024-04-21 11:44
Duplicate of #1228

**Closed by patrickgold** 2024-04-21 11:44 UTC
Labels: bug
