### ISSUE TITLE
Add other options when swiping up and down

### ISSUE THREAD

**Issue by romain030992** [florisboard/florisboard#1882] opened 2022-05-29 07:27 UTC
Hi, 

I found out about your project because I was looking for a new keyboard to replace Fleksy. I used fleksy for about 7-8 years now but I wanted to have something lighter. I found nothing on Play Store so I decided to check on github. I'm very happy about this keyboard, it's an amazing work !! 

A feature that I very like about your keyboard is to be able to set up some actions when swiping up and down! Do you think it would be possible to implement a Fleksy like feature for these swipes ? The feature is the following :
- Let's say you want to write "Hello"
- Instead you type "Gellp"
- Then you swipe right for adding a space. 
- You should be able to change the mispelled word by swiping down. Even go through different proposition.
What do you think ?

**Comment by patrickgold** [comment] 2022-05-29 10:32
Glad you like FlorisBoard!

As for your feature proposal, this requires Word suggestions/Inline spell checking, which will be implemented in the next major dev cycle 0.4.0 after the 0.3.16 release. If you are interested in the development of that, make sure to be on the beta channel to get the intermediate 0.4.0-alpha and 0.4.0-beta releases, because it will take some time until the stable 0.4.0 release is done.

> You should be able to change the mispelled word by swiping down. Even go through different proposition.

How exactly does this work? Is there a small popup with possible words you could have meant?

The current plan for 0.4.0 is that while you write word suggestions based on your input appear in the Smartbar (the row above the keyboard layout). So for instance if you type "gellp", it would make suggestions such as "hello", "help", "hell", which you can then press on one of those words to replace it with your misspelled input. If the suggestion algorithm is sure that you definitely meant "hello", then this word is marked bold and you just have to press space (or set up a swipe right action to insert a space) and "gellp" will be automatically replaced by "hello".

**Comment by romain030992** [comment] 2022-05-29 10:41
hello, yes I forgot to mention that word suggestion would be a prerequisites for this kind of feature. I'm on the beta channel 😉

Regarding how it works, it is quite complex to explain but easy to understand, you can download Fleksy and everything is explained in the tutorial. Basically instead of anticipating the word you are typing, it is more about correct the word you just typed. So you have to type all the letters, then several propositions are available depending on the keys you stroke. As I said, not easy to explain (even more difficult for a french guy 🤣)

**Comment by patrickgold** [comment] 2022-05-29 11:01
> it is more about correct the word you just typed. So you have to type all the letters, then several propositions are available depending on the keys you stroke.

That's what FlorisBoard would also do. Provide 2 suggestions and 1 autocorrect by default, inserting space applying the autocorrect automatically. However I just tried out Flesky and the swipe down didn't do something special for me, so I could not figure out if there's something more to that gesture in Flesky.

**Comment by romain030992** [comment] 2022-05-29 14:02
You have to swipe down after having inserted a space (or swipe right). Basically it's for going through several autocorrect proposition or cancel the autocorrect if you really meant to write what you wrote.

**Comment by romain030992** [comment] 2022-05-30 05:39
I just went through some opened issues/feature requests and it is a duplicate of this one finally https://github.com/florisboard/florisboard/issues?page=4&q=is%3Aissue+is%3Aopen

**Comment by yashpalgoyal1304** [comment] 2022-06-03 17:37
@romain030992 which one?? u did not mention the issue number or issue title

**Comment by romain030992** [comment] 2022-06-04 15:55
Oups sorry I thought I mentionned it : https://github.com/florisboard/florisboard/issues/1480

**Comment by yashpalgoyal1304** [comment] 2022-06-04 17:20
hey so, this issue can be closed as a duplicate right??

**Comment by romain030992** [comment] 2022-06-04 18:29
I think so. Maybe it could be useful to add some relevant information to the previous post.

**Comment by yashpalgoyal1304** [comment] 2022-06-05 04:57
so, what are u waiting for in closing this issue 😅😅😂. FYI: the author of
issue (here, thats u) can also close the issue, it doesnt necessarily have
to be the admin

**Comment by yashpalgoyal1304** [comment] 2022-10-11 07:40
so, what are u waiting for in closing this issue 😅😅😂. FYI: the author of
issue (here, thats u) can also close the issue, it doesnt necessarily have
to be the admin

romain030992 wrote:

> I think so. Maybe it could be useful to add some relevant information to
> the previous post.
>

**Closed** 2022-10-11 12:37 UTC
Labels: needs more info, proposal, area: word-prediction

**Comment by yashpalgoyal1304** [comment] 2022-10-11 15:27
i dont remember sending any reply email 8 hours ago?!

why is github showing so?

**Comment by KLaurence** [comment] 2022-10-12 02:08
It's possibly an accidentally-sent duplicate by your email provider.

**Comment by yashpalgoyal1304** [comment] 2022-10-16 15:39
hey @KLaurence 

> It's possibly an accidentally-sent duplicate by your email provider.

it really seems to be a github side bug, see the other similar comments - which i am sure i did not send in recent time of 5 days, i posted these quite long time ago:


* https://github.com/florisboard/florisboard/issues/1882#issuecomment-1274881164
* https://github.com/mkulesh/microMathematics/issues/112#issuecomment-1274212650
* https://github.com/JuliaPlots/Plots.jl/issues/4311#issuecomment-1274364015
* https://github.com/geany/geany/issues/3146#issuecomment-1274237581

**Comment by KLaurence** [comment] 2022-10-17 02:12
I'm sadly not sure how to determine the root cause. I'd say it is likely related to email in one way or another as your accidental issue comments were all sent via email, but I'm short of ideas on verifying whether it is GitHub or your email provider's issue.
