### ISSUE TITLE
Auto Capitalization doesn't work on some apps

### ISSUE THREAD

**Issue by 0xd64393** [florisboard/florisboard#1861] opened 2022-05-20 15:43 UTC
#### Short description
Auto capitalization doesn't work in some apps but it does work on others like Instagram 

#### Steps to reproduce
1. Go to browser (I used bromite here)
2. Click on search bar, you'll notice that keyboard is not capitalized even tho Auto Capitalization is on
Notice: if you typed a letter and then deleted it the keyboard will be capitalized
4. Try writing an Instagram message and you notice the keyboard is capitalized 

#### Environment information
- FlorisBoard Version: 0.3.16-beta-03
- Install Source: Github
- Device: Samsung Galaxy J6+
- Android: OneUI 10

**Comment by patrickgold** [comment] 2022-05-21 10:12
Auto-capitalization only applies if the app also wants it. For the browser example you brought it makes sense that auto-capitalization does nothing, because the browser URL/search bar is a hybrid and it would be super annoying if you type a URL with auto-capitalization enabled. So this issue itself is not a bug.

I am aware though that the auto-capitalization in the latest beta has issues when hiding/opening the keyboard repeatedly in an input field. As there's no tracking issue for that it seems, I will use this issue for keeping track of this until it is fixed.

**Comment by patrickgold** [comment] 2022-05-27 16:56
Above PR should be a fix for auto-capitalization not behaving correctly. Will be released in 0.3.16-beta04. Thanks for reporting!

**Closed** 2022-05-29 11:01 UTC
Labels: bug, bug-confirmed, area: kbd-logic
