### ISSUE TITLE
[0.3.10] florisboard appears and stuck after switching keyboard

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#732] opened 2021-04-22 09:31 UTC
Sometimes keyboard starts to lag and after switching to hackers keyboard and finishing typing, florisboard appears and needs to be force closed.

![](https://i.imgur.com/QvO8vOB.jpg)
![](https://i.imgur.com/0czX7hg.jpg) 

**Environment information** 
- FlorisBoard Version: 0.3.10
- Install Source: Github
- Device: Mix 2S
- Android: 10, LineageOS

**Comment by Glitchy-Tozier** [comment] 2021-04-22 11:43
Hi, thank you for your report!

Could you please fill out the template, especially the environment information?

**Comment by rancidfrog** [comment] 2021-04-22 16:11
Is there a logcat command to filter dev.patrickgold.florisboard logs from terminal?

**Comment by patrickgold** [comment] 2021-04-24 01:39
Thanks for your bug report! Could definitely be related to #677, could in theory be tied to the rotating bug and to the layout recompute memory bug (the latter is completely fixed in the draft PR #734, which will be the beta02 release once finished).

> Is there a logcat command to filter dev.patrickgold.florisboard logs from terminal?

Wait did FlorisBoard log to the Logcat terminal in the beta and release versions (at least in v0.310)? If so that's a big oopsie from my side. Since v0.3.11-beta01 I am slowly adapting my custom debug utility, I will have to inspect if it happens with it too or if it is fixed. And to answer your question: In Android Studio you can apply filters either by using the dropdown in the logcat tab and selecting FlorisBoard or by specifying a filter term in the input text box. For other Logcat viewer tools I don't know, sorry.

**Comment by rancidfrog** [comment] 2021-04-24 07:12
I am not sure, in regards to the logs.
I wanted to check logs if it occured again, using specific filters instead of seaping through all the log.

**Comment by patrickgold** [comment] 2021-04-24 11:03
If it works like it should and you search the Logcat log when using a beta or stable release you shouldn't even see a log line. This is intended that way because debug logging is even worse for performance, so filtering for non-existent messages won't return something :)

**Comment by Kreuger** [comment] 2021-04-30 01:41
This is definitely related to #677 , as thar was what happened to me when I submitted my bug report before it was merged in.

**Comment by patrickgold** [comment] 2021-05-09 14:54
Today evening v0.3.11 (stable track) will release, containing a lot of fixes for the layout logic, memory management and fixes for crashes etc. Could you give me feedback if by fixing these things your issue has gotten worse, better or the same? Thanks in advance!

**Comment by rancidfrog** [comment] 2021-05-15 13:18
I switched to hackerskeyboard for a while, due to the oom bug causing lags, which may have caused phone to lock up and forced restart every once in a while.

However, I am using v0.3.12 now and will let you know if I come across any issues.

Thank you for the great work.

Just wondering, where does the OOM memory issue come from?
As, I never came across so obvious lags from an app before, which is weird.
 Where you able to locate the culprit?
I am intrigued to know what causes all these memory leaks

**Comment by patrickgold** [comment] 2021-05-15 18:07
> Just wondering, where does the OOM memory issue come from?

Mainly because I didn't really think about the fact that Java's heap memory size is pretty limited (in regards tom the native memory, which has a lot less strict limit and allows to store stuff so much more efficiently). For normal apps most of the time this is ok - as you just display text, icons, maybe images (but Android takes care of loading them natively for you automatically), you never really think about the heap size limit and you never even come close to that limit. For FlorisBoard, I then started implementing the suggestions thing and well - this was the tip on the iceberg of an already not-so-optimized UI structure (emojis and the keyboard view especially). Since then I learned a lot how Java and Android works internally, I am caching more stuff (to reduce the possibility for creating a leak upon rotating, where the UI has to re-build itself), I have flattened the UI to reduce the measurement cycles and unnecessary memory usage / key view, emojis are now partially cached and dynamically loaded, etc.

You don't really see this in other apps, even keyboards, because these issues either have been avoided from the start or have since been reworked and resolved. If I knew more about Java/Android in April 2020 I would have done so too but one can only learn from experience. FlorisBoard is alpha/early-beta + my first project which requires this much resources to be loaded at once - thus yeah things weren't that optimized from the start. v0.3.13 will be the next step though in improving things and a lot of cool stuff is to come (this time with memory limits in mind haha).

**Comment by rancidfrog** [comment] 2021-05-15 19:07
Interesting.
At least it helps you understand how things work in depth.
Keep up the good work.
Florisboard is already great, and it can only get better

**Comment by patrickgold** [comment] 2021-05-23 17:05
@rancidfrog  Is this issue now resolved or does FlorisBoard still get stuck sometimes?

**Comment by Kreuger** [comment] 2021-05-24 01:07
It happened again to me recently but I cant remember which of the 3 keyboards it happened with  🤣

**Comment by tsiflimagas** [comment] 2021-05-24 14:31
Sorry for writing here, as it seems like not totally the right place, but I thought I saw some conversation about key shadows performance regression, and I can't find it.
After this [commit](https://github.com/florisboard/florisboard/commit/94f5b56b6a0ae129c66c59f47224efd22c2e43fa) glide typing animation has become laggy, and there's a big latency between typing and text being actually input. Also it seems that shadows are indeed pretty costly. Running _top -d 1 -p $(pgrep version 0.3.13-debug)_ and typing keys randomly, cpu usage is at about 30% which is approximately double than what the latest beta draws.

**Comment by patrickgold** [comment] 2021-05-24 16:29
>  After this commit glide typing animation has become laggy, and there's a big latency between typing and text being actually input. Also it seems that shadows are indeed pretty costly. Running top -d 1 -p $(pgrep version 0.3.13-debug) and typing keys randomly, cpu usage is at about 30% which is approximately double than what the latest beta draws.

I think this happens because I am for absolutely unknown reasons unable to get the native shadow to render, the shadow is a compat shadow and manually drawn. I am aware of this and the linked commit is already attempt 2 in fixing the shadow, but until now no fix sadly.

**Comment by Glitchy-Tozier** [comment] 2021-07-21 08:40
Hi, is this still an issue for you?

I still experience the keyboard just never closing when switching apps, but I always assumed this is more of an android-issue.

**Comment by Glitchy-Tozier** [comment] 2021-09-25 06:24
I'll close this issue as it most likely has been solved in later versions of FlorisBoard.

Please reopen, should the problem persist!

**Closed by Glitchy-Tozier** 2021-09-25 06:24 UTC
Labels: bug, area: other
