### ISSUE TITLE
Swipe left / right to Delete or Pin clipboard items

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1648] opened 2022-03-15 22:15 UTC
Hello,

I found this good library if you in the features plan to add swipe actions to the clipboard manager/history you can use this library to do that action swipe left to delete current clip item and or swipe right to pin items.

The Library: [RecyclerViewSwipeDecorator](https://github.com/xabaras/RecyclerViewSwipeDecorator)

Example: 

![Sample app - Swipe right](https://xabaras.github.io/RecyclerViewSwipeDecorator/img/screen01.png) ![Sample app - Swipe left](https://xabaras.github.io/RecyclerViewSwipeDecorator/img/screen02.png)

**Comment by GoRaN909** [comment] 2022-03-15 22:18
This is related to #1179

**Comment by patrickgold** [comment] 2022-03-18 17:19
Thanks Goran for your proposal! This is actually a lot easier to accomplish with pure Compose, although it won't be done before 0.3.14 stable anymore (which' release is soon). Will add this to my 0.3.15 idea list. Note that this is a direct duplicate of #1179, so closing this issue to keep the list of issues clean.

**Closed by patrickgold** 2022-03-18 17:19 UTC
Labels: proposal
