### ISSUE TITLE
Inverted values in 'Swipe distance threshold' Option?

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#406] opened 2021-02-28 23:46 UTC
#### Short description
From what I've seen in my tests, the following values are inverted:

`Short` is `Long` and vice versa
`Very short` is `Very Long` and vice versa

#### Steps to reproduce
1. Go to 'Gestures' tab and on 'Swipe distance threshold'
2. Change values and test
3. See error

#### Environment information
- FlorisBoard Version: v0.3.8
- Install Source: GitHub
- Device: Redmi Note 4
- Android version, ROM: MIUI 11 (Android 7.0)

**Comment by patrickgold** [comment] 2021-02-28 23:59
> From what I've seen in my tests, the following values are inverted:

Ok I've just tested the v0.3.8 release version on my phone and can't notice this bug. `Very short` triggers the gesture after a short amount of finger movement, `very long` takes a longer distance before the gesture is triggered. I have tried this out on the space bar move left/right gesture, because there the difference is most noticeable. For one-shot gestures it is hard to tell, will have to measure this exactly on an emulator.

**Comment by patrickgold** [comment] 2021-03-01 00:05
Your report made me notice another bug though, related to the suggestions feature: When moving the cursor very fast, the current word underline in the text field slides around and is delayed. Additionally, at the end of a text field the cursor completely escalates for a sec before being static at the end, which looks quite funny but is not the intended behavior. Will have to investigate into this.

**Comment by RickyM7** [comment] 2021-03-01 00:56
> Very short triggers the gesture after a short amount of finger movement, very long takes a longer distance before the gesture is triggered.

I didn't know that was normal behavior. I thought that Very long would cause more characters to be tagged and vice versa. So I guess there's no bug here (in addition to what you found), right?

**Comment by patrickgold** [comment] 2021-03-01 19:39
No, the swipe distance threshold works as intended, so I think we can close this issue. As for the other bug, I've opened another issue for this: #411

**Closed by patrickgold** 2021-03-01 19:39 UTC
Labels: bug, needs investigation
