### ISSUE TITLE
Musical Note Symbol Wrong Category

### ISSUE THREAD

**Issue by totoroot** [florisboard/florisboard#1421] opened 2021-12-03 11:37 UTC
I have used Florisboard for quite a while now and with every update it gets more stable and therefore usable and is my number one choice by now, so thanks for the great work!! 👏

I stumbled across a peculiar thijg when I was looking for the musical notes emojis (🎼🎵🎶).
They are in the category with the lightbulb symbol (💡) on the tab which makes sense to me as all the instruments can also be found in this category.

However I was looking for them in the next category, as this category uses four symbols on its tab, one of which is a musical note.

Perhaps it would make sense to replace this symbol with a check mark or some other symbol that can actually be found in this category.

To illustrate my point here are some screenshots:

<img src="https://i.imgur.com/9YLvti9.jpg" width="320">

<img src="https://i.imgur.com/I521FtG.jpg" width="320">

This issue definitely isn't very impactful, but I thought I'd point it out in case no one else has noticed.

Cheers!

**Environment information**
• FlorisBoard Version: 0.3.13
• Install Source: F-Droid
• Android: 11

**Comment by Glitchy-Tozier** [comment] 2021-12-07 09:46
Nice finding! :)

**Comment by patrickgold** [comment] 2021-12-07 19:44
That's actually a good find, and also a bit funny IMO.

So I thought about what could the cause be and here's my conclusion:

The emoji order and assignment to which group has not been chosen by me, I used the Unicode 13.1 emoji spec for this.

Google's material icon library (which I use extensively because the icons match the style of the Android and Material style very good) conveniently has an icon for each of Unicode's emoji group's, and I took them without giving too much thought about each icon.

Problem: Gboard (the primary reason I think the emoji icons are in the icon library in the first place) does NOT follow the Unicode categories 1:1, while FlorisBoard does... So in Gboard you will actually find the music emoji in the group with the musical note on it.

As it is easier for me to fix the icons of the groups than beginning to manually reorder emojis, I will have to find an alternative icon.

**Comment by Glitchy-Tozier** [comment] 2021-12-08 20:25
I know Whatsapp and Element use this icon in their Emojie-board: https://fonts.google.com/icons?selected=Material+Icons&icon.query=symbol

**Comment by patrickgold** [comment] 2021-12-08 21:30
You mean this? https://fonts.google.com/icons?selected=Material%20Icons%3Apin%3A

It would make sense, because the category contains a lot of symbols with filled boxes, including filled 1s, 2s and 3s.

**Comment by Glitchy-Tozier** [comment] 2021-12-09 07:23
Yup, this one! :)

**Comment by patrickgold** [comment] 2022-05-16 22:17
Above commit/PR changes the icon of the emoji category symbols to the linked one above (filled 123 box). Will be released in 0.3.16-beta03, thanks again for noticing this minor detail :)

**Closed** 2022-05-17 13:39 UTC
Labels: proposal, proposal-accepted, area: emoji-kaomoji
