### ISSUE TITLE
Delete precisely with delete key swipe gesture

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#25] opened 2020-10-20 10:37 UTC
Hi,
Thanks for maintaining this project.

I think you took a lot of inspiration from Gboard which I like since I switched from Gboard to Florisboard.

In the latest release you added the gestures (which I really like, especially the swipe down to hide) but the swipe left on delete key gesture only deletes full words.
In Gboard's version you can highlight something left to the cursor, let go and it deletes the highlighted text. I was wondering if it is possible for you to implement it as well.

**Comment by patrickgold** [comment] 2020-10-20 14:15
Hi D3SOX,

thanks for your suggestion. I didn't even know that Gboard had this feature. I'll add it to the todo list for v0.3.0!

**Comment by HyknuF** [comment] 2020-10-31 05:57
Hi Together,

first of all, I just tested your keyboard and it looks really nice coded so far. Thanks for your effort and hopefully you keep going :-)

Nice to hear, that this feature will implemented soon, as it is really really handy.  Thank you!

**Comment by kojid0** [comment] 2020-11-26 22:13
Openboard has this feature as well, so you might want to look at its source code on github, if needed :)

**Comment by RickyM7** [comment] 2020-11-28 23:19
Some changes that would greatly improve the way "Swipe to Delete" works in the app. The changes would be:

- 1. Mark the characters while swiping.

- 2. Don't interact with the keyboard while swiping.

- 3. Do not lock "Swipe to Delete" after deleting only one word.

Example:

| App in example: [Simple Keyboard](https://github.com/rkkr/simple-keyboard) |
| --- |
| ![Swipe to Delete Example](https://user-images.githubusercontent.com/24703825/100527303-069eaf00-31b0-11eb-91e8-83eaf69ae045.gif) |

**Comment by patrickgold** [comment] 2020-11-29 21:50
Above commit adds precise character selection and deletion with the delete key, as in the image above. You still have the choice to have the previous 'Delete current word' gesture as selectable swipe action, alongside with no action at all (see image below). Will release with v0.2.5 shortly.

![image](https://user-images.githubusercontent.com/19412843/100554492-3b386680-3295-11eb-8372-e36ed5f3b551.png)

**Comment by HyknuF** [comment] 2020-11-30 05:38
Perfect, i will test it as soon as it's released 👍

**Comment by D3SOX** [comment] 2020-11-30 05:54
> Perfect, i will test it as soon as it's released 👍

It's already released. See https://github.com/florisboard/florisboard/releases/tag/v0.2.5

Working great so far.

**Comment by HyknuF** [comment] 2020-11-30 07:45
i can confirm, it works flawless so far 👍

**Comment by kojid0** [comment] 2020-12-01 20:06
Would it be possible to make delete on swipe more sensitive? Swiping fully from right to left only deletes a couple of words, so it takes a while to get rid of more
Example Florisboard:
![florisboard](https://user-images.githubusercontent.com/24477557/100790950-dd348c00-3418-11eb-80a7-11923a0e69f7.gif)

Example Openboard:
![openboard](https://user-images.githubusercontent.com/24477557/100790964-e1f94000-3418-11eb-9648-69a7d0d4dead.gif)

**Comment by D3SOX** [comment] 2020-12-01 20:08
@kojid0 I was thinking exactly the same. Another improvement that would be kinda cool: An option that makes it snap to words

**Comment by kojid0** [comment] 2020-12-01 20:12
> An option that makes it snap to words

yeah!🔥

**Comment by patrickgold** [comment] 2020-12-01 20:24
> Would it be possible to make delete on swipe more sensitive? Swiping fully from right to left only deletes a couple of words, so it takes a while to get rid of more

@kojid0 Hmm yeah you are right, I'll adjust the sensitivity.

> An option that makes it snap to words

This sounds like a cool idea, will definitely implement it!

**Comment by RickyM7** [comment] 2020-12-02 18:27
> Hmm yeah you are right, I'll adjust the sensitivity.

@patrickgold Will this adjust also apply to the option to move the cursor when swipe the space bar?

**Comment by patrickgold** [comment] 2020-12-02 18:29
@RickyM7 yes, because the same GestureHandler is responsible for both the space bar swipe and the precise delete swipe.

**Comment by RickyM7** [comment] 2020-12-02 18:33
@patrickgold That's great.

**Comment by RickyM7** [comment] 2020-12-23 10:43
@patrickgold This has already been added, so I think this issue can be closed, however I have a note, the swipe gestures still have little sensitivity in v0.3.1.

**Comment by patrickgold** [comment] 2020-12-23 12:58
@RickyM7 Yes it's true that the precise key deletion feature has been implemented, but currently ot only snaps to characters. I will close this issue when the precision delete also works for words.

**Comment by RickyM7** [comment] 2020-12-23 13:20
@patrickgold Got it. Thank you for the reply.

**Closed** 2020-12-25 18:39 UTC
Labels: proposal, proposal-accepted
