### ISSUE TITLE
FlorisBoard crashed - empty log

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#646] opened 2021-04-13 12:20 UTC
#### Short description
I'm not sure what happened. I only know that i put the phone down (without locking it). When I picked it up, Florisboard had crashed.

The weird thing is, there is no stacktrace. It's just empty.
![Screenshot_20210413-141221_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/114551152-4946bc80-9c63-11eb-86b4-ee07b0fd0b3b.jpg)

For comparison, a "normal crash":
![Screenshot_20210413-141611_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/114551113-3fbd5480-9c63-11eb-8167-2e84c6f91d5d.jpg)

If you think this issue has too little information to be helpful, you can close it.  :)

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment] 2021-04-13 18:13
Thanks for your bug report! Empty logs can rarely occur, because the stacktrace UI is displayed twice and you only see the second dialog, where the stacktrace files have already been read and thus deleted. Don't really know though how this bug occurs or how to fix it (the possibilities what I can do is very limited if the service state is "crashed"). I will close this issue, should you either experience this issue multiple times again or you find a way to reproduce this bug, feel free to reopen the issue!

**Closed** 2021-04-13 18:13 UTC
Labels: bug
