### ISSUE TITLE
Spacing after word input in glide typing

### ISSUE THREAD

**Issue by Mech4Life1970** [florisboard/florisboard#1983] opened 2022-07-29 11:56 UTC

**Comment by Glitchy-Tozier** [comment] 2022-07-29 20:42
Could you please specify your proposal. Automatic spacing when glide-typing has been a feature for a long time.

**Comment by KLaurence** [comment] 2022-07-30 09:48
This might be a duplicate of #1940

**Comment by patrickgold** [comment] 2022-08-01 09:57
I agree with @KLaurence that this is probably a duplicate of #1940, closing thus.

**Closed by patrickgold** 2022-08-01 09:57 UTC
Labels: invalid, needs more info, proposal

**Comment by Mech4Life1970** [comment] 2022-08-30 11:20
Yes its on the same lines as #1940 sorry didnt see it...
