### ISSUE TITLE
[Feature Request] Add question mark for language right to lift "؟" 

### ISSUE THREAD

**Issue by Natsu-raw** [florisboard/florisboard#372] opened 2021-02-18 10:23 UTC
- Hello, there is no question mark for language's from right to lift like Arabic "؟" 
 In other keyboard it is place in same location of "?" if you change language

**Comment by Waelwindows** [comment] 2021-02-18 10:25
This a duplicate of #120

**Comment by Natsu-raw** [comment] 2021-02-18 10:29
I forget to search sorry

**Closed** 2021-02-18 10:30 UTC
