### ISSUE TITLE
How to contribute an exported JSON theme?

### ISSUE THREAD

**Issue by kj7rrv** [florisboard/florisboard#463] opened 2021-03-16 20:25 UTC
I exported a "Completely Black" theme. How can I contribute it? 
![Screenshot_20210316-132503](https://user-images.githubusercontent.com/58444735/111375210-37213080-865b-11eb-975a-374469b7d978.png)
![Screenshot_20210316-132517](https://user-images.githubusercontent.com/58444735/111375221-3b4d4e00-865b-11eb-85ef-4b4a871ff159.png)
![Screenshot_20210316-132530](https://user-images.githubusercontent.com/58444735/111375231-3d171180-865b-11eb-886c-c8478145f904.png)

**Comment by D3SOX** [comment] 2021-03-16 20:55
I also created a theme: `Florisboard Black Borderless Red`
![Screenshot_20210316-215239_1.png](https://user-images.githubusercontent.com/24937357/111378437-16c89480-86a2-11eb-9110-77d88fb45694.png)
![Screenshot_20210316-215241_1.png](https://user-images.githubusercontent.com/24937357/111378442-18925800-86a2-11eb-903b-23875b4711b6.png)

But I'm not sure what the guidelines are for submitting themes. Maybe you should add this to the Contributing Guidelines

**Comment by patrickgold** [comment] 2021-03-16 22:01
> But I'm not sure what the guidelines are for submitting themes.

You are right, there are currently no real guidelines for theme contributions. The problem is that there will probably be many custom themes, which is very cool but the core app file size will increase as well.

To keep things small and tidy, I propose that I set up a community repository on GitHub where everyone can share his theme + preview images. Others can then explore the repo, download themes they like and import them into FlorisBoard. This way the core app file size is small, but I won't have to reject potentially cool community themes (and in the future layouts and other things too). What do you think of this approach?

**Comment by kj7rrv** [comment] 2021-03-16 22:09
That sounds great! And maybe add a "theme browser" (as an extension to avoid network permission) to FlorisBoard?On Mar 16, 2021 15:01, Patrick Goldinger ***@***.***> wrote:

But I'm not sure what the guidelines are for submitting themes.

You are right, there are currently no real guidelines for theme contributions. The problem is that there will probably be many custom themes, which is very cool but the core app file size will increase as well.
To keep things small and tidy, I propose that I set up a community repository on GitHub where everyone can share his theme + preview images. Others can then explore the repo, download themes they like and import them into FlorisBoard. This way the core app file size is small, but I won't have to reject potentially cool community themes (and in the future layouts and other things too). What do you think of this approach?

**Comment by D3SOX** [comment] 2021-03-16 22:43
I like that idea too! :+1:

**Comment by patrickgold** [comment] 2024-05-05 13:59
Community themes will be supported through the official addons store, see #2468 for more details. Closing this discussion to avoid duplicate discussion channels.

**Closed by patrickgold** 2024-05-05 13:59 UTC
Labels: question, area: kbd-theme
