### ISSUE TITLE
Why does Floris keyboard and floris keyboard beta lose glide typing after my phone restarts? This bug has been happening after the latest updates to both of them. Unless I'm doing something wrong. 

### ISSUE THREAD

**Issue by shreyanssshah** [florisboard/florisboard#1395] opened 2021-11-15 15:20 UTC
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by GhostMcT** [comment] 2021-11-21 02:36
Even I am facing this bug for a long time. Not only glide typing, but most of the settings in the new UI gets reset after a restart.

**Comment by patrickgold** [comment] 2021-11-21 18:11
I am aware of this bug, this is because the direct-boot context did not reset to the user-context after unlocking.

Will close as a duplicate of #1304 , will be released as beta06 as soon as I finish with my works on #1370.

**Closed by patrickgold** 2021-11-21 18:11 UTC
Labels: bug
