### ISSUE TITLE
Keyboard does not show up reliably all of the time on webpage form elements

### ISSUE THREAD

**Issue by 9mido** [florisboard/florisboard#469] opened 2021-03-17 21:04 UTC
The keyboard does not appear when trying to type something into a form element of a webpage you are using reliably all of the time. A refresh of the browser is needed to get it to show up again to be able to type in the webpage's search bar. Not sure if this happens for the URL bar of the browser but it happens within webpage form elements themselves randomly. Also not sure if it happens for certain browsers. This bug has been reproduced multiple times in the past but it is hard to figure out how to reproduce it each time to fix the issue. This bug does not occur often so it is not a big deal if it does not get fixed since a refresh is all that is needed to fix the problem.

**Comment by patrickgold** [comment] 2021-03-17 21:46
Which web browser are you talking about? It is known that web elements of the Firefox Android browser cause some trouble (because sometimes IME events get lost) but this happens only rarely within a webpage, not for URL bars.

**Comment by 9mido** [comment] 2021-03-17 23:17
Duckduckgo

**Comment by patrickgold** [comment] 2021-03-18 17:20
So basically the Android WebView so basically some Chromium variant. Hmm normally Chromium browsers work really well with FlorisBoard, will investigate into this!

**Comment by 9mido** [comment] 2021-03-19 00:12
@patrickgold 

I think I found a way to reproduce it. 

Play a video, full screen the video, un-fullscreen the video, then try typing into a form element. When I do this, the keyboard does not show up for me. Hope this helps.

**Comment by patrickgold** [comment] 2021-03-19 00:27
@9mido Was able to reproduce this bug in DDG browser and on youtube.com, however not only with FlorisBoard but also with Gboard, OpenBoard and AnySoftKeyboard.

I've read the debug log and from what I can see is that after exiting fullscreen and tapping into an input field the `onStartInputView()` event is not triggered, which is highly important for an IME to show itself. When tapping into the urlbar, the state resets and everything works again correctly.

**Comment by 9mido** [comment] 2021-03-19 00:36
@patrickgold 

Okay cool glad you were also able to reproduce it. I didn't check other browsers/apps but maybe the same thing happens there as well? 

So if it happens with the other keyboards is there nothing that can be done?

**Comment by patrickgold** [comment] 2021-03-19 00:54
@9mido This is indeed a known bug in DDG and has been fixed with this commit: https://github.com/duckduckgo/Android/commit/cd2108eb7f1f843a163377e8d4f88f103f3b3741

I just tried out their latest release v5.78.1 and can confirm that it is fixed, so when you can also confirm this then I think this issue is resolved.

**Comment by 9mido** [comment] 2021-03-19 01:02
@patrickgold Yup the newest version worked. Thanks for the help.

**Comment by patrickgold** [comment] 2021-03-19 01:43
Perfect, thanks for confirming! Will close this issue now.

**Closed by patrickgold** 2021-03-19 01:43 UTC
Labels: bug, needs investigation
