### ISSUE TITLE
Please add clipboard manager

### ISSUE THREAD

**Issue by FBIAgent05** [florisboard/florisboard#296] opened 2021-02-01 08:46 UTC
The clipboard will show you your recently copied texts in one place. You can also pin copied text
![Screenshot_20210201_164050](https://user-images.githubusercontent.com/74946397/106434572-b3492580-64ac-11eb-80c8-c31aa2c0c817.jpg)

Example in Google Keyboard

**Comment by D3SOX** [comment] 2021-02-01 08:59
Duplicate of #113

**Closed** 2021-02-01 14:08 UTC
Labels: proposal
