### ISSUE TITLE
NullPointerException crash involving initial state of keyboard logic

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#2025] opened 2022-08-28 20:12 UTC
#### Short description
Can't really tell what I did to crash it but I basically updated to alpha4, opened the app drawer in Lawnchair and tried to instantly type after it opened the keyboard. I can't reproduce it again but I hope the stack trace is helpful anyway. Maybe it has something to do with a setting so if you need any additional informatiom just ask.

#### Steps to reproduce
1. Set Lawnchair to automatically show the keyboard on app drawer open
2. Swipe up and instantly type
3. See crash

#### Environment information
- FlorisBoard [0.4.0-alpha03](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha03) (89)
- Device: OnePlus KB2003 (OnePlus8T_EEA)
- Android: 11 (cn=R sdk=30)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-08-28T20:07:58.646Z
Manufacturer        : OnePlus
Model               : KB2003
Product             : OnePlus8T_EEA
Android             : 11 (cn=R sdk=30) [lineage_kebab-userdebug 11 RQ3A.211001.001 eng.root.20220817.180712 dev-keys]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.20 GiB (57.28% used, 7.34 GiB max)
Font scale          : 1.0
Locales             : en-US,de-DE

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha03 (89)
Build type          : beta
Build commit hash   : 26650d2a00d509efbbd58bafa8606ba11bc5961f
Java heap memory    : 34.29 MiB (13.39% used, 256.00 MiB max)
Native heap memory  : 28.43 MiB (90.42% used, 31.44 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1661717267554.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.lib.StateAdaptersKt.observeAsNonNullState(StateAdapters.kt:10)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardManager.observeActiveState(Unknown Source:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1$1.invoke(FlorisImeService.kt:73)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1$1.invoke(FlorisImeTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt$FlorisImeTheme$1.invoke(FlorisImeTheme.kt:13)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:4)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:6)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:6)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:132)
	at dev.patrickgold.florisboard.ime.theme.FlorisImeThemeKt.FlorisImeTheme(FlorisImeTheme.kt:32)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1$1.invoke(FlorisImeService.kt:7)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt$ProvideKeyboardRowBaseHeight$2.invoke(FlorisImeSizing.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.ime.keyboard.FlorisImeSizingKt.ProvideKeyboardRowBaseHeight(FlorisImeSizing.kt:116)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUiWrapper$1.invoke(FlorisImeService.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt$ProvideLocalizedResources$1.invoke(Resources.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at dev.patrickgold.florisboard.lib.compose.ResourcesKt.ProvideLocalizedResources(Resources.kt:11)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUiWrapper(FlorisImeService.kt:3)
	at dev.patrickgold.florisboard.FlorisImeService$ComposeInputView.Content(FlorisImeService.kt:4)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:23)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:8)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:88)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:4)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:23)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at kotlin.LazyKt__LazyJVMKt.invokeComposable(LazyJVM.kt:2)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:5)
	at kotlin.text.UStringsKt.observeDerivedStateRecalculations(UStrings.kt:8)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:22)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:10)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:7)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:15)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:2)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Unknown Source:12)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:5)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:13)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:11)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:17)
	at android.view.View.dispatchAttachedToWindow(View.java:20479)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5278)
	at android.view.ViewGroup.addView(ViewGroup.java:5064)
	at android.view.ViewGroup.addView(ViewGroup.java:5036)
	at android.inputmethodservice.InputMethodService.setInputView(InputMethodService.java:1920)
	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:1755)
	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2182)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2131)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:750)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:722)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:226)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

**Comment by patrickgold** [comment] 2022-08-29 21:35
Thanks for your bug report!

I haven't been able to reproduce this crash at all, but I think I know where the source is. Will experiment later on with changing the observer logic, so this crash cannot occur anymore.

**Comment by patrickgold** [comment] 2022-08-29 23:03
Above commit/PR should fix the issue, I now completely swapped the observer logic of KeyboardState from Android's LiveData to Kotlin's StateFlow, which should help eliminate these dangling initial null references. This fix will be parts of the 0.4.0-alpha04 release.

@D3SOX @keatit71 @noesterle If possible, could some of you try out the debug artifact of said PR to test if you can produce it in any way? The debug artifact installs independently from beta and stable, you can uninstall it after testing again.

**Comment by KLaurence** [comment] 2022-08-30 03:50
Adding to Patrick's comment, the debug artifact is [here](https://github.com/florisboard/florisboard/actions/runs/2952321241) named `app-debug.apk`.

**Comment by xxxserxxx** [comment] 2022-08-31 12:23
In my case, I didn't notice the crash, just the notification in the title bar. It's the same null pointer, but I don't know how to trigger it, and so don't know how to test that the debug APK works. Other than just running it for a week and seeing if I get no crashes. Is that kind of testing valuable?

**Comment by sybenx** [comment] 2022-08-31 14:55
Thid crash may be related: NullPointerException
[Paste](https://bin.foss.wtf/?145f51126752fb8c#E3pcVkVfqkSuJ1KorYSjNXiEr3CibuHDjP7NndP1vWDx)

**Comment by patrickgold** [comment] 2022-08-31 18:14
> In my case, I didn't notice the crash, just the notification in the title bar. It's the same null pointer, but I don't know how to trigger it, and so don't know how to test that the debug APK works. Other than just running it for a week and seeing if I get no crashes. Is that kind of testing valuable?

Yeah just seeing if the crash is reported as a notification or not because it crashed sometime while you didn't use your phone is also valuable testing.

**Comment by patrickgold** [comment] 2022-08-31 18:15
> This crash may be related: NullPointerException

It is the same crash as far as I can see

**Closed** 2022-08-31 18:16 UTC
Labels: bug, needs investigation, area: kbd-logic
