### ISSUE TITLE
Capitalisation broken

### ISSUE THREAD

**Issue by uli-on** [florisboard/florisboard#1378] opened 2021-11-03 20:05 UTC
#### Short description
Capitalisation is not working for me and never did, no matter what I try (marking a word, putting cursor inside a word or at its end, then double tapping shift key or long tapping), in none of the FlorisBoards I've currently installed, that is 0.3.13, 0.3.14 beta05, and 0.3.14 debug.

#### Environment information
- FB 0.3.14 beta 05 (from F-Droid)
- Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
- Webview 94.0.4606.71
- Motorola Moto G4
- device not rooted

**Comment by Glitchy-Tozier** [comment] 2021-11-03 20:08
I don't think that feature has been implemented yet.

**Comment by uli-on** [comment] 2021-11-03 20:31
Then I've misunderstood #419, sorry.
But actually a must have feature.

**Comment by Glitchy-Tozier** [comment] 2021-11-03 20:58
I see what you mean, that issue can easily be read in a different way.

If you don't mind, I'll close this issue as a duplicate of the other 1-3 issues that request this feature. :)
The other ones (at least one of them) will stay open and will probably be tackled eventually.

**Comment by uli-on** [comment] 2021-11-03 21:05
> I see what you mean, that issue can easily be read in a different way.
>
And to be honest I only read the first post :)
But yes, can be closed, of course.

**Closed** 2021-11-04 10:04 UTC
Labels: bug, duplicate
