### ISSUE TITLE
Delete key swipe left bug

### ISSUE THREAD

**Issue by el-Basketo** [florisboard/florisboard#1765] opened 2022-04-07 08:33 UTC
#### Short description
When the "Delete key swipe left" parameter is set to "Delete words precisely", it is possible to swipe right and it will still select and delete words to the left.
This hinders usability: swipe left to select the words to delete, change your mind, swipe right and release to cancel, some words still get deleted.
Similar behavior is displayed with "Select words precisely". The issue is not present with the other settings (characters and current word).
I hope this hasn't been filed already, I searched before posting :)

#### Steps to reproduce
1. Go to Settings -> Gestures & Glide typing -> Delete key swipe left. Select either "Delete words precisely" or "Select words precisely".
2. Go to any text field.
3. Type a few words.
4. Either swipe right on the delete key, or swipe left then right without releasing.
5. See unexpected behavior of words getting deleted when they shouldn't

#### Environment information
- FlorisBoard Version: 0.3.14 (75)
- Install Source: F-Droid
- Device: Fairphone 4 128GB
- Android: Android 11 stock (Android RKQ1.210503.001, Build number FP4.FP3Q.A.094.20211213)

#### Developer congratulations
Your app is amazing, I rely on it everyday. I chose it over Gboard, Swiftkey or any other because of the nifty gesture features (delete, spacebar, etc) the super deep customizability, the privacy and the super clean and minimalist design. Cheers!

**Comment by m-koushan** [comment] 2022-04-08 13:47
I tried it on FlorisBoard Beta 0.3.15-rc01 and it seems fine for me
Can you download this version from github and give us the result pls?

**Comment by patrickgold** [comment] 2022-04-08 15:45
Thanks for your bug report!

I was able to reproduce your issue, it was caused by the fact that I took the mathematically absolute value of the horizontal swipe distance. In above commit I added a value checker ensuring it is the proper range before using it to select words, so selecting words left via swiping right is not possible anymore. Will be released in 0.3.15-rc02 soon.

**Closed by patrickgold** 2022-04-08 15:45 UTC
Labels: bug, bug-confirmed, area: gestures

**Comment by el-Basketo** [comment] 2022-04-10 16:02
> it was caused by the fact that I took the mathematically absolute value of the horizontal swipe distance.
This is what I suspected. Thanks for the quick response, I am looking forward to the next updates!
