### ISSUE TITLE
Reorder keys to avoid tapping navigation pill instead of space.

### ISSUE THREAD

**Issue by teemue** [florisboard/florisboard#58] opened 2020-12-02 16:09 UTC
This is a bit niche request, but I use Navigation Gestures-app and the pill always gets on the way (like in the picture attached). Some keyboards have a function to lift keyboard on the screen (pixelwise) enough to avoid misclicking. More elegant solution would be reordering of  keys, so that bottom corners would have buttons but there would be empty space between them.
![Screenshot_20201202-114018](https://user-images.githubusercontent.com/317905/100898183-293f0980-34c9-11eb-9f6a-b632af39298d.png)

**Comment by patrickgold** [comment] 2020-12-02 16:18
Thanks for your suggestion, teemue. Afaik, Android apps can't automatically detect the pillow, as it is technically an overlay over the window FlorisBoard draws and is not in the way during the measurement process (I will look it up though).

You could try to adjust the setting `Keyboard > Bottom offset (for curved screens)`, which was intended to lift up FlorisBoard's keys by the specified dp to avoid curved screen's edges, for avoiding the pillow as well. Setting it to something like ~16dp to 20dp should suffice, although that varies from device to device. Let me know if this fixed your issue!

**Comment by teemue** [comment] 2020-12-02 16:24
I tried different offset values but tbh i didn't notice any difference. But thanks for considering this!

**Comment by patrickgold** [comment] 2020-12-02 16:28
I just noticed that on the latest version the bottom offset is completely broken for some reason, this is why you didn't notice any difference...

Regarding your suggestion, after fixing the bottom offset preference I will also add a toggle to auto avoid a navigation overlays, as I think this is the best option to tackle ths. Thanks for your input!

**Comment by patrickgold** [comment] 2020-12-06 22:06
I have tested around a bit with auto-avoiding the pillow but was unfortunately unsuccessful. As a temporary workaround you can use the bottom offset for pushing up FlorisBoard (which should start working with v0.3.0 again). I'll set the navigation avoidance on my todo list for 0.4.0.

**Comment by teemue** [comment] 2020-12-07 15:48
Bottom offset works now. Unfortunately it's maximum value is not enough.

**Comment by patrickgold** [comment] 2021-01-31 22:45
@teemue I've tried around some auto-detection for this and unfortunately I wasn't able to implement something which could automatically avoid the navigation pillow. What I've done though is I've split up the `Bottom offset` preference into a portrait and landscape one and expanded the value range from 0...24 to 0...60 dp, which should be more than sufficient for avoiding the nav pillow. Will be released with v0.3.6 tomorrow.

**Closed by patrickgold** 2021-01-31 22:45 UTC
Labels: proposal, proposal-accepted

**Comment by teemue** [comment] 2021-02-02 17:26
Thanks. 60dp is enough indeed! This is the best solution I've seen on FOSS keyboards.
To make use of the leftover space under keyboard in this kind of situation, I would like to see 'corner buttons' described in the first post, but I understand that it's not prioritized. Thank you anyway :)
