### ISSUE TITLE
Western (Additional Symbols) keys are too tall

### ISSUE THREAD

**Issue by llgdd** [florisboard/florisboard#2153] opened 2023-02-09 16:35 UTC
#### Short description
Western (Additional Symbols) symbols layout keys are too tall, resulting in overlaps when vertical spacing between keys is set to a lower value.

#### Steps to reproduce
1. Change your Symbols layout to Western (Additional Symbols).
2. Set Vertical spacing between keys to a value lower than the default.

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: F-Droid
- Device: Sony Xperia XZ3
- Android: 10, Sony edition (which is mostly vanilla)

![_20230209_183559.JPG](https://user-images.githubusercontent.com/53429650/217877905-18554202-9e20-47f0-a792-456cc31639e6.JPG)

**Comment by tsiflimagas** [comment] 2023-05-20 20:20
Thanks for your bug report! This seems like a duplicate of #1561 ,which has actually been fixed in v0.4.0-alpha03.

**Closed** 2023-05-20 20:50 UTC
Labels: bug, duplicate, area: kbd-ui
