### ISSUE TITLE
Settings reset after every reboot

### ISSUE THREAD

**Issue by xxxcrow** [florisboard/florisboard#2394] opened 2024-02-11 18:53 UTC
Hi, firstly, i'm very happy to see the project back, I've been using this keyboard for a very long time already

My issue is simple, after every reboot all the setting are reset, all the layouts, themes, haptics, everything
It even asks me to do the settings again

**Comment by lm41** [comment] 2024-04-07 19:44
Can you please provide more information such as android system version, app version etc.

**Comment by patrickgold** [comment] 2024-04-14 22:16
Duplicate of #1726

Sadly this rare bug still hasn't been resolved, however when I find the time could try using the read-only flag for preference models introduced with [JetPref 0.1.0-rc01](https://github.com/patrickgold/jetpref/releases/tag/0.1.0-rc01)

**Closed by patrickgold** 2024-04-14 22:16 UTC
Labels: bug, needs more info, needs investigation
