### ISSUE TITLE
Current FB 0.3.14 debug (DL 2021-11-02) tends to forget prefs

### ISSUE THREAD

**Issue by uli-on** [florisboard/florisboard#1389] opened 2021-11-07 01:07 UTC
I've now had this three times, one time the language layouts were gone, one time that plus I've had to re-initialise my prefs (i.e. like I've passed steps 1 & 2 in the setup procedure but forgot to complete step 3, <ins>although the customisations executed in the Design, Keyboard and Gesture sections remained</ins>), and one time ***all*** my customisations were set to default.

The only pointer I can supply is, I'm quite frequently switching keyboards, maybe 5-10 times a day.

FB version from here:
https://github.com/florisboard/florisboard/issues/1364#issuecomment-955866150
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 94.0.4606.71
Motorola Moto G4
device not rooted

(Edited for inserting underlined phrase.)

**Comment by Donkey-Doug** [comment] 2021-11-07 13:15
Same issues, but also with beta version. Not kust debug version.

**Comment by Glitchy-Tozier** [comment] 2021-11-08 20:56
@patrickgold Sounds like an important issue.

**Comment by patrickgold** [comment] 2021-11-09 00:27
Thanks for your issue! This is indeed a mysterious problem, some parts (like the localization problems) are because the old logic clashes with the new one (am currently rewriting this bit with moving layouts and subtypes to extensions).

> plus I've had to re-initialise my prefs (i.e. like I've passed steps 1 & 2 in the setup procedure but forgot to complete step 3, although the customisations executed in the Design, Keyboard and Gesture sections remained)

This is a thing I definitely have to investigate, currently I do not know why this happens.

> and one time all my customisations were set to default.

This can happen during beta upgrades (because a lot of keys are changing in the background), but other than that while normally using FLorisBoard beta without updating this should NOT happen. If it occurs while normal usage please report this to me and I will have to do a proper research if the preference initialization fails due to some weird state.

**Comment by uli-on** [comment] 2021-11-09 06:27
>> and one time all my customisations were set to default.
> This can happen during beta upgrades (because a lot of keys are changing in the background), but other than that while normally using FLorisBoard beta without updating this should NOT happen. If it occurs while normal usage please report this to me and I will have to do a proper research if the preference initialization fails due to some weird state.
> 
OK, so let me insist ;) that the reported issue — in my case — has nothing to do with upgrading! This is about the debug version I've downloaded to verify if a new/proper installation would lock me in step 1 of the setup procedure, and I've kept it and am still using it.

**Comment by patrickgold** [comment] 2021-11-09 08:19
> OK, so let me insist ;) that the reported issue — in my case — has nothing to do with upgrading! This is about the debug version I've downloaded to verify if a new/proper installation would lock me in step 1 of the setup procedure, and I've kept it and am still using it.

Ok got it, just wanted to say that upgrading can cause these issues too ;)

Will def. look into this before I release beta06, because this is a pretty annoying bug if it occurs.

**Comment by patrickgold** [comment] 2022-01-05 01:23
Tomorrow/Today beta08 will be released. While I didn't get any further reports that the pref forget issue is still a thing, I would like to hear from you if this bug is still reproducible in beta08, else I think we can close this issue. Thanks in advance!

**Comment by Donkey-Doug** [comment] 2022-01-05 01:38
I have not experienced this problem for a while. I think it is safe to assume that the problem has been solved.

**Closed** 2022-01-27 23:30 UTC
Labels: bug, area: settings, bug-confirmed
