### ISSUE TITLE
Cant copy/cut URL in browser 

### ISSUE THREAD

**Issue by nikhilbadyal** [florisboard/florisboard#534] opened 2021-03-30 11:27 UTC
As the title says. The copy/cut options are disabled while i try to copy url in browser.

As you can see in the image . If i select the whole URL. Copy/cut option gets disabled 

![IMG_20210330_165357.jpg](https://user-images.githubusercontent.com/59223300/112981510-27502480-9110-11eb-96b8-f391293e9b39.jpg)

**Comment by Glitchy-Tozier** [comment] 2021-03-30 12:02
Version?


On 0.3.9 i can reproduce it, though it works most of the time. Randomly it doesn't though.

**Comment by ProblematicDude** [comment] 2021-03-30 12:06
Its 0.3.10 beta 4  and for me. Most of the time it doesnt work

**Comment by patrickgold** [comment] 2021-03-30 14:49
Which browser does this bug occur? It seems as FlorisBoard doesn't register the selection, thus the copy/cut enabled states don't get updated.

**Comment by ProblematicDude** [comment] 2021-03-30 14:51
[This is the browser](https://github.com/kiwibrowser)

It's Kiwi

**Comment by patrickgold** [comment] 2021-03-30 15:03
Thanks for sharing! Will investigate into this.

**Comment by patrickgold** [comment] 2021-03-31 21:47
> When using Shift+Spacebar-swipe to select text, the copy-button only gets activated after you release BOTH shift and space

This is actually intended behavior to avoid updating the UI constantly while the selection rapidly changes.

> Delete-swipe also doesn't activate the copy-button anymore

Happens because normally the copy/paste buttons don't get updated until the selection is final (meaning you stopped selecting and released your input pointer). For the delete swipe, there's no final selection, because the final selection is immediately deleted.

> Not sure if that's the same issues you're battling, but they are kind of annoying.

I can try to at least update the Smartbar UI for every change instead of only the final one, though this isn't the bug for the above mentioned issue.

**Comment by Glitchy-Tozier** [comment] 2021-04-01 06:39
I see, let's continue this unrelated thread on #542 then.  :)

**Comment by patrickgold** [comment] 2022-03-06 11:05
I just tested this issue out in the KIWI browser and could not reproduce it anymore using the latest debug build of PR #1618. Thus I will close this issue as fixed. Thanks for reporting it!

**Closed by patrickgold** 2022-03-06 11:05 UTC
Labels: bug, bug-confirmed, area: smartbar

**Comment by Glitchy-Tozier** [comment] 2022-03-06 15:38
@patrickgold I think I can still reproduce it.

1. Get Firefox Klar (I got it from the Google Play Store)
2. Go to any website
3. Click on the url-bar
4. **See bug**: Copy&Cut are disabled

**Comment by patrickgold** [comment] 2022-03-06 15:59
@Glitchy-Tozier That's correct, when following your steps it is still a case. The reason is that Firefox Klar provides my keyboard the following information:

```Logcat
2022-03-06 16:47:56.915 31851-31851/dev.patrickgold.florisboard.debug I/EditorInstance: startInputView() - info=android.view.inputmethod.EditorInfo
    imeOptions: action=IME_ACTION_GO flags=IME_FLAG_NAVIGATE_NEXT|IME_FLAG_NO_EXTRACT_UI|IME_FLAG_NO_FULLSCREEN|IME_FLAG_NO_PERSONALIZED_LEARNING
    initialCapsMode: flags=(none)
    initialSelStart: 52
    initialSelEnd: 52
    inputType: class=TYPE_CLASS_TEXT variation=TYPE_TEXT_VARIATION_URI flags=(none)
    packageName: org.mozilla.klar
```

Note the `initialSelStart` and `initialSelEnd` both being reported as `52`? Based on that info it means that Firefox Klar shows an input field, which is at least 52 code points long and there is NO selection (if `end minus start == 0` then it is a blinking cursor at position start). Thus if FlorisBoard gets the info that there's a cursor it will not enable the copy/cut symbols.

Now we compare it to the same scenario (same website and also tapping into the URL bar), just in the Fennec F-Droid Firefox browser:

```Logcat
2022-03-06 16:53:41.091 31851-31851/dev.patrickgold.florisboard.debug I/EditorInstance: startInputView() - info=android.view.inputmethod.EditorInfo
    imeOptions: action=IME_ACTION_GO flags=IME_FLAG_NO_EXTRACT_UI|IME_FLAG_NO_FULLSCREEN
    initialCapsMode: flags=(none)
    initialSelStart: 0
    initialSelEnd: 52
    inputType: class=TYPE_CLASS_TEXT variation=TYPE_TEXT_VARIATION_URI flags=(none)
    packageName: org.mozilla.fennec_fdroid
```

Here the selection is correctly reported and thus the copy/cut icons are properly enabled. This is not an issue with FlorisBoard but Firefox Klar in this instance.

**Comment by Glitchy-Tozier** [comment] 2022-03-06 16:04
I see, so this seems to be FF Klar's issue.

Isn't there a way to check whether there is a selection instead of calculating cursor-positions?

**Comment by patrickgold** [comment] 2022-03-06 16:11
> Isn't there a way to check whether there is a selection instead of calculating cursor-positions?

Yes and no. When you type and the contents of the input fields change, I get the cursor position from a different callback, which is more reliable. The problem is I can't really trigger it, you must type something so it gets triggered. There are more commands available on the input connection to get the cursor position, but generally calls on the input connection should be avoided because it tends to be slow. But maybe with some tinkering to the input logic (which I will have to do anyways because of some crash reports which I need to fix) I can fix this as well.

Off-topic based on your screenshot: Are you experiencing the same Smartbar bug as #1615? The bug drives me crazy because I don't know what causes it and now I see it again from a different device.

**Comment by Glitchy-Tozier** [comment] 2022-03-06 16:20
> Yes and no. When you type and the contents of the input fields change, I get the cursor position from a different callback, which is more reliable. The problem is I can't really trigger it, you must type something so it gets triggered. There are more commands available on the input connection to get the cursor position, but generally calls on the input connection should be avoided because it tends to be slow. But maybe with some tinkering to the input logic (which I will have to do anyways because of some crash reports which I need to fix) I can fix this as well.

I see, good luck, then!

> Off-topic based on your screenshot: Are you experiencing the same Smartbar bug as #1615? The bug drives me crazy because I don't know what causes it and now I see it again from a different device.

Seems like it. Am i missing some setup-steps or is looking at it all I need to do?

![Screenshot_20220306-172031_GitHub.jpg](https://user-images.githubusercontent.com/59611881/156931810-ecbe801d-1761-41a1-b26f-f6f334e48515.jpg)

**Comment by patrickgold** [comment] 2022-03-06 16:35
> Seems like it. Am i missing some setup-steps or is looking at it all I need to do?

If you flip the toggle buttons in the preferences, does the three-dot icon then appear on the left, but never on the right?

**Comment by Glitchy-Tozier** [comment] 2022-03-06 16:40
Yep, that's the behaviour.

![Screenshot_20220306-173711_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/156932624-16a1127a-0477-465b-b690-ec6a751583c2.jpg)


Here's something that may or may not help: The button actually exists, it just doen't show it's icon. If we long-press-we still get an animation on that "empty" slot:

![Screenshot_20220306-173743_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/156932682-e191135d-9ee1-4762-9c0b-f21667b8326a.jpg)

![Screenshot_20220306-173801_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/156932690-110821c8-ef4b-4d7d-81f5-b118d29009ea.jpg)

![Screenshot_20220306-173817_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/156932695-83f189fc-ae64-482d-a776-6291bde073c4.jpg)

**Comment by Glitchy-Tozier** [comment] 2022-03-06 16:42
Additionally, tapping the empty button gives usthis toast:
![Screenshot_20220306-174127_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/156932775-ffeebb67-8dfb-4fee-81f8-e30fd424de8b.jpg)

**Comment by Glitchy-Tozier** [comment] 2022-03-06 17:29
ALSO the button shows up in landscape-mode:
![Screenshot_20220306-182825_Fennec.jpg](https://user-images.githubusercontent.com/59611881/156934574-12c8ec7d-6415-4e54-a8a9-7f295a764083.jpg)

**Comment by patrickgold** [comment] 2022-03-06 17:33
> Here's something that may or may not help: The button actually exists, it just doen't show it's icon. If we long-press-we still get an animation on that "empty" slot:

That does help a lot, because it means the button is squished into a space which is smaller than the intended size, so the icon is not drawn. Thanks for your detailed screenshots!

> ALSO the button shows up in landscape-mode:

Confirms my theory that there's something wrong with the layout measurement, and in landscape the overflow icon has more than enough space to sow itself. I will add a possible fix for it in today's beta14 release, could you check if it is fixed once you get the update via GPlay?

**Comment by Glitchy-Tozier** [comment] 2022-03-06 17:40
> I will add a possible fix for it in today's beta14 release, could you check if it is fixed once you get the update via GPlay?

Will do!  :)

**Comment by Glitchy-Tozier** [comment] 2022-03-07 15:31
Yay
![Screenshot_20220307-162732_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/157064848-75b386db-49f1-48c0-89bb-9476eff4717d.jpg)
