### ISSUE TITLE
[bug] inline autofill briken

### ISSUE THREAD

**Issue by Silther** [florisboard/florisboard#2563] opened 2024-09-17 12:13 UTC
### Short description

Inline autofill with password managers like Bitwarden or Proton Pass no longer work.

### Steps to reproduce

1. Open Bitwarden App
2. Make sure inline autofill is enabled
3. Open browser and go to a login page of your choosing 
4. Instead of inline outfill in the keyboard an popop in the brwoser will apear.

### FlorisBoard Version

floris board beta 0.4.0 rc2

### Install Source

F-Droid

### Device

Samsung A52s

### Android

One UI 6.0 (Android 14)

**Comment by lm41** [comment] 2024-09-17 20:26
Duplicate of #2542

**Closed by lm41** 2024-09-17 20:26 UTC
Labels: bug
