### ISSUE TITLE
Screenshot support for clipboard

### ISSUE THREAD

**Issue by MacaroonAlive2513** [florisboard/florisboard#2452] opened 2024-04-20 16:41 UTC
### Feature idea

The screenshots taken must be saved in clipboard. Gboard has this feature.
There is another implementation in Chrooma keyboard, the application requests access to the photos, and after granting permission, you simply insert your photos using the keyboard interface

**Comment by lm41** [comment] 2024-05-30 20:42
Thanks for your suggestion. It's already been suggested, so I'm closing this one as duplicate of #1761.

**Closed by lm41** 2024-05-30 20:42 UTC
Labels: proposal
