### ISSUE TITLE
Empty sticky action still takes space 

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#2033] opened 2022-08-29 22:36 UTC
#### Short description
When the sticky action is removed at the Reorder Actions screen, the space on the smartbar remains empty. It is not reused by the other smartbar actions. 

The smartbar setting is the default, Suggestions and Actions Shared.

#### Steps to reproduce
1. Tap the ... icon in the smartbar
2. Go to Reorder Actions
3. Remove the sticky action
4. Observe the smartbar

#### Environment information
- FlorisBoard Version: 0.4.0-alpha03 (89)
- Install Source: F-Droid
- Device: Mi 9T
- Android: LineageOS

**Comment by MisterY** [comment] 2022-08-29 22:38
I have to add - thank you for the relatively big update and the preparation work for the suggestions!

**Comment by patrickgold** [comment] 2022-08-29 22:52
Thanks for your bug report!

This is actually not a bug but fully intended, as I want to keep the symmetry of the candidates row. If I take away the empty space of a non-existent sticky action the candidate row/shared actions row hangs to the right, which looks weird.

I mean I could theoretically add a toggle for this (on a technical level really simple), but as my goal is to avoid to avoid a "togglenation", basically a state where there are so many toggles that you don't even know what toggle to use, I think I will let this be as it is now.

**Comment by MisterY** [comment] 2022-08-29 22:57
I understand your reasoning and it makes perfect sense for the suggestions. But the actions bar looks weird with an empty spot. 

As a side note, I also have Fleksy and their suggestions also hang to the right, interestingly.

**Comment by patrickgold** [comment] 2022-08-29 23:18
What I could do is the following for the no sticky action scenario:

For the candidate row it stays as it is, no sticky action means empty space. If the shared actions row is shown, the overflow button takes the sticky action space and the actions row can show 1 additional action.

If a sticky action is set nothing changes to the current behavior as of 0.4.0-alpha03. Would this solution be okay for you?

**Comment by MisterY** [comment] 2022-08-29 23:21
That makes sense to me. 

As a workaround, I've set a sticky action to use the space and the practical result is the same so not a deal breaker on my side. It is probably an edge case, anyway.

**Comment by patrickgold** [comment] 2022-08-29 23:46
Above linked commit/PR implements discussed behavior. Will be parts of v0.4.0-alpha04.

**Closed** 2022-08-31 18:16 UTC
Labels: proposal, proposal-accepted, area: smartbar
