### ISSUE TITLE
Composer either missing or malfunctioning since v0.3.14-beta6

### ISSUE THREAD

**Issue by HaneulCheong** [florisboard/florisboard#1478] opened 2021-12-30 07:35 UTC
#### Short description
FlorisBoard's composing input method, implemented through #866, seems either missing or malfunctioning since [v0.3.14-beta6](https://github.com/florisboard/florisboard/releases/tag/v0.3.14-beta06), causing incorrect outputs in some languages such as Korean.

I am opening this issue since I don't see it included in the "List of unavailable features".

#### Steps to reproduce
 1. Go to 'Languages & Layouts'
 1. Add 'Korean' subtype preset
 1. Type in the following order: [ㅎ][ㅏ][ㄴ][ㄱ][ㅡ][ㄹ]

 - Expected Output: 한글
 - Actual Output: ㅎㅏㄴㄱㅡㄹ

#### Environment information
- FlorisBoard Version: 0.3.14-beta6 ~ 0.3.14-beta8
- Install Source: GitHub
- Android: 11

**Comment by patrickgold** [comment] 2022-01-01 19:37
Thanks for your bug report!

This is true, composers are in the latest beta not fully working, because I haven't found a way yet to convert them to the new extension format, but this should be resolved before stable 0.4.0. Will assign it to the list of keyboard issues.

**Comment by HaneulCheong** [comment] 2022-01-02 09:24
Thank you for the reply. I guess I can keep using 0.3.13 until this is resolved.

As far as I can tell, FlorisBoard is currently the sole FOSS virtual keyboard with Korean support. Just wanted to add that I genuinely appreciate the team's effort.

**Comment by patrickgold** [comment] 2022-03-03 23:14
@HaneulCheong above linked PR re-implements composers, they can now be defined in any extension with serial type `ime.extension.keyboard`, by default they are in the extension package `org.florisboard.composers`.

If possible, could you please try out the debug artifact (installs separately) if the Hangul and/or Kana composer work as intended? I can only verify that it does something, but I don't speak Korean so I don't know if something is off during loading and interpretation of the input. Thanks in advance!

**Comment by Me0wzz** [comment] 2022-03-06 12:59
@patrickgold Hello, I am Korean florisboard user.
I used this [artifact-apk](https://github.com/florisboard/florisboard/actions/runs/1938893583) but, Hangul composer is not working.

#### Steps to reproduce
1. Go to 'Languages & Layouts'
 2. Add 'Korean' subtype preset
 3. Type in the following order: [ㅎ][ㅏ][ㄴ][ㄱ][ㅡ][ㄹ]


- Expected Output: 한글
* Actual Output: ㅎㅏㄴㄱㅡㄹ
*

**Comment by Me0wzz** [comment] 2022-03-06 13:06
Hello @patrickgold , I used this [artifact-apk](https://github.com/florisboard/florisboard/pull/1614) and It seems Hangul composer is not working.

Steps to reproduce is same as @HaneulCheong's.


* Expected Output: 한글
* Actual Output: ㅎㅏㄴㄱㅡㄹ

**Comment by patrickgold** [comment] 2022-03-06 15:07
@Me0wzz Could you please recheck the debug artifact that you didn't accidentally took one from another branch without the composer fix ( https://github.com/florisboard/florisboard/pull/1614/checks )? I just checked your given example and the Hangul composer behaved correctly (got the expected output you gave).

**Comment by Me0wzz** [comment] 2022-03-06 15:12
@patrickgold Oh, I installed different artifact.
Sorry for the confusion.

The compositer works properly on reimplement-composers build.

**Comment by patrickgold** [comment] 2022-03-06 15:14
Perfect, great to hear!

Will merge the fix into master then and release it as beta14 later today.

**Closed** 2022-03-06 15:15 UTC
Labels: bug, bug-confirmed, area: kbd-logic

**Comment by HaneulCheong** [comment] 2022-03-24 07:19
I completely forgot that I openned this... Thanks a lot for the fix!
