### ISSUE TITLE
Copied images are randomly rotated when pasting them

### ISSUE THREAD

**Issue by realpixelcode** [florisboard/florisboard#2363] opened 2024-01-10 19:22 UTC
#### Short description

When copying an image and pasting it, it's rotated after being sent. The issue happened both in Threema and Threema Libre, but I couldn't reproduce it with either other messengers or other keyboards. I have already reported this to the Threema [support](https://threema.ch/en/support-request?i_have_read_the_faq=1) ([*SUPPORT](https://threema.id/*SUPPORT)), but they said it's not a bug in Threema but in FlorisBoard instead.

https://github.com/florisboard/florisboard/assets/52963327/e3b6eff0-7a3f-45c8-bbbc-8f84d5a735c8

#### Steps to reproduce

1. Copy any image to the clipboard.
2. Open a Threema chat and paste the image from FlorisBoard.
3. The image is rotated.

#### Environment information

- FlorisBoard Beta Version: 0.4.0-alpha06
- Install Source: F-Droid
- Device: Fairphone 3
- Android: Android 12, /e/OS

**Comment by Kasi07** [comment] 2024-01-10 20:04
I can reproduce this in Version 0.3.16 too.

Environment information
-     FlorisBoard Beta Version: 0.3.16
-     Install Source: Github
-     Device: Pixel 7
-     Android: Android 14, GrapheneOS

**Comment by lm41** [comment] 2024-01-11 20:07
This is really weird. 
I can reproduce this in Version 0.4.0-alpha04 too.
Environment information
-     FlorisBoard Version: 0.4.0-alpha04
-     Install Source: Own Build
-     Device: Pixel 7 Pro
-     Android: Android 14, GrapheneOS

However, the image is rotated correctly in Signal, in MonoclesChat, in SchildiChat (Element) as well as when you click on the image in Threema and go to the image viewer.
In my opinion, this is most likely a Threema bug.

**Comment by chop-suey** [comment] 2024-01-12 10:33
I can also reproduce this.

- FlorisBoard Version: 0.4.0-alpha04
- Install Source: IzzyOnDroid
- Device: Samsung S20+
- Android: Android 13

As this does not happen with any other keybord i have tested my conclusion is that this is most likely both: a bug in floorisboard _and_ in threema. In some cases threema seems to only apply the rotation to the generated thumbnails (e.g. when the image is sent as a file). But there most be something odd with the images pasted by floorisboard.

**Comment by patrickgold** [comment] 2024-01-12 11:14
That really seems to be a Threema issue, as you can see in the message send preview the image is correctly formatted, from that point on FlorisBoard does not influence the image anymore, only the target app, in that case Threema

**Comment by chop-suey** [comment] 2024-01-12 11:22
As i happen to be quite familiar with the threema code i can confirm that the image is re-queried for thumbnail- and original-image creation (see https://github.com/threema-ch/threema-android/blob/main/app/src/main/java/ch/threema/app/services/MessageServiceImpl.java#L3967). 
(if not sent as a file, the "original"-image is also regenerated to respect image size settings and to remove metadata, to preserve privacy)

**Comment by mimiks** [comment] 2024-01-12 16:22
The problem lies in the ContentProvider returning random values for `MediaStore.Images.Media.ORIENTATION`.
Threema queries this value through the ContentResolver to determine the orientation as a fallback if ExifInterface returns an undefined orientation.
[https://github.com/threema-ch/threema-android/blob/8c5c50ec5e4a8905c0c7ac08b925da59d90a7a0a/app/src/main/java/ch/threema/app/utils/BitmapUtil.java#L484](url)

So, this could probably be fixed in Florisboard's ContentProvider.

**Comment by lm41** [comment] 2024-01-13 01:44
I've dropped a fix in #2369.

**Comment by lm41** [comment] 2024-01-13 08:52
> The problem lies in the ContentProvider returning random values for `MediaStore.Images.Media.ORIENTATION`.

The values weren't sooo random. It was the Id of the clipboard item. (The first element in the cursor object)

**Comment by lm41** [comment] 2024-03-02 18:30
Can you please test the changes of #2369 https://github.com/florisboard/florisboard/actions/runs/8116835937

**Comment by realpixelcode** [comment] 2024-03-02 20:18
Works fine for me – thank you! 🎉

**Closed** 2024-03-06 23:46 UTC
Labels: bug, area: clipboard
