### ISSUE TITLE
frequent lags

### ISSUE THREAD

**Issue by pdmidnh** [florisboard/florisboard#723] opened 2021-04-21 09:49 UTC
The app stops working very often.It just freezes.

**Comment by lawson85** [comment] 2021-04-21 11:00
> The app stops working very often.It just freezes.

This is not helpful to the developer at all. You need to tell them what you were doing when it crashed, what version of the keyboard and Android version, what settings you have. If it is related to OOM issues, they are fully aware of them. Also, sometimes when it crashes, you may be prompted with a send feedback button, try that so they get all the relevant logs to better diagnose the issues

**Comment by R4ygen** [comment] 2021-04-22 22:15
Could be a duplicate of #708, which is related to #677.

**Comment by patrickgold** [comment] 2021-04-24 01:31
Yes it is known that there's some major issues with OOM errors and performance. PR #734 (still experimental and in draft) is a major overhaul for the lyouting of the keyboard, which reduces the base RAM memory usage, allocates less objects to minimize stress on the CPU and RAM and also improve performance a bit. When the branch is complete and documented, I will release v0.3.11-beta02 and see if I broke anything while re-implementing and if beta users are seeing less OOM related crashes. Note that I will close this issue as a duplicate.

**Closed by patrickgold** 2021-04-24 01:31 UTC
Labels: bug
