### ISSUE TITLE
Copy-&cut-buttons have invalid state if not released

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#725] opened 2021-04-21 13:49 UTC
#### Disclaimer
This is just a visual bug. Functionality stays the same, and the visuals reset once the button is clicked again. 

#### Steps to reproduce
1. Go to any text-field.
2. Write something
3. Highlight any number of letters
4. Press and hold `Copy` or `Cut` in the copy&paste-bar
5. (Still holding the previous button) click and release any letter-key. **(see first screenshot)**
Now the text that was highlighted is gone, but you're still holding the `Copy`/`Cut` button.
6. When you release the `Copy`/`Cut` button, it will look like it still is held down. **(see second screenshot)**
7. You may now repeat this process for the other of the two buttons. **(see third screenshot)**

#### Screenshots
![fstuck1](https://user-images.githubusercontent.com/59611881/115564826-2185d300-a2b9-11eb-870b-7f04a2784a75.jpeg)

![fstuck2](https://user-images.githubusercontent.com/59611881/115564847-264a8700-a2b9-11eb-80c6-55e8b5efa7d2.jpeg)

![fstuck3](https://user-images.githubusercontent.com/59611881/115564866-2b0f3b00-a2b9-11eb-9ea7-f5f552932f93.jpeg)

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment] 2021-04-28 03:33
I've just found your bug report buried in the backlog, sorry about the late response here :) As #734 completely rewrites the rendering of the KeyboardView, I absolutely don't know if this issue is now fixed or not. Best we can do is to wait for the v0.311 release (which will happen after beta03 I think) and see if the issue is resolved for you!

**Comment by Glitchy-Tozier** [comment] 2021-04-28 05:42
Okay, I'll do my best to remember needing to test it!

**Comment by Glitchy-Tozier** [comment] 2022-01-25 07:30
Update: Now this behaviour makes the app crash :)

---

#### Environment information
- FlorisBoard Version: 0.3.14-beta08 (64)
- Device: Samsung SM-G960F
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1643095792213.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:947)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCut(EditorInstance.kt:631)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardManager.onInputKeyUp(KeyboardManager.kt:580)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>

**Comment by patrickgold** [comment] 2022-01-25 23:06
Hmm I cannot reproduce this bug, not the stuck key background nor a crash associated with this stuck background. Can you reproduce this crash only in a specific app or across all apps?

**Comment by Glitchy-Tozier** [comment] 2022-01-26 07:17
I could reproduce it in every app I tried.
- KISS launcher
- FF Focus
- Githo
- Signal
- Github
- Florisboard settings
(Although it's somewhat annoying to test there, the select-all key doesn't work, and neither does double-tapping. Had to use Shift+Space-swipe.)

**Comment by lm41** [comment] 2024-04-16 14:14
Hey there. I cannot reproduce this behavior in the latest beta version. Does the bug still occur there?

**Comment by Glitchy-Tozier** [comment] 2024-04-16 14:56
No, I can't reproduce anything mentioned here anymore.
Thank you for checking

**Closed** 2024-04-16 14:57 UTC
Labels: bug, bug-confirmed, area: kbd-logic
