### ISSUE TITLE
Floating Keyboard

### ISSUE THREAD

**Issue by NripPrajapat** [florisboard/florisboard#2484] opened 2024-05-26 06:00 UTC
### Feature idea

Add 'floating keybord' option. Whcih will help in writing when we use apps in landscape mode or in multiwindow situations or floating windows apps,  which most of the OEMs have now days. 

Not an option just to resize but to let it float anywhere on the screen and that should support resizing too.

It will save the whole screen and other apps to use it simply.

**Comment by lm41** [comment] 2024-05-26 13:11
Duplicate of #336

**Closed by lm41** 2024-05-26 13:11 UTC
Labels: proposal
