### ISSUE TITLE
Issue with newest version

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#1805] opened 2022-04-20 23:56 UTC
Hey guys. Last night I downloaded 0.3.15 and spent some time redoing my theme since it would import again. Luckily I was able to figure it out. Anyways Im having an issue where hitting the symbols key sometimes doesnt do anything. There has been a couple of times where Ive had to hide the keyboard and bring it back up for it to work. Also the state of shift/CAPS doesnt always change either. Sometimes it will appear lower case after a period but the next letter typed is actually capitalized. As well there are times when I hit shift and then the keyboard stays in CAPS but types normally.

**Comment by patrickgold** [comment] 2022-04-28 23:26
Thanks for your bug report!

This is a know issue, sadly I have not found the cause for it yet. Could be a bug in my logic, but also a bug in the UI library I use. As this is a duplicate of #1714 I will close this issue to keep the list of issues clean.

**Closed by patrickgold** 2022-04-28 23:26 UTC
Labels: bug
