### ISSUE TITLE
Crashed On Private browser

### ISSUE THREAD

**Issue by rockerritesh** [florisboard/florisboard#1482] opened 2022-01-04 00:53 UTC
#### Short description
Initially I was using experimental auto suggestion in that case I open private browser in which I have disabled auto search completion in that case it crash.
Next time I off experimental auto suggestion, but its again crash.

#### Steps to reproduce
1. Go to 'FlorisBoard setting enable auto suggestion while typing
2. Open any Browser in private or for mode
3. Type something, then try to erase it, you will 
4. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi Redmi 8
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1641257019339.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 8 free bytes and 8B until OOM, target footprint 268435456, growth limit 268435456
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.<init>(temp_suggestion_code.kt:187)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment] 2022-03-19 10:36
This is a classic OOM crash caused by the old word suggestions. The next stable releases won't have word suggestions until the 0.4.0 development begins, so this issue should also not occur. Closing this issue to keep the list of issues cleaner.

**Closed by patrickgold** 2022-03-19 10:36 UTC
Labels: bug
