### ISSUE TITLE
Keyboard height changes when switching between ABC layout & ?123 layout with "Number row" enabled

### ISSUE THREAD

**Issue by unilock** [florisboard/florisboard#1561] opened 2022-02-10 04:20 UTC
#### Short description
With the "number row" enabled (above the letters & below the smartbar), the keyboard will change in height when switching between the letter mode (ABC) and number mode (?123). (Sorry, it's late and I'm not totally sure what these modes are called...)

<img src="https://user-images.githubusercontent.com/11802133/153335574-fce9a195-62fd-45b5-a813-96d06079d6b4.png" width=25%> <img src="https://user-images.githubusercontent.com/11802133/153335588-95a8b989-e896-441b-9162-b9f3d54ea086.png" width=25%>

In version 0.3.13 (and likely earlier), the height of the keys themselves increased when switching from ABC -> ?123. I'm not sure whether this approach would still be viable, given all the changes with theming and whatnot.

<img src="https://user-images.githubusercontent.com/11802133/153335950-71b691de-76a8-4dee-afaf-9dcf52e8cb6c.png" width=25%> <img src="https://user-images.githubusercontent.com/11802133/153335956-c57d716e-fdc4-409d-9249-883f7b2305da.png" width=25%>

I can only recall the height change being an issue in Termux, in which it lead to some graphical corruption of the terminal interface. I don't exactly recall the circumstances; it's likely that an ncurses UI was involved, as the program isn't particularly fond of terminal size changes.

Other than that, it's just mildly annoying...

#### Steps to reproduce
1. Enable "Number row" under "Keyboard" in settings
2. Open the keyboard
3. Switch between ABC mode and ?123 mode
4. The keyboard height changes

#### Environment information
- FlorisBoard Version: 0.3.14-beta10
- Install Source: F-Droid (IzzyOnDroid repo)
- Device: Google Pixel 4a
- Android: 12 (build SQ1A.220105.002)

**Comment by patrickgold** [comment] 2022-03-28 19:42
Forgot to close this issue when I fixed this previously. See #1568, has been fixed in 0.3.15-beta01. Closing thus.

**Comment by Turbotomate** [comment] 2022-05-03 12:55
Sadly i have to ask for reopening of this issue @patrickgold 
I had the problem with 0.3.14 aswell and it was fixed with 0.3.15. But today i suddenly realized that the height of the keyboard changes again, when switching between letter- and special character-screens. I started investing the problem and it fixed itself after i opened the app itself (not just the keyboard) once. Since then all is fine again but the problem was there again for some hours.

**Comment by Turbotomate** [comment] 2022-06-02 09:48
It happened again several times since I mentioned it here. The problem just suddenly appears and disappears again after a short time.

**Comment by patrickgold** [comment] 2022-06-02 17:34
Re-opening but cannot reproduce this issue using the latest beta 0.3.16-beta04.

**Comment by Turbotomate** [comment] 2022-06-08 12:32
> Do you use a 4-row or 5-row character layout? (excluding the additional number row)

I am using the German (QWERTZ) layout which has 4 rows on the character page and 3 rows on the special characters page.

**Comment by Turbotomate** [comment] 2022-06-12 15:20
https://user-images.githubusercontent.com/64365398/173240007-74018712-bbf7-4d14-bc5e-9fa9246fd607.mp4

@patrickgold Here is a video of the problem. It happens about once every other day. Maybe i'll try the 0.3.16 beta...

**Comment by Turbotomate** [comment] 2022-07-05 16:51
@patrickgold Didnt happen once with 0.3.16. i think this can be closed now.

**Comment by tsiflimagas** [comment] 2022-07-05 18:08
Ok, should it happen again, we can reopen the issue again.

**Comment by Turbotomate** [comment] 2022-08-06 12:24
@tsiflimagas @patrickgold This happened again today with 0.3.16. Had it happen some days ago aswell. So the issue is still there and should be reopened. But happens lot less frequently than in 0.3.15.

**Comment by sudowesu** [comment] 2022-08-13 14:03
I also realised that the key borders gets larger when the Western (Addition symbols) enabled (even though the size of the keyboard doesn't actually change)
![Screenshot_20220813-165512_FlorisBoard Beta.png](https://user-images.githubusercontent.com/67051709/184497540-fea985e8-22aa-4800-afa4-8e2822160f83.png)
![Screenshot_20220813-165515_FlorisBoard Beta.png](https://user-images.githubusercontent.com/67051709/184497614-2f8c0a94-4d32-425d-a8a0-2c74ab389321.png)
Is this related with this issue? And was it supposed to happen?

**Comment by patrickgold** [comment] 2022-08-13 16:25
>  Is this related with this issue? And was it supposed to happen?

It is related, because the key borders derive their height from the general height and the row count of the layout, however somewhere in there there is a bug which messes this up for non-standard layout heights. I need to look into this again but currently do not know when exactly I will have time to do so.

**Comment by patrickgold** [comment] 2022-08-21 21:08
@Turbotomate So for the Smartbar actions rework in #2012 (and especially for the overflow menu) I had to adjust the spacing logic, with this I also adjusted and fixed the height calculation once again. So now the height is always calculated based on the number of rows in the characters layout, and symbols, symbols2 and numericAdvanced follow suit. If the symbols layout has less rows than characters its keys will grow (although not fully occupy each row's height, as this looks weird). I hope that this now finally fixes this bug. If you want you can try out the debug artifact of linked PR and see for yourself or wait for alpha03 in a few days.

**Comment by tsiflimagas** [comment] 2022-08-21 21:53
The issue with the "Western (Additional symbols)" layout was reported in #1946, so that should be closed too when the PR is merged.

**Comment by patrickgold** [comment] 2022-08-21 23:15
> The issue with the "Western (Additional symbols)" layout was reported in https://github.com/florisboard/florisboard/issues/1946, so that should be closed too when the PR is merged.

Yup that's correct thanks for the reminder!

**Closed** 2022-08-23 21:40 UTC
Labels: bug, area: kbd-ui
