### ISSUE TITLE
Shift behave as caps lock 

### ISSUE THREAD

**Issue by laraib07** [florisboard/florisboard#1219] opened 2021-09-02 12:51 UTC
#### Short description
Earlier (v3.12) when i press shift it capitalize for one letter as intended but now(v3.13) shift behave mostly as caps lock.

#### Steps to reproduce
1. Press shift
2. type anything , it stays capital even after one character.
3. press shift again, nothing happens
4. if you type some characters and then press shift, it will still do nothing.

#### Environment information
- FlorisBoard Version: 3.13
- Install Source: fdroid
- Device: realme 2 pro
- Android: 11, aosp extended

**Comment by KLaurence** [comment] 2021-09-02 14:37
Do you use [Termux](https://f-droid.org/en/packages/com.termux)? If you do, does this occur in Termux? Does this also occur in apps other than Termux?

If it occurs in Termux but doesn't occur in other apps, this issue might be a duplicate of #1019.

**Comment by laraib07** [comment] 2021-09-02 14:40
Yes I do, and just verified it only occur in termux.

**Comment by KLaurence** [comment] 2021-09-02 14:45
I'm not a contributor, but I think this issue should be closed, as it's a duplicate. You can still comment in #1019, though.

**Closed** 2021-09-02 14:46 UTC
Labels: bug
