### ISSUE TITLE
crash issue

### ISSUE THREAD

**Issue by paritoshs257** [florisboard/florisboard#1491] opened 2022-01-08 05:24 UTC
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi Redmi Note 8 Pro
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1641614310414.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 402653184, growth limit 402653184
	at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
	at android.os.Binder.execTransact(Binder.java:992)

```
</details>

**Comment by Glitchy-Tozier** [comment] 2022-01-08 09:23
1. When posting bug-reports, please make sure to fill out the full bug-template.
2. This is a duplicate of #1268.
The crashes you experience are OutOfMemory issues, which are caused by word suggestions. The current workaround is to disable word suggestions if they cause trouble and wait for version 0.3.15, where Patrick will re-implement them to make sure this specific crash does not occur again.

**Closed by Glitchy-Tozier** 2022-01-08 09:23 UTC
Labels: bug, duplicate
