### ISSUE TITLE
lagged then stayed on screen and crashed

### ISSUE THREAD

**Issue by NotDusan** [florisboard/florisboard#751] opened 2021-04-24 10:48 UTC
It crashed. Error:
~~~ 1619261112614.stacktrace ~~~

java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 0 free bytes and 0B until OOM, target footprint 268435456, growth limit 268435456
	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.<init>(PopupExtendedView.kt:38)
	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.<init>(PopupExtendedView.kt:77)
	at dev.patrickgold.florisboard.ime.popup.PopupExtendedView.<init>(PopupExtendedView.kt:76)
	at dev.patrickgold.florisboard.ime.popup.PopupManager.<init>(PopupManager.kt:78)
	at dev.patrickgold.florisboard.ime.text.key.KeyView.<init>(KeyView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.buildLayout(KeyboardView.kt:121)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.setComputedLayout(KeyboardView.kt:67)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.addKeyboardView(TextInputManager.kt:147)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$addKeyboardView$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by patrickgold** [comment] 2021-04-24 10:57
Duplicate of #677 and many other issues. Parts of this error will be addressed by #734.

**Closed by patrickgold** 2021-04-24 10:57 UTC
