### ISSUE TITLE
Number key pop up do not match the number key

### ISSUE THREAD

**Issue by Yurieaijoker** [florisboard/florisboard#1566] opened 2022-02-12 03:09 UTC
#### Short description
The pop up of the number keys do not match the size of the number key ( see the attached photo)

#### Steps to reproduce
1. Go to symbols
2. Click on dedicated number key
3. Click any number
4. The pop up does not match the size of the key.

It would be nice to have an option to disable pop ups on big number keys. Thank you.

#### Environment information
- FlorisBoard Version: 0.3.14-debug (65)
- Install Source: Github
- Device: Huawei Nova 7se
- Android: 10
![Screenshot_20220212_110350_com google android googlequicksearchbox](https://user-images.githubusercontent.com/93813352/153694278-90150ff1-5ac9-48b2-b7fa-25a9b5e9bc9a.jpg)

**Comment by Glitchy-Tozier** [comment] 2022-02-13 08:40
Hi and thank you for taking the time to write this bug-report!
There already exists an issue documenting this problem, which is why I'll close this one as a duplicate of #1044. Please continue the conversation on this topic there.

**Closed by Glitchy-Tozier** 2022-02-13 08:40 UTC
Labels: bug, duplicate
