### ISSUE TITLE
Keyboard Covers Input Field.

### ISSUE THREAD

**Issue by Penguin-Guru** [florisboard/florisboard#1747] opened 2022-04-04 20:24 UTC
#### Short description
In some apps (e.g. Signal, Element), and only in landscape mode, the keyboard covers the input field so text can not be read while the keyboard is open. I only noticed this after upgrading to 0.3.14, but I can't say for sure that it was not present before then. Reducing the keyboard height and width might work around the issue, I haven't tried that yet, but clearly it should not be necessary. Other input fields, such as the text field in the FlorisBoard app, do not have this issue. Opening the keyboard in landscape and switching to landscape with the keyboard open produce the same results.

#### Environment information
- FlorisBoard Version: 0.3.14 (75)
- Install Source: F-Droid
- Device: Pixel 5
- Android: 12, Graphene

**Comment by tsiflimagas** [comment] 2022-04-04 20:27
Thanks for your bug report! This seems to be a duplicate of the now closed #1711. You can try the artifact from #1734 and see if it's fixed for you too.

**Comment by Penguin-Guru** [comment] 2022-04-04 20:58
Ok, sorry I failed to find that. I will go ahead and close this. I'm not sure what artifact you mean but I don't mind waiting a few days since it seems the release is due soon. Thank you. :)

**Closed** 2022-04-04 20:58 UTC
Labels: bug, area: kbd-ui
