### ISSUE TITLE
deepl built-in translator

### ISSUE THREAD

**Issue by andsofine** [florisboard/florisboard#1865] opened 2022-05-20 22:42 UTC
the only thing besides swipes and auto-correct that keeps me from leaving gboard is the built-in translator. I think deepl would be a good option

**Comment by ThatOneCalculator** [comment] 2022-05-21 16:19
The problem is DeepL is a non-free network service and has limited API keys, either everyone would have to register for a DeepL API key or the FlorisBoard devs would have to pay >$100/yr

**Comment by andsofine** [comment] 2022-05-21 21:10
> The problem is DeepL is a non-free network service and has limited API keys, either everyone would have to register for a DeepL API key or the FlorisBoard devs would have to pay >$100/yr

 any other suggestions?

**Comment by GoRaN909** [comment] 2022-05-21 23:00
> 
> any other suggestions?

I prefer Google translate it's support too many languages and i think the API is free of charge forever :)

**Comment by ThatOneCalculator** [comment] 2022-05-21 23:39
> I prefer Google translate it's support too many languages and i think the API is free of charge forever :)

The whole point of a project like this is to be *freed* from Google services.

**Comment by GoRaN909** [comment] 2022-05-21 23:57
> > I prefer Google translate it's support too many languages and i think the API is free of charge forever :)
> 
> The whole point of a project like this is to be _freed_ from Google services. Either use [LibreTranslate](https://libretranslate.com/) (or another similar project) or don't use a translator at all.

And why NOT? the only reason I liked to use FlorisBoard as my default daily keyboard is the features and user interface is very close to GBoard  idk what's the problem if we have the Google Translator just like GBoard :/ You knew that the [LibreTranslate](https://libretranslate.com/) is just support some European languages and the Google Translate is support more that 130 languages :)

**Comment by ThatOneCalculator** [comment] 2022-05-22 00:19
Why not? Because it's a ***Google service***. This is a free and open source project.

**Comment by GoRaN909** [comment] 2022-05-22 01:23
> Why not? Because it's a _**Google service**_. This is a free and open source project.

Hahaha you are infected by **Googlophobia** LoL :)

**Comment by ThatOneCalculator** [comment] 2022-05-22 01:55
It's not "Googlephobia" it's not wanting to be tracked and unknowingly be using a non-free network service.

**Comment by andsofine** [comment] 2022-05-22 08:50
I don't really like the idea of ​​google translate. I don't really like LibreTranslate either.
on the other hand, you can leave the choice of the method of translation. 
Offline translation would be nice, do you have any ideas?

**Comment by patrickgold** [comment] 2022-05-22 09:36
Word translation is something that may be added to FlorisBoard if there's a viable way of doing so preferably fully offline. And even if we end up choosing an online service, Google Translate would be dead last in my list of choices. This here is an open-source privacy-respecting keyboard, so giving your translation data to Google kinda defeats the purpose of this keyboard in the first place.

> The problem is DeepL is a non-free network service and has limited API keys, either everyone would have to register for a DeepL API key or the FlorisBoard devs would have to pay >$100/yr

More like per 2-3 months looking at their pricing. Also the exact price heavily depends on how much users translate, so it is a very unpredictable source of expense. Although one must say for the languages they support, the translation quality is damn good when using the web interface for quick translation.

> and user interface is very close to GBoard idk what's the problem

Yes the point of FlorisBoard is to have some kind of cleanness and structure like Gboard (because looking only at that Gboard is a great keyboard), HOWEVER without collecting and aggregating any user data for ads or other purposes, like Google does.

---

If you have a good idea for an offline open-source translator or just in general about the implementation, please post it in above linked issue. This way we have all translation-related ideas in one place. I will close this issue thus.

**Closed by patrickgold** 2022-05-22 09:36 UTC
Labels: proposal
