### ISSUE TITLE
Feature request to get T9 search option on numeric keyboard on florisboard beta end 

### ISSUE THREAD

**Issue by Gottarocket** [florisboard/florisboard#878] opened 2021-05-15 04:35 UTC
I use open contacts and have T9 option selected which comes handy when searching but florisboard beta doesnt show alphabets along with numbers  would be better to add it

**Comment by Glitchy-Tozier** [comment] 2021-05-15 08:12
Hi, could you please also put the request in the title instead of "Feature Request"?

**Comment by patrickgold** [comment] 2022-03-24 22:51
Probably duplicate of #355. Closing thus.

**Closed** 2022-03-24 22:51 UTC
Labels: duplicate, proposal

**Comment by STPKITT** [comment] 2022-03-25 01:33
Hm, is this really a duplicate? With all other keyboard apps I came across the dialer keyboard always seemed to be an independent component from the keyboard that would show up in all other apps. While the keyboard apps all seem to have a dialer keyboard with letters that keyboard though can't be accessed anywhere except when in the telephone app. So I always thought that was an Android thing/limitation.
What I assume is also different between such a dialer keyboard and a universal one with the same layout is that the dialer keyboard would directly translate letters into numbers while the T9 keyboard this issue is about would need to do much more.

**Comment by patrickgold** [comment] 2022-03-25 06:49
Well there are always at least two dialer pads on your system:

One is integrated into your system Phone app, which allows you to directly make calls too. It also has helper letters for each digit. It is completely independent from the keyboard.

The other is the keyboard-dependent dialer layout, which #355 references. It shows up for input fields with type "PHONE". This is mostly used either in telephone search fields or in forms when entering your telephone number. #1693 implements letters for this layout, which is useful when you remember phone numbers by letters.

If this issue was about the actual T9 layout though (which is a keyboard layout similar to the phone dialer but usable in all text fields) it would still be a duplicate, namely of issue #165.
