### ISSUE TITLE
No Keyspacing for Primary symbol layout (Western (Additional symbols))

### ISSUE THREAD

**Issue by MeinChef** [florisboard/florisboard#2181] opened 2023-03-28 10:21 UTC
#### Short description
The keyspacing for the symbols with the "Western (Additional symbols)" primary symbol layout is nonexistent, as well as the keys themselves are not the height they should be. See images below.
![ScreenshotFlorisboard_Symbols](https://user-images.githubusercontent.com/126389277/228204697-4be14872-4690-43cf-998a-c8746c634dfa.jpg) (clicked the `?123` button)
![ScreenshotFlorisboard_Keyboard](https://user-images.githubusercontent.com/126389277/228205074-ae8a789e-ed87-42cb-a464-207f39d21984.png)

#### Steps to reproduce
Select for "Symbols primary layout" in "Languages & Layouts" "Western (Additional symbols)

#### Environment information
- FlorisBoard Version: 0.3.16 (86)
- Install Source: Fdroid
- Device: Xiaomi Note 11 / Honor 10
- Android: 11 / 10

```
======= SYSTEM INFO =======
Time                : 2023-01-30T09:33:21.611Z
Manufacturer        : Xiaomi
Model               : 2201117TY
Product             : spesn_eea
Android             : 11 (cn=R sdk=30) [RKQ1.211001.001 test-keys]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 2.59 GiB (46.86% used, 5.52 GiB max)
Font scale          : 1.0
Locales             : en-GB

======= APP INFO =======
Package             : dev.patrickgold.florisboard
Name                : FlorisBoard
Version             : 0.3.16 (86)
Build type          : release
Build commit hash   : null
Java heap memory    : 17.92 MiB (7.00% used, 256.00 MiB max)
Native heap memory  : 37.36 MiB (95.25% used, 39.22 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : true
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : false

======= LOGCAT =======
--------- beginning of system
01-30 10:32:13.882  5126  5126 E MQSEventManagerDelegate: failed to get MQSService.
01-30 10:32:13.882  5126  5126 W MQSEventManagerDelegate: registerApplicationScoutThread getMQSService null
01-30 10:32:13.882  5126  5126 W ActivityThread: registerApplicationScoutThread result:false
01-30 10:32:13.920  5126  5126 I ForceDarkHelper: ForceDarkConfigInfo: null
--------- beginning of main
01-30 10:32:21.916  5126  5146 I old.florisboar: ProcessProfilingInfo new_methods=282 is saved saved_to_disk=1 resolve_classes_delay=8000
01-30 10:32:42.993  5126  5126 D FrameIndicator: support status: 1 0x79ee759018 0x79ee7594c4
01-30 10:32:42.996  5126  5216 I AdrenoGLES-0: QUALCOMM build                   : 5eaa426211, I07ee46fc66
01-30 10:32:42.996  5126  5216 I AdrenoGLES-0: Build Date                       : 10/08/21
01-30 10:32:42.996  5126  5216 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.16
01-30 10:32:42.996  5126  5216 I AdrenoGLES-0: Local Branch                     : 
01-30 10:32:42.996  5126  5216 I AdrenoGLES-0: Remote Branch                    : 
01-30 10:32:42.996  5126  5216 I AdrenoGLES-0: Remote Branch                    : 
01-30 10:32:42.996  5126  5216 I AdrenoGLES-0: Reconstruct Branch               : 
01-30 10:32:42.996  5126  5216 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
01-30 10:32:42.996  5126  5216 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
01-30 10:32:43.003  5126  5216 I AdrenoGLES-0: PFP: 0x016ee197, ME: 0x00000000
01-30 10:32:43.033  5126  5216 E LB      : fail to open file: No such file or directory
01-30 10:32:43.218  5126  5139 I old.florisboar: Background concurrent copying GC freed 485626(14MB) AllocSpace objects, 35(6996KB) LOS objects, 49% free, 14MB/28MB, paused 107us total 143.421ms
01-30 10:32:50.555  5126  5126 V MiuiFrameworkFactory: get AllImpl object = android.common.MiuiFrameworkFactoryImpl@bb71363
01-30 10:32:50.558  5126  5126 W MirrorManager: this model don't Support
01-30 10:33:16.786  5126  5143 D AnrScout: AppScoutStateMachine created
01-30 10:33:16.794  5126  5126 D DecorView[]: getWindowModeFromSystem  windowmode is 1
01-30 10:33:16.829  5126  5126 D FrameIndicator: support status: 1 0x79ea915018 0x79ea9154c4
01-30 10:33:16.833  5126  5216 E LB      : fail to open file: No such file or directory
01-30 10:33:17.222  5126  5126 D CompatibilityChangeReporter: Compat change id reported: 150939131; UID 10277; state: ENABLED
```

**Comment by tsiflimagas** [comment] 2023-05-20 15:28
Thanks for your bug report! This seems like a duplicate of #1561, which has actually been fixed in v0.4.0-alpha03.

**Closed by tsiflimagas** 2023-05-20 15:28 UTC
Labels: bug
