### ISSUE TITLE
Change selected text to lowercase or uppercase when shift is pressed

### ISSUE THREAD

**Issue by notBradPitt** [florisboard/florisboard#2128] opened 2022-12-04 21:49 UTC
I think it would be useful if you can change the selected text to lowercase or uppercase, like in Gboard

* normal text will look like this
* If A Text Is Selected And Shift Is Pressed, It Will Look Like This
* IF THE BUTTON IS PRESSED TWICE (CAPS LOCK), IT WILL LOOK LIKE THIS

**Comment by KLaurence** [comment] 2022-12-05 11:14
This might be a duplicate of #759 or #804.

**Comment by KLaurence** [comment] 2022-12-05 11:29
Regarding the capitalization, I tested Gboard and the general capitalization stages that Gboard uses are:

1. (Previous irregular capitalization)
2. All lowercase
3. First letter uppercase
4. All uppercase

The cycle starts at the stage that the current text fits with. Stage 1 is always excluded unless the cycle starts at stage 1. For example, `Hello > HELLO > hello > Heo` is `3 > 4 > 2 > 3` (1 is always skipped) but `hEllo > hello > Hello > HELLO > hEllo` is `1 > 2 > 3 > 4 > 1` (1 is always included).

Gboard also seems to remember the "irregular capitalization" stage of the capitalization even after the text is unselected and reselected.

These might be important if it turns out that Florisboard will adopt Gboard's behavior  if Gboard's behavior will be copied in the future.

**Comment by tsiflimagas** [comment] 2023-05-22 12:11
Indeed this is a duplicate. Thanks anyway!

**Closed by tsiflimagas** 2023-05-22 12:11 UTC
Labels: duplicate, proposal, area: kbd-logic
