### ISSUE TITLE
Keyboard  pug

### ISSUE THREAD

**Issue by toniguy2018** [florisboard/florisboard#1294] opened 2021-09-28 10:09 UTC
~~~ 1632823637221.stacktrace ~~~

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.biz2.nowfloats/com.nowfloats.Analytics_Screen.VmnCallCardsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.framework.pref.TokenResult.getToken()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7091)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.framework.pref.TokenResult.getToken()' on a null object reference
	at com.nowfloats.util.Utils.getAuthToken(Utils.java:461)
	at com.nowfloats.util.Utils$2.intercept(Utils.java:498)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:273)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy34.trackerCalls(Unknown Source)
	at com.nowfloats.Analytics_Screen.VmnCallCardsActivity.getCalls(VmnCallCardsActivity.java:325)
	at com.nowfloats.Analytics_Screen.VmnCallCardsActivity.onCreate(VmnCallCardsActivity.java:151)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
	... 11 more

**Comment by patrickgold** [comment] 2021-09-28 17:35
This crash does not contain any FlorisBoard related calls or package name, are you sure this is a crash caused by FlorisBoard? Will close this issue as it contains too little info, if you can provide sufficient info so I can investigate this crash we can reopen it.

**Closed by patrickgold** 2021-09-28 17:35 UTC
