### ISSUE TITLE
Improve Error-Log

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#685] opened 2021-04-15 11:57 UTC
@patrickgold Is there some way to automatically add device information, app version etc. to the bottom of the error log?

This would improve the quality of many future crash-issues tremendously.

**Comment by patrickgold** [comment] 2021-04-15 15:14
There sure is (even if not 100% exact for the device model names) and in the light of the current bug report quality I think it would bring many benefits. Will add it to my todo list!

**Comment by Glitchy-Tozier** [comment] 2021-04-15 16:02
> and in the light of the current bug report quality I think it would bring many benefits.

That's exactly what made me think of the proposal :smile:

Just out of curiosity, where do you create the log? I'm not quite sure where to look in the app's file structure.

**Comment by patrickgold** [comment] 2021-04-15 17:48
> Just out of curiosity, where do you create the log?

I am not creating the log (The JVM - Java Virtual Machine on Android is doing it), just catching and saving it to a temporary file in the local app directory until the crash dialog UI is shown.

**Comment by patrickgold** [comment] 2021-04-15 17:52
Your question now got me an idea though: for the debug APK, I am writing log messages to the terminal so I can read values and check behaviors better in Android Studio. Maybe it is worth to build a util class which allows to enable debug logs also in the beta and release versions (if you explicitly enable it), which then logs the enabled parts to a temp file and the user can then paste the log on GitHub. These logs often times have much more valuable data, especially if its a bug which doesn't involve a crash, like state bugs and so on. What do you think of this idea?

**Comment by Glitchy-Tozier** [comment] 2021-04-15 18:09
I think the deciding factor is usability. The problematic crash-reports seem to be coming from people that are pretty new to GitHub or are too lazy to read the template.
If you find a way to implement those logs in a way that doesn't force those people to perform extra steps, it should be helpful. 

Turning on some abstract log **even before the app crashes** doesn't sound like a feasible request if you want those people's reports to improve.
Therefore I think this change might still improve **some things** (reports from experienced users), but I think it won't do much in helping with this issue.

#### Summary:
1. My original proposal improves sloppy error-reports
2. Your new idea improves error-reports from dedicated (or experienced) users

You probably know best, in which of those two (or even both) it's worthwhile to invest your time.

**Comment by patrickgold** [comment] 2021-04-15 18:22
> My original proposal improves sloppy error-reports

Never said that I won't implement your idea - my idea would be kinda an addition.

> Your new idea improves error-reports from dedicated (or experienced) users

This is indeed true. I think my idea is especially useful for things like the flashing keyboard, etc. Bugs that are absolutely not reproducible for me and then I can ask the issue reporter to manually enable logging for a certain category and upload the log to GitHub, which can assist me in finding the bug.

> too lazy to read the template

Sadly this is true. I've updated the bug report template yesterday and it says explicitly that  OutOfMemory errors are known and should not be posted - yet still we have new OOM issues.

> If you find a way to implement those logs in a way that doesn't force those people to perform extra steps, it should be helpful.

Nope, because creating and saving debug logs decreases performance, takes away disk space and is used by like 0.01% of users.

**Comment by Glitchy-Tozier** [comment] 2021-04-15 18:51
>Never said that I won't implement your idea - my idea would be kinda an addition.

I know I know :)

>Bugs that are absolutely not reproducible for me and then I can ask the issue reporter to manually enable logging for a certain category and upload the log to GitHub, which can assist me in finding the bug.

Exactly. So it's up to you to decide whether it's worth your time to implement this (no idea how often you face that problem)

> yet still we have new OOM issues.

I fear this'll keep happening until the crashes stop happening 😅

**Comment by patrickgold** [comment] 2021-04-17 12:29
@Glitchy-Tozier Above PR improves the debug logging and the crash utility. The error log now contains more info to the environment and features enabled and also formats the stacktraces better. For more info see the PR itself. Will be released in the next beta v0.3.11-beta02.

**Closed** 2021-04-18 13:05 UTC
Labels: proposal, proposal-accepted
