### ISSUE TITLE
FlorisBoard hangs when disabling smartbar

### ISSUE THREAD

**Issue by f1reflyyyylmao** [florisboard/florisboard#825] opened 2021-05-07 11:50 UTC
#### Short description
When disabling the smartbar trying to use the keyboard seems to get it stuck in a loop, but it doesn't crash. I tried getting a logcat output but I don't see any messages regarding florisboard. My processor gets hot. 

#### Steps to reproduce
1. Go to the FlorisBoard settings
2. Turn off the smartbar
3. Try opening the keyboard
4. See the keyboard not appear and your phone start to heat up 

#### Environment information
- FlorisBoard Version: v0.3.11-beta04
- Install Source: F-Droid Izzysoft repo
- Device: Oneplus 5
- Android: LineageOS for microg, Android 11

**Comment by Glitchy-Tozier** [comment] 2021-05-07 12:22
There should be some new setting that lets you display used memory. Could you turn that option on and share what happens there when you reproduce the bug?

**Comment by f1reflyyyylmao** [comment] 2021-05-07 12:32
I tried, but it doesn't show anything because the keyboard doesn't appear in the first place after enabling the setting and returning to an input field unfortunately. The app freezes as well, I have to go to the system settings and kill the app in order to be able to turn the setting off again.

**Comment by patrickgold** [comment] 2021-05-07 15:42
Thanks for your bug report! Just tested it out and can fully reproduce this bug! Will investigate into this.

**Comment by f1reflyyyylmao** [comment] 2021-05-07 15:47
Always glad to be of service, thank you for looking into this!

**Comment by patrickgold** [comment] 2021-05-08 13:31
Above PR is a fix for the Smartbar infinite loop bug. The cause was an infinite bug in the text size calculation when either the width or height of a layout were 0px (when disabling the Smartbar the height is 0px), this has now been patched out. With fixing this many reports of the keyboard not disappearing may also have been fixed, but only time and feedback will tell if this is indeed the case. Thanks again for reporting! The changes will be released in beta05 in a few minutes.

**Closed** 2021-05-08 13:35 UTC
Labels: bug, bug-confirmed, priority-1-high
