### ISSUE TITLE
Exception on delete word

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#2034] opened 2022-08-29 23:10 UTC
Setting the long-press on delete button to be Delete Word. Then pressing the Delete button. 
Happened in the settings screen, testing the keyboard settings in the provided text box, with one word typed and the cursor after it. 

#### Environment information
- FlorisBoard [0.4.0-alpha03](https://github.com/florisboard/florisboard/releases/v0.4.0-alpha03) (89)
- Device: Xiaomi Mi 9T (davinci)
- Android: 10 (cn=Q sdk=29)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-08-29T23:07:10.982Z
Manufacturer        : Xiaomi
Model               : Mi 9T
Product             : davinci
Android             : 10 (cn=Q sdk=29) [lineage_davinci-userdebug 10 QQ3A.200805.001 10039217]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 4.22 GiB (77.37% used, 5.46 GiB max)
Font scale          : 1.0
Locales             : en-AU

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-alpha03 (89)
Build type          : beta
Build commit hash   : 26650d2a00d509efbbd58bafa8606ba11bc5961f
Java heap memory    : 6.92 MiB (2.70% used, 256.00 MiB max)
Native heap memory  : 21.70 MiB (81.52% used, 26.62 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : true

```
</details>

<details>
<summary>1644682686089.stacktrace</summary>

```
java.lang.NullPointerException
	at dev.patrickgold.florisboard.app.ui.settings.advanced.ComposableSingletons$RestoreScreenKt$lambda-1$1$2$3.invoke(RestoreScreen.kt:300)
	at dev.patrickgold.florisboard.app.ui.settings.advanced.ComposableSingletons$RestoreScreenKt$lambda-1$1$2$3.invoke(RestoreScreen.kt:256)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at dev.patrickgold.florisboard.app.ui.components.FlorisCardsKt.FlorisOutlinedBox-wK_Y8yA(FlorisCards.kt:453)
	at dev.patrickgold.florisboard.app.ui.components.FlorisCardsKt.FlorisOutlinedBox-wK_Y8yA(FlorisCards.kt:203)
	at dev.patrickgold.florisboard.app.ui.settings.advanced.ComposableSingletons$RestoreScreenKt$lambda-1$1$2.invoke(RestoreScreen.kt:253)
	at dev.patrickgold.florisboard.app.ui.settings.advanced.ComposableSingletons$RestoreScreenKt$lambda-1$1$2.invoke(RestoreScreen.kt:208)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2547)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:722)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>

<details>
<summary>1661814427799.stacktrace</summary>

```
java.lang.IllegalArgumentException: offset(-1) is out of bounds [0, 0]
	at androidx.compose.ui.text.MultiParagraph.requireIndexInRangeInclusiveEnd(MultiParagraph.kt:9)
	at androidx.compose.ui.text.TextLayoutResult.getWordBoundary--jx7JFs(TextLayoutResult.kt:2)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrevWordOffset(TextPreparedSelection.kt:4)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$5.invoke(TextFieldKeyInput.kt:5)
	at androidx.compose.foundation.text.selection.TextFieldPreparedSelection.deleteIfSelectedOr(TextPreparedSelection.kt:3)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:95)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke(TextFieldKeyInput.kt:28)
	at androidx.compose.ui.input.key.KeyInputModifier.propagateKeyEvent-ZmokQxo(KeyInputModifier.kt:3)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:24)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:453)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1839)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3971)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(Unknown Source:0)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:4)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5580)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5448)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5008)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4974)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5114)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4982)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5171)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5008)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4974)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4982)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7672)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7641)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7602)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4725)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>

**Comment by patrickgold** [comment] 2022-08-29 23:20
Duplicate of #2001. Closing thus.

**Closed by patrickgold** 2022-08-29 23:20 UTC
Labels: bug
