### ISSUE TITLE
Keys can get stuck with active visuals

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1446] opened 2021-12-16 09:45 UTC
#### Short description
https://user-images.githubusercontent.com/59611881/146347672-a5ff32a9-dc6e-445f-ad2c-94996ef41132.mp4

#### Steps to reproduce
1. Hold the clipboard-manager icon
2. Hold ANY other key
3. Let go of the clipboard-manager-button
4. Go back to the main keyboard
5. See active-looking keys

#### Environment information
- FlorisBoard Version: 0.3.14-beta07 (63)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by Glitchy-Tozier** [comment] 2021-12-16 09:49
1. You'll never be safe, Patrick 😈
2. The same thing can also be triggered by holding down one of the buttons in the upper smart-bar, then closing that smasrt-bar using this button:
![Screenshot_20211216-104850_GitHub.jpg](https://user-images.githubusercontent.com/59611881/146348373-5ae947a0-c074-4b3f-8089-e4171996e8f1.jpg)

**Comment by patrickgold** [comment] 2021-12-16 15:11
> You'll never be safe, Patrick 😈

I already accepted my fate :)

The technique you use here is the same logic bug as the one you use to produce the stuck popup in your other issue. Will fix that when I fix the stuck popup too.

**Comment by patrickgold** [comment] 2022-04-09 15:31
Finally got around to fix these bugs. Above PR is (hopefully) a fix for the bug, at least I couldn't reproduce it anymore. Will be released with 0.3.15-rc02 today. Thanks again for reporting this!

Should you still be able to reproduce it with your magic logic-break-find skills I need to continue investigating and fixing the lifecycle logic :)

**Closed** 2022-04-09 15:35 UTC
Labels: bug, area: kbd-ui, bug-confirmed

**Comment by Glitchy-Tozier** [comment] 2022-04-09 16:33
Damn, now I'll have to go on a search to find new bugs :P
