### ISSUE TITLE
Input field for testing in settings

### ISSUE THREAD

**Issue by Tmpod** [florisboard/florisboard#348] opened 2021-02-14 00:37 UTC
I believe it would be rather nice to have some way of pulling up a dummy text field where you could type to see the changes you made in effect. Perhaps a floating button that would show the field, or a permanent bar at the top? Not sure about the best UX, but it is something I liked in SwiftKey, but failed to see in any other keyboard I've tried.

**Comment by D3SOX** [comment] 2021-02-14 08:53
Duplicate of #190

**Closed** 2021-02-14 10:29 UTC
Labels: proposal
