### ISSUE TITLE
Use the Paste icon for the selection screen 

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#384] opened 2021-02-20 17:26 UTC
The current arrows icon for the selection screen is not intuitive, and has no relation to the clipboard. I'd suggest using the Paste (clipboard) icon, which generally represents the clipboard operations, instead.
Although there are  the cursor movement buttons in there, their purpose is mostly to assist the cut/paste actions.

**Comment by yashpalgoyal1304** [comment] 2021-02-20 17:55
can u check if this is a duplicate of #316 ?

**Comment by MisterY** [comment] 2021-02-20 18:20
@yashpalgoyal1304, kinda.
It would be a duplicate if that issuewas still open. Plus, that issue is asking to replace a different-looking icon.
I got confused by the arrows icon, which is in use in 0.3.7.

**Comment by yashpalgoyal1304** [comment] 2021-02-20 18:37
> arrows icon, which is in use in 0.3.7

ohhkay, the update is not yet available in f-droid. So, i think that that the pr related to that issue is still in dev phase.

**Comment by MisterY** [comment] 2021-02-22 08:27
I'm old school ;)

<img src="https://user-images.githubusercontent.com/462445/108682031-177d6900-74f0-11eb-9f59-7271dbdd9cb1.jpg" width="20rem" />

**Comment by patrickgold** [comment] 2021-12-12 17:18
The selection screen itself as known when this issue was created does not exist anymore, and will return in a completely different form at a later stage. Thus there's no need to replace the icon for this screen anymore and I will close this issue.

**Closed by patrickgold** 2021-12-12 17:18 UTC
Labels: proposal, area: smartbar
