### ISSUE TITLE
Normal Numpad Numbers height is miniscule

### ISSUE THREAD

**Issue by yashpalgoyal1304** [florisboard/florisboard#354] opened 2021-02-14 11:25 UTC
Split from https://github.com/florisboard/florisboard/issues/341 (4)

#### Short description
The numbers on numpad are way too small, and doesnt fit. Feels weird using it. And the dialer numpad (of florisboard) is completely different too, i thought they were same thing. (the bottom one - not to scale). I am mentioning dialer numpad in the hope that maybe it can suggest something on how can normal numpad and its layout be improved.
![1photo_2021-02-12_23-30-49]
![q6HAggbrop]

[1photo_2021-02-12_23-30-49]: https://user-images.githubusercontent.com/19423063/107851466-2d27ca00-6e30-11eb-898f-d6bc42ad4b5b.jpg
[q6HAggbrop]: https://user-images.githubusercontent.com/19423063/107852192-66af0400-6e35-11eb-98f5-421ff648fba6.png

dialer numpad = the numpad which shows when saving a contact, dont know if that's its proper name.

#### Steps to reproduce
-  open keyboard > symbols view <kbd>?123</kbd> > numpad view <kbd>1234</kbd>

#### Environment information
- FlorisBoard Version: 0.3.5
- Install Source: F-Droid
- Device: Jivi Prime P30
- Android version, ROM: 7.0 (seems AOSP)

**Comment by X-yl** [comment] 2021-02-14 17:06
I think this is caused by the bug I found [here](https://github.com/florisboard/florisboard/pull/338#issuecomment-778568497) 

See screenshots:

After fix:
<img src="https://user-images.githubusercontent.com/28653555/107883357-050b9a00-6f08-11eb-9f41-f20c4dae7e73.jpg" width=300>

Before fix:
<img src="https://user-images.githubusercontent.com/28653555/107883358-076df400-6f08-11eb-993e-6f9377b53d5b.jpg" width=300>




So it would be fixed if/when that PR  is merged.

**Comment by patrickgold** [comment] 2021-02-14 17:11
Good catch on that one, thanks! I will link the PR to this issue then.

**Closed** 2021-02-27 11:24 UTC
Labels: bug, bug-confirmed
