### ISSUE TITLE
Search for Emojis in Emoji-Drawer

### ISSUE THREAD

**Issue by Duvio** [florisboard/florisboard#989] opened 2021-06-03 09:04 UTC
It would be nice if you could search for the name of an Emoji in the Emoji-Drawer like you can do with GBoard

**Comment by Glitchy-Tozier** [comment] 2021-06-03 10:20
Hi and thank you for your feature request. It has already been proposed in #45, so i suggest we close yoir issue, if you don't mind.  :)

Funnily enough, it's a duplicate of the oldest FlorisBoard issue that is still open.

**Comment by Duvio** [comment] 2021-06-03 22:22
Ah, i searched for a similar proposal but didnt see this one, probably because it was so far behind

Should i close the issue ?

**Comment by Glitchy-Tozier** [comment] 2021-06-04 06:14
Yes, plaese.

Should ideas come up regarding how to best implement this feature, make sure to share them in #45!  :)

**Closed** 2021-06-04 16:56 UTC
Labels: proposal
