### ISSUE TITLE
Spellchecker / Autocorrect is not working

### ISSUE THREAD

**Issue by Dismade** [florisboard/florisboard#1302] opened 2021-10-01 16:47 UTC
#### Short description
The spellchecker was working great for me, then it randomly stopped working. It's not because of any settings I changed. Even after reinstalling it doesn't work anymore.

#### Steps to reproduce
N/A

#### Environment information
- FlorisBoard Version: 0.3.1.3
- Install source: F-Droid
- Device: Samsung Galaxy S10
- Android: 11

**Comment by lilithium-hydride** [comment] 2021-10-02 14:06
Looks like a duplicate of #1268.

**Comment by BobIsMyManager** [comment] 2021-10-02 16:10
#1268 is for word prediction, not spell checker

**Comment by lilithium-hydride** [comment] 2021-10-02 19:57
I figured it was related to the same heap size issue, particularly with the mention of having to load dictionaries and that filling up the memory.

**Comment by BobIsMyManager** [comment] 2021-10-02 20:58
Just checking, spellchecker only works on english US?

**Comment by patrickgold** [comment] 2021-10-04 22:17
I don't know why, but it seems like it only indexes the en_US spelling dictionary for some reason (normally all installed dictionaries regardless of language are supported). As I am currently rewriting the theme and spelling extension code in the preference rework I will address this issue.

**Closed** 2021-10-14 21:34 UTC
Labels: bug, bug-confirmed, area: spellchecking

**Comment by FlorentLM** [comment] 2021-11-09 20:37
It still does not autocorrect for me, and it only offers suggestions for english words even though i have two languages installed
