### ISSUE TITLE
Properties share between different rules using codes in themes.

### ISSUE THREAD

**Issue by Keepkeepzz** [florisboard/florisboard#1626] opened 2022-03-08 09:48 UTC
#### Short description
Having 1 key code in 2 different rules will share the properties between the 2 rules for keys that aren't set in both of them. In the screenshot only 10 is set to have blue background but 113 and 114 have it too.

#### Steps to reproduce
1. Create a new theme.
2. Make a rule for key, set foreground to ffffffff and font size to 22.
3. Add rule for key and add any code (10 in screenshot).
4. Add any property to the rule (background blue in screenshot)
5. Create another key rule with the same code from the previous rule then add other codes (113 and 114 in screenshot)
6. Results

#### Environment information
- FlorisBoard Version: 0.3.14-beta14
- Install Source: IzzyOnDroid Repo
- Device: Nokia 7.1
- Android: 10, Stock

![Screenshot_20220308-221330](https://user-images.githubusercontent.com/99106227/157209260-f818998a-78e9-4e92-b30d-89c0585596e2.png)

**Comment by patrickgold** [comment] 2022-03-19 18:52
Thanks for your bug report!

This bug was a particular nasty one, as it is the result of a simplified merging logic. I now adjusted the stylesheet compiler and rule matcher and now using your given example it does behave as intended and no incorrect sharing is occuring.

Note that the rules are applied in the same order as shown in the stylesheet order - meaning if you define a background=RED for `key[code=10]` and background=BLUE for `key[10,113,114]`, the enter key (code 10) will have a blue background.

Will be released in 0.3.14-rc03.

**Closed by patrickgold** 2022-03-19 18:52 UTC
Labels: bug, bug-confirmed, area: kbd-theme
