### ISSUE TITLE
Crash report after reboot

### ISSUE THREAD

**Issue by GL513** [florisboard/florisboard#1560] opened 2022-02-09 23:45 UTC
#### Short description
Rebooted device and florisboard crashed

#### Steps to reproduce
1. Reboot device
2. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-A516V
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1644447148765.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 208632 free bytes and 203KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 49020928 bytes)
	at dev.patrickgold.florisboard.ime.dictionary.NgramNode.<init>(temp_suggestion_code.kt:187)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1009)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by Glitchy-Tozier** [comment] 2022-02-10 13:24
Duplicate of #1268.
The crashes you experience are OutOfMemory issues, which are caused by word suggestions. The current workaround is to disable word suggestions if they cause trouble and wait for version 0.3.15, where Patrick will re-implement them to make sure this specific crash does not occur again.

**Closed by Glitchy-Tozier** 2022-02-10 13:24 UTC
Labels: bug, duplicate
